### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by kdmurray91** [biocore/scikit-bio#1012]
Hi all,

Thanks for making scikit-bio, I really like it. I was wondering if anyone had looked into packaging of skbio for Debian? If not I could attempt to do so if you would like, under the Debian Med project.

Cheers,
Kevin

**Comment by ebolyen** [comment]
Hey @kdmurray91, thanks for your interest! I think right now we are probably more interested in using `conda` to package scikit-bio. Though a Debian package might be interesting in the future.

**Comment by jairideout** [comment]
@kdmurray91 though we are targeting conda for packaging/distributing scikit-bio, I think having it available via Debian Med would be very convenient for users already set up in that environment. Please let us know if there's anything we can help you with, and thanks for offering to work on this!

**Comment by kdmurray91** [comment]
OK, I'll start work from the 0.4.0 tarball. Will let you know how it goes.

**Comment by gregcaporaso** [comment]
Awesome, thanks @kdmurray91!

**Comment by kdmurray91** [comment]
Status update: Andreas Tille beat me to it to an extent, so 0.2 is packaged and uploaded. 0.4.0 is waiting on numpy 1.9.2 to move out of the experimental distribution, then it should "just work".

**Comment by jairideout** [comment]
Thanks for the update @kdmurray91! Would you be interested in contributing some simple install instructions to README.rst?

**Comment by kdmurray91** [comment]
Sure, 0.4.0 was just uploaded to the NEW queue, so I'll write the install instructions into the readme once it hits Debian sid.

Cheers,
K

**Comment by jairideout** [comment]
Sounds good, thanks @kdmurray91!

**Comment by jairideout** [comment]
Fixed in #1320.
