### ISSUE TITLE
Do we need a PairwiseAlignment object?

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1015]
Currently we only have `Alignment` which represents a multiple sequence alignment. We also need to be able to represent multiple alignments to a single reference (#1014 ). This makes it unclear what alignment functions should return, as they could justifiably return a reference based alignment. What if we had these objects:

- `MultipleAlignment`
- `ReferenceAlignment`
- `PairwiseAlignment`

where the `PairwiseAlignment` will be a default case for two sequences and can be converted to a `MultipleAlignment` or a `ReferenceAlignment`.

**Comment by gregcaporaso** [comment]
I think that sounds reasonable, but why not have the pairwise aligners just return a ``MutlipleAlignment`` containing two sequences (i.e., what does ``PairwiseAlignment`` do that ``MultipleAlignment`` wouldn't)?

**Comment by ebolyen** [comment]
I guess there wouldn't be a difference, and we could have a method which could create a `ReferenceAlignment` from two sequences in a `MultipleAlignment`. Though I think we would only ever be able to support a conversion for a single read and reference from a `MultipleAlignment` as any more would produce a `ReferenceAlignment` that wasn't independent (unless I am thinking about this wrong). I think that is where the `PairwiseAlignment` starts to make sense as the user never gets to ask the question of "why only 2?", but maybe that doesn't matter.

**Comment by jairideout** [comment]
Closing in favor of #1288.
