### ISSUE TITLE
link scipy 2015 presentation from website

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#1016]

**Comment by ebolyen** [comment]
There doesn't seem to be a good way to export a RISE presentation statically. Would a link work fine?

**Comment by gregcaporaso** [comment]
You can now do presentation mode in nbviewer, so you can link [here](http://nbviewer.ipython.org/format/slides/github/biocore/scikit-bio-presentations/blob/master/scipy-2015/A%2520Bioinformatics%2520Library%2520for%2520Data%2520Scientists%252C%2520Students%252C%2520and%2520Developers.ipynb#/).

**Comment by ebolyen** [comment]
It might be better to actually link to the video presentations. We can link to the repo (and migrate those other presentations)

**Comment by ebolyen** [comment]
Here it is [rendered](http://nbviewer.ipython.org/format/slides/github/ebolyen/scikit-bio-presentations/blob/scipy2015rendered/scipy-2015/A%2520Bioinformatics%2520Library%2520for%2520Data%2520Scientists%252C%2520Students%252C%2520and%2520Developers.ipynb). I guess it mostly works

**Comment by gregcaporaso** [comment]
What if you linked to both, e.g.:

SciPy 2015 (video, slides)

Different people will want to view it different ways I think, so this would be ideal.

**Comment by ebolyen** [comment]
Conceptually we could even do a page with an iframe of both. Would that be worthwhile?

**Comment by ebolyen** [comment]
Actually we don't have a template engine, so I'm not super excited about that approach anymore.

**Comment by gregcaporaso** [comment]
It'd be cool, but lower priority than a lot of other stuff, so unless it's really quick I think just links to both for now is fine.

**Comment by ebolyen** [comment]
Funny story, doing the link will actually be more work because of the CSS styling used to make the dropdown work. I think the fastest option would actually be to jekyllize it and then have a page for each

**Comment by gregcaporaso** [comment]
Eh, let's just link to either videos or the static versions of the slides for now then (could update both links to point to nbviewer). I don't want us to spend a bunch of time on this right now - we could always revisit with other website updates in the future.

**Comment by ebolyen** [comment]
A PR is in with the video links in that case.

**Comment by gregcaporaso** [comment]
Merged, thanks!
