### ISSUE TITLE
Need name and github account for benchmark bot

### ISSUE THREAD

**Issue by anderspitman** [biocore/scikit-bio#1020]
Our asv benchmarking framework will need a bot to report progress on automated benchmarking builds. We need to create a github account with an unused email address for the bot. Anyone have strong feelings about naming it something other than `scikit-bio-benchmarks`? Also, is there an email address available to use for this purpose?

**Comment by ebolyen** [comment]
@emperor-helper, @qiimer-2d2 thoughts?

**Comment by emperor-helper** [comment]
@ebolyen 

```
KOKUSHI called to his attendant: "Oshin!"

Oshin replied, "Yes."

Kokushi called "Oshin!"

Oshin replied, "Yes."

Kokushi called again, "Oshin!"

Oshin replied again, "Yes."

Kokushi said, "I apologize for all this calling of your name. But
in truth you should apologize to me!"
```

**Comment by wasade** [comment]
qiiminator
tijuanomicsed
birdpoop (...the result of air speed velocity)
no-prokaryote
obi-sic-kit (
http://wordsmith.org/anagram/anagram.cgi?anagram=scikitbio&t=1000&a=n)
hit-it-with-a-biostick
turtle-or-hare

**Comment by wasade** [comment]
Regardless of everything, I vote that this be the avatar for the bot:

![](https://imgur.com/nRad65z.jpg)

**Comment by ElDeveloper** [comment]
Not very suggestions, but:

- scikitten-bio: supplemented by rotating lolcat.
- mr-pickle: with the cowboy-pickle artwork that we found at that bar in
  Austin (at last SciPy).

**Comment by ElDeveloper** [comment]
:+1: on the avatar!

**Comment by wasade** [comment]
![image](https://cloud.githubusercontent.com/assets/474290/8998473/01b67574-36eb-11e5-8e49-5acbe6204380.png)

**Comment by wasade** [comment]
also, love the scikitten-bio

**Comment by qiime-r2d2** [comment]
![mr-pickle](https://cloud.githubusercontent.com/assets/3912941/9010626/e7e94fbe-375c-11e5-9349-f44bf972562d.jpg)

**Comment by ebolyen** [comment]
:+1: for `scikitten-bio`

**Comment by jairideout** [comment]
:+1: for `scikitten-bio`

**Comment by anderspitman** [comment]
Shall I open a gmail for it or do we have an address pool to pull from?

**Comment by ebolyen** [comment]
We could do something like `no-reply@scikit-bio.org`

**Comment by ebolyen** [comment]
We don't have mail servers or anything, but that's almost the point.

**Comment by anderspitman** [comment]
Won't we have to send a verification email?

**Comment by ebolyen** [comment]
I suppose we would

**Comment by scikitten-bio** [comment]
scikitten-bio is a dumb name

**Comment by wasade** [comment]
![](http://media2.fdncms.com/orlando/imager/feeling-emo-post-a-stupid-kitten/u/original/2333798/544419_753117664836_672543526_njpg)

**Comment by ElDeveloper** [comment]
![](https://lh3.googleusercontent.com/-CbVebKED0Dc/UghPCm_I7fI/AAAAAAAACfE/CkIHV5SdnE0/w322-h281/4742_1ed2.gif)
