### ISSUE TITLE
Parameterized Generators in IO

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1024]
Currently it is not possible to take advantage of automatic format sniffing for generators.

Our API requires that we write:

```python
seqs = skbio.io.read(some_file, format='fasta', into=None)
```

As `into` and `format` cannot both be `None`. (This is to prevent `seqs = skbio.io.read(some_file)` which obscures entirely what one could expect `seqs` to be.)

Suppose we had a mechanism to describe the subtype of the generator in `into`.

I propose something like the following:
```python
seqs = skbio.io.read(some_file, into=lambda:DNA)
```

Using `lambda` is easy to type, fits well inline, and we can differentiate this from other kinds of types. Unfortunately it has no real semantic relation to generators other than the idea that both are an eta-abstraction.

**Comment by jairideout** [comment]
What about having a keyword argument `stream=None` that can be passed a type (e.g., `DNA`) if the generator is parameterizable? This way, `into` is used to read the file *into* an object, while `stream` is used to stream the file. We could keep the current behavior of `into=None` for backwards compatibility.

**Comment by ebolyen** [comment]
Spinning off of that, what about:
```python
seqs = skbio.io.read(file, into=DNA, stream=True)
```

This would also have a potentially nice symmetry with any registrations and would be pretty painless to augment IO for:

```python
@format.reader(DNA, stream=True)
def _format_to_dna_stream(fh):
    ...
```

**Comment by jairideout** [comment]
:+1:

**Comment by wasade** [comment]
Well... that's totally badass.
