### ISSUE TITLE
Cannot parse FASTA file into SequenceCollection of DNA sequences

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/scikit-bio#1034]
It seems that if you want to read a FASTA file into a `SequenceCollection` object of `DNA` objects, the only way is to read in using `SequenceCollection` and then casting all the sequences to `DNA` objects and store them in a different sequence collection.

**Comment by wasade** [comment]
Possible to provide a code sample?

**Comment by ebolyen** [comment]
Have you checked our docs for [FASTA](http://scikit-bio.org/docs/latest/generated/skbio.io.format.fasta.html#reader-specific-parameters)? :wink: 
```python
In [2]: sc = SequenceCollection.read(['>\n', 'ACGT'], constructor=DNA)

In [9]: sc[0]
Out[9]: 
DNA
-----------------------------
Metadata:
    'description': ''
    'id': ''
Stats:
    length: 4
    has gaps: False
    has degenerates: False
    has non-degenerates: True
    GC-content: 50.00%
-----------------------------
0 ACGT
```

**Comment by ElDeveloper** [comment]
Thanks, yeah that makes sense. The reason why I didn't find this is
because I was trying to use skbio.io.read, and then I was looking at
SequenceCollection.read; see the links below:

http://scikit-bio.org/docs/latest/generated/skbio.alignment.SequenceCollection.read.html#skbio.alignment.SequenceCollection.read

http://scikit-bio.org/docs/latest/io.html

Unless I missed something, there's no mention there about constructors.

**Comment by jairideout** [comment]
Each file format's readers and writers may define their own keyword arguments, this is why `skbio.io.read` (the most general way to read a file in scikit-bio) and `SequenceCollection.read` (supports many formats) don't list `constructor` in their docs. Instead, `constructor` is described in the FASTA format docs because it is a format-specific parameter.
