### ISSUE TITLE
I/O support for BED file formats 

### ISSUE THREAD

**Issue by hanfang** [biocore/scikit-bio#1038]
Hi all,

I think scikit-bio can benefit from adding support for the BED files, as this file is one of the most used files in bioinformatics. I can implement this if people think it's worth it.

You can find descriptions of the BED format here: https://genome.ucsc.edu/FAQ/FAQformat.html#format1
There are in total 12 fields for this file, with nine of them being optional.
 
The first three required BED fields are:
* chrom - The name of the chromosome (e.g. chr3, chrY, chr2_random) or scaffold (e.g. scaffold10671).
* chromStart - The starting position of the feature in the chromosome or scaffold. The first base in a chromosome is numbered 0.
* chromEnd - The ending position of the feature in the chromosome or scaffold. The chromEnd base is not included in the display of the feature. For example, the first 100 bases of a chromosome are defined as chromStart=0, chromEnd=100, and span the bases numbered 0-99.

**Comment by wasade** [comment]
:+1:

@RNAer @ebolyen, I think this at least overlaps with #986

**Comment by ebolyen** [comment]
That sounds awesome @hanfang. How did you want to manipulate this data? From my brief glance at the format, it looks like something we would read into a `pandas.DataFrame`, does this sound right? Or were you considering something else? Are these files generally associated with a sequence file as well? We might be able to do something similar to what `FASTA` and `QUAL` do.

**Comment by hanfang** [comment]
I am thinking about `<pandas.DataFrame>`. BED files do not have to be associated with a sequence file. At the beginning, it was used for defining and visualizing tracks on [UCSC Genome Browser](https://genome.ucsc.edu/). Later people used it a lot for describing genomic intervals. Let me take a look at what you have done with `<FASA>`, `<QUAL>`. It is important to be consistent. Thanks guys!

**Comment by ebolyen** [comment]
Sounds great, thanks @hanfang!

**Comment by mortonjt** [comment]
This seems to overlapping with the IntervalMetadata object : https://github.com/biocore/scikit-bio/issues/1159
