### ISSUE TITLE
Better error in the situation when a sequence has valid, but lowercase characters

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1041]
Currently it just complains that the letter isn't in the alphabet, but in practice there is a good chance that it is just lowercase. We should augment the error when this is the case so that it informs the user about the `lowercase` keyword. That way, they have an actionable path forward.

**Comment by colinbrislawn** [comment]
Where is this error thrown? In here:
https://github.com/biocore/scikit-bio/blob/master/skbio/sequence/_sequence.py

**Comment by ebolyen** [comment]
@colinbrislawn It is actually in this file:
https://github.com/biocore/scikit-bio/blob/master/skbio/sequence/_iupac_sequence.py#L194

**Comment by ebolyen** [comment]
The sequence objects are a little tricky because they are backed by `ndarrays` instead of strings, which let's us do a lot of fancy stuff really fast. Feel free to ping us if you are interested in this and need help at any point! (I'm happy to guide you through how the sequence objects generally operate as well)

**Comment by colinbrislawn** [comment]
Note to self: here is how to create this error message.

``` python
from __future__ import absolute_import, division, print_function
import unittest
import numpy as np
import numpy.testing as npt
from skbio import Protein
```

Get error message: `Protein('paW')`
Suppress error message: `Protein('paW', lowercase=True)`

**Comment by colinbrislawn** [comment]
@ebolyen @jairideout 

Any suggestions on error message text? The current error is
``` python
>>> Protein('paW')
Traceback (most recent call last):
...
ValueError: Invalid characters in sequence: ['a', 'p']. Valid IUPAC characters: ['A', 'C', 'B', 'E', 'D', 'G', 'F', 'I', 'H', 'K', 'M', 'L', 'N', 'Q', 'P', 'S', 'R', 'T', 'W', 'V', 'Y', 'X', 'Z', '*', '-', '.']
```

Perhaps:
```
ValueError: Invalid characters in sequence: ['a', 'p'].
Lowercase letters are not used in IUPAC notation. You can pass 'lowercase=True' if your sequence contains lowercase letters. 
Valid IUPAC characters: ['A', 'C', 'B', 'E', 'D', 'G', 'F', 'I', 'H', 'K', 'M', 'L', 'N', 'Q', 'P', 'S', 'R', 'T', 'W', 'V', 'Y', 'X', 'Z', '*', '-', '.']

**Comment by jairideout** [comment]
@colinbrislawn this looks good! Minor suggestion: I would use single backticks instead of quotes for consistency with other scikit-bio error messages:

```
You can pass `lowercase=True` if your sequence...
```
