### ISSUE TITLE
add __format__ support to I/O registry

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1047]
It'd be awesome to support Python's `format` protocol as an extension of I/O, such that it understands any scikit-bio file format defined for an object:

```python
format(DNA('ACGT')) # return str(), this already works
format(DNA('ACGT'), 'fasta') # return FASTA-formatted str
format(DNA('ACGT'), 'qseq') # return QSEQ-formatted str
...
```

See [here](https://docs.python.org/3/library/functions.html#format) for details.

**Comment by ebolyen** [comment]
:+1:

**Comment by gregcaporaso** [comment]
:+1:

**Comment by wasade** [comment]
That's so clean
