### ISSUE TITLE
RFC: tabular-msa

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1053]
Please send all discussion to:
https://github.com/biocore/scikit-bio-rfcs/pull/1

Depending on the resolution of the RFC, this issue will be updated to organize the work that needs to be done.

**Comment by ebolyen** [comment]
Milestone that tracks this RFC:
[RFC 1: tabular-msa](https://github.com/biocore/scikit-bio/milestones/RFC%201:%20tabular-msa)

**Comment by ebolyen** [comment]
RFC complete!

**Comment by gregcaporaso** [comment]
awesome!!!

**Comment by anderspitman** [comment]
:+1:
