### ISSUE TITLE
Adding ANCOM to `skbio.stats.composition`

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#1054]
I've been discussing with @wdwvt1 and @rob-knight offline about implementing [ANCOM](http://www.ncbi.nlm.nih.gov/pubmed/26028277) in qiime/skbio.

ANCOM is another differential abundance detection method.  In addition to the benchmarks in the paper, I've constructed a few benchmarks on ANCOM myself, and it completely kills Mann-Whitney and t-test for detecting differences in species abundances across different simulated samples.

I was thinking about pushing a PR for the core method in `skbio.stats.composition`.    There are a couple of functions that'll need to be added, namely multiple hypothesis correction and the actual ANCOM method.  I do have a draft of the code [here](https://github.com/mortonjt/ANCOM/blob/master/ancom/stats/ancom.py) just for testing - the PR that I'll be pushing out will be a bit different (i.e. no GPU backend).  

Once this is merged, then we can get started on submitting the CLI to qiime.

**Comment by ebolyen** [comment]
@mortonjt I think this is the perfect kind of statistic to have in scikit-bio! Could you update your post to reflect exactly what and where this will be added? (I'm assuming this is really just a single function somewhere). If it is a little beefier than that, we also have a poorly described (at this time) RFC process: https://github.com/biocore/scikit-bio-rfcs. But I think that is probably overkill for this.

**Comment by jairideout** [comment]
Fixed in #1114.
