### ISSUE TITLE
Add Pielou's evenness as an alpha diversity metric

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/scikit-bio#1068]
There is a cool alpha diversity metric of evenness which is based on Shannon entropy. I know this metric as ['Pielou's evenness'](https://en.wikipedia.org/wiki/Species_evenness).

Similar metrics are already included in scikit-bio these include [equitability](https://github.com/biocore/scikit-bio/blob/master/skbio/diversity/alpha/_base.py#L207), [Heip's evenness](https://github.com/biocore/scikit-bio/blob/master/skbio/diversity/alpha/_base.py#L454), and Shannon itself.

Colin

**Comment by jairideout** [comment]
:+1: this would be great! Are you interested in contributing this function to scikit-bio?

**Comment by colinbrislawn** [comment]
Yes, I am! I may stumble through some of this process like unit testing,
but I'll give it a shot.

Colin

**Comment by ebolyen** [comment]
Awesome @colinbrislawn, feel free to send us a ping if you get stuck or need help!

**Comment by colinbrislawn** [comment]
First try!

How do you updated documentation on `gh-pages`? I included inline documentation, but was not sure how to test it or see if I formatted it correctly.

**Comment by gregcaporaso** [comment]
@colinbrislawn, the docs in gh-pages aren't something that you'd update yourself, we do that at build time. You can build the docs locally to confirm that they're rendering correctly by changing into the ``docs/`` directory, and running ``make html``. This will create a local version of the documentation, and you can navigate to the alpha diversity docs and confirm that everything looks right. You should review [this page](https://github.com/biocore/scikit-bio/blob/master/doc/README.md) to make sure that your environment is configured correctly for building the docs.

**Comment by jairideout** [comment]
Awesome, thanks for working on this @colinbrislawn! In addition to the scikit-bio doc README that @gregcaporaso linked, our [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md) guide should be helpful in getting started with scikit-bio contributions.

**Comment by colinbrislawn** [comment]
@jairideout I've been making great use of [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md). It's very well written.

@gregcaporaso I'll try using `make html` now. I know how finicky markup can be, and wanted to see it to believe it.
