### ISSUE TITLE
add Sequence method to compute character frequencies

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1074]
It would be useful to have a way of computing the frequencies of characters (or a subset of characters) in a sequence. Currently the way to do this is `seq.kmer_frequencies(k=1)`, which handles the frequencies of characters present in the sequence but does not support a subset of characters.

It could also be useful to have this functionality on `Sequence` because iterating over positions in an alignment will yield `Sequence` objects. See the [`TabularMSA` RFC](https://github.com/biocore/scikit-bio-rfcs/pull/1) for potential `Alignment` API changes, which will *not* include the current `Alignment.position_frequencies` functionality.

@ebolyen and I propose adding the method `Sequence.frequencies(chars=None, relative=False)` where:

- `chars=None` produces the frequencies of characters in the sequence. Equivalent to `seq.kmer_frequencies(k=1)`.
- `chars` will accept either a single-character string or a `set` of single-character strings indicating characters to include in the frequency calculations. We only support single-character strings to avoid confusion with substring matching (use `Sequence.count` or `'foo' in seq` for this). We don't want users to run something like `seq.frequencies(chars='ACGT')` and expect to get a frequency distribution back for each character.
- `relative` matches `Sequence.kmer_frequencies`, returning relative frequencies when `True`
- the method returns the same type of output as `Sequence.kmer_frequencies`

**Comment by gregcaporaso** [comment]
+1

**Comment by ebolyen** [comment]
:+1:
