### ISSUE TITLE
add Sequence method to return set of observed characters

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1075]
@ebolyen and I propose adding the method `Sequence.observed_chars()`, which returns the `set` of characters observed in the sequence.

This seems like a useful piece of the sequence API as it mirrors class methods describing the alphabet such as `gap_chars`, `degenerate_chars`, etc. The set of observed characters can then be referenced or composed with other pieces of the sequence API, such as `Sequence.frequencies` (proposed in #1074).

**Comment by ebolyen** [comment]
:+1:

**Comment by gregcaporaso** [comment]
:+1:
