### ISSUE TITLE
`TabularMSA`: join

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1093]
From [RFC](https://github.com/biocore/scikit-bio-rfcs/blob/master/active/001-tabular-msa.md):

- `join(TabularMSA, how='strict') -> TabularMSA`

   Joins two `TabularMSA` by sequence (horizontally). `how` may be
   `'strict'`, in which case both MSAs must have the same keys (or be the same
   length if there are no keys). `how` may also be one of the common SQL joins:
   `'inner'`, `'outer'`, `'left'` (outer), or `'right'` (outer); these require
   keys or they will raise an exception. `how` is a superset of the interface
   provided by pandas. Outer based modes will insert gaps for missing keys.
   This should be documented as *not* preforming an alignment.

**Comment by dansondergaard** [comment]
I can give this a go in the coming weeks.

**Comment by jairideout** [comment]
@dansondergaard I'm going to take this one, we're nearing our 0.4.1 release (currently scheduled for 12/9) and trying to wrap things up on `TabularMSA`.

@ebolyen is currently working on `__getitem__`/`loc`/`iloc`, we'll ping you on #1139 when that's in if you're still interested in working on `TabularMSA.sample`.

**Comment by dansondergaard** [comment]
@jairideout Still interested in `TabularMSA.sample`, but you're welcome to take this one! :)
