### ISSUE TITLE
`TabularMSA`: extend

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1097]
From [RFC](https://github.com/biocore/scikit-bio-rfcs/blob/master/active/001-tabular-msa.md):

- `extend(iterable | TabularMSA) -> None`

   Add sequences to the end of the alignment. Each sequence must be the same
   `dtype` and length must match second dimension. It should be documented
   that this operation, if successful, is not necessarily meaningful.

**Comment by anderspitman** [comment]
This can be implemented in terms of `append`. I can take it.

**Comment by anderspitman** [comment]
If a `TabularMSA` is provided, do we want to bring additional data along with the sequences, ie keys, etc?
