### ISSUE TITLE
`TabularMSA`: iter_positions

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1100]
From [RFC](https://github.com/biocore/scikit-bio-rfcs/blob/master/active/001-tabular-msa.md):

- `iter_positions(reverse=False) -> iterator`

   Iterator of *exactly* `Sequence` objects in the order of positions in the
   alignment. If `reverse=True`, yields positions in reverse order.

**Comment by anderspitman** [comment]
Possibly stupid question: what does this method do?

**Comment by anderspitman** [comment]
Nevermind, I just noticed this functionality exists in the current `Alignment` class.

**Comment by anderspitman** [comment]
Dibs
