### ISSUE TITLE
`TabularMSA`: __getitem__

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1102]
From [RFC](https://github.com/biocore/scikit-bio-rfcs/blob/master/active/001-tabular-msa.md):

- `__getitem__(indexer) -> TabularMSA | Sequence`

   Accepts 1 or 2 axes separated by a comma. The rules for axes are applied
   from left to right. The least significant axis can only restrict the type
   returned, it cannot take what would have been `DNA` and return a
   `TabularMSA`. This restriction makes it easier to mentally model the
   indexing behavior. So the following must always hold:

   ```python
   aln[X, Y] == aln[X][:, Y] # or [Y] if the result is 1D
   ```

   #### First axis:
   If the index is a single key or an ordinal, return an `IUPACSequence` of
   type `dtype`:

   ```python
   aln['a'] -> DNA
   aln[0] -> DNA
   ```

   If the index is a slice or other complex structure of keys or ordinals,
   return `TabularMSA`:

   ```python
   aln[2:4] -> TabularMSA
   aln['b':'e':2] -> TabularMSA
   aln[['a', 'c']] -> TabularMSA
   aln[[1]] -> TabularMSA
   aln[[True, False, False, True]] -> TabularMSA
   ```

   In the event that the keys are integers, any index composed of them will be
   assumed to be in relation to keys and not indices
   (like `pandas.DataFrame.ix`). It is advisable to use `iloc` and `loc` in
   these situations. If there are no keys for the MSA, then the index will
   always be in relation to the indices.

   #### Second axis:
   The second axis will accept only column indices (e.g ordinals, slices,
   etc.). If the first axis has already narrowed the type returned to a
   `IUPACSequence` object, then the second axis is simply treated as an
   additional filter to that object:

   ```python
   aln[2, 4:7] -> DNA
   aln[0, 0] -> DNA
   ```

   Otherise:

   ```python
   aln[2:3, 4:7] -> TabularMSA
   ```

   If the type so far is a `TabularMSA` and the second axis is an ordinal, then
   *exactly* the type of `Sequence` will be returned. The exact `dtype` is not
   returned because the sequence does not represent a real biological sequence
   but rather a column in the alignment. A `Sequence` object is returned
   because it is convenient to reuse the existing numpythonic-string API that
   `Sequence` classes posses.

   ```python
   aln[:, 3] -> Sequence
   aln['a':'d', 3] -> Sequence
   ```

**Comment by ebolyen** [comment]
@jairideout and I have discussed that we may need to change the semantics here a little:

`TabularMSA.keys` is an `ndarray`; unfortunately `asarray` will do it's best to make an array monomorphic before giving up and using an `object` dtype. This means that very often mixed types will be unified in unexpected ways. To avoid this we can make `TabularMSA.keys` always have an `object` dtype which will be less efficient, but lossless. Because all we really want out of `keys` is fancy indexing, we don't really need to worry about the efficiency, the user can always convert the type if they want to do math (why would they ever do that???). 

This has the unfortunate side-effect of making `getitem` indexing less easy to define. Suppose you had `keys` that looked like this: `[1, 'a', 2, 3, 'b']`. Ignoring the strangeness of these keys, how would `getitem` resolve: `aln[1:3]`. Under the above rules, we would expect it to convert to the proper indicies: `slice(0, 3)`, but how would it make the determination that `1` and `3` represented keys rather than indicies. Because `TabularMSA.keys` will have the dtype of `object` we would need to do a linear pass each time to determine if the slice could be construed as keys over indicies. This is a huge performance hit to accommodate what is basically a poor practice anyways. `iloc` and `loc` should have been used when the `keys` are integers anyways to remove ambiguity. 

So instead of taking a linear pass through keys each time a slice occurs, we could change the rule to assume integer indices/slices are **always** proper indices. Because we have a mechanism for interpreting them as keys via `loc` the user isn't out anything.

Of course an alternative to all of this would be to enforce that `keys` are always monomorphic, but that results in 2 contextual rules (error happens if not monomorphic, and slicing depends on the state of keys) vs 2 static rules (keys are object dtype, and integers are always proper indices in `getitem`). So modifying the rule seems to be the cognitively simpler approach.

**Comment by jairideout** [comment]
:+1:
