### ISSUE TITLE
Allow `skbio.util._misc.resolve_key` to take an iterable

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1111]
This will allow `DistanceMatrix.from_iterable` to have keys be an iterable instead of just a lookup key, or function. This will also help out `TabularMSA`. 

Note:
We should exclude strings as being considered iterable, if that behavior is desire, the user would need to pass `iter(string)` instead of `string` to keep it from being considered a lookup key.

**Comment by jairideout** [comment]
:+1:

**Comment by ebolyen** [comment]
So it turns out resolve_key is not a good place for this, instead `from_iterable`, `TabularMSA()`, and `reindex` should probably accept both `key` and `keys`. Where `keys` embodies the new functionality. This also improves the semantics of `TabularMSA.sort` where an iterable as `key` does not make any sense.

Having both also prevent any ambiguity about resolving a string (which is iterable).
