### ISSUE TITLE
Adding metadata in skbio.TreeNode

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#1117]
This is related to the discussion in #1108 

Noticed that the same problem of dealing with metadata also shows up in `skbio.TreeNode`
It would super awesome if there is a way to assign metadata in the same fashion as the `skbio.SequenceCollection`

**Comment by ebolyen** [comment]
:+1: This would also allow us to support the [`NHX`](http://home.cc.umanitoba.ca/~psgendb/doc/atv/NHX.pdf) format for interoperability with `ete`.

**Comment by jhcepas** [comment]
regarding the interoperability layer between the upcoming ete3 version and scikit-bio tree objects, any feedback here would be great:  https://github.com/jhcepas/ete/issues/137

**Comment by mortonjt** [comment]
I'm going to close this.  Metadata can be added to the tree objects pretty easily.
For example, the following can be run
```python
from skbio import TreeNode
>>> t = TreeNode.read(['(a, b)c;'])
>>> t.foo_am_not = False
>>> print(t.foo_am_not)
False
```
