### ISSUE TITLE
Create GitHub page for hosting benchmark results

### ISSUE THREAD

**Issue by anderspitman** [biocore/scikit-bio#1119]
@scikitten-bio will need push privileges

**Comment by jairideout** [comment]
Is this going under gh-pages for this repo?

**Comment by anderspitman** [comment]
Isn't that where scikit-bio.org is currently hosted? You thinking maybe make it a subpage?

**Comment by jairideout** [comment]
Yep that's where scikit-bio.org is hosted. I think a subpage makes sense. Just sent @scikitten-bio an invite to the organization and push team.

**Comment by anderspitman** [comment]
Weird I'm not seeing it from that account. BTW if anyone needs the login info for @scikitten-bio let me know.

**Comment by jairideout** [comment]
GitHub says the invite is pending. Did you receive an email at the address @scikitten-bio is registered with?

**Comment by anderspitman** [comment]
Ah didn't realize it was an email. Done

**Comment by anderspitman** [comment]
It occurs to me that we may not want to store the benchmark results in this repo. A new directory will be created for every pull request, and even if we delete old ones periodically it will bloat the history over time. Thoughts @jairideout and @ebolyen?

**Comment by anderspitman** [comment]
The more I think about it I think maybe we don't want per-PR benchmark results stored in git, which brings up the question of how big of a problem would it be to keep powertrip serving up those results? I definitely think we should post results for master in the repo in a long-term fashion.

**Comment by jairideout** [comment]
Maybe it's worth pushing all benchmarks to S3 instead so they're centralized, we don't have to expose powertrip to the world, and our gh-pages repo avoids bloat. @anderspitman @ebolyen thoughts?

**Comment by anderspitman** [comment]
That feels a little too complicated to me. Is exposing powertrip that much worse than exposing an AWS instance?

**Comment by jairideout** [comment]
You don't need to expose an EC2 instance with S3 (for example, S3 can be used to [host a static site](http://docs.aws.amazon.com/AmazonS3/latest/dev/HostingWebsiteOnS3Setup.html)). This solution seems simpler IMO because we can host all benchmarks from a single place (S3) instead of gh-pages and powertrip (which is also a security vulnerability).

**Comment by anderspitman** [comment]
Gotcha. Seems like a good solution for the PR benchmarks, and we can still plan to us gh-pages for master.

**Comment by ebolyen** [comment]
:+1: for S3, it's cheap and easy.

**Comment by jairideout** [comment]
I was thinking of using S3 for PR benchmarks **and** master. Any reason not to?

**Comment by anderspitman** [comment]
Just that for master we are interested in saving the benchmarks over time and the files won't constantly be being created and deleted so it's a good fit for git.

**Comment by ebolyen** [comment]
I agree on git for master, that makes it easy to pull in the appropriate results for a PR. Then the amalgamated results can be pushed to S3. There's really two systems, one tracks master. And the other needs bits of master and a separate directory for each PR. 

Actually...
Is there a reason benchmarks of a branch couldn't be in a git branch and powertrip just exports that to S3 in the needed directory. So the git repo could hold the raw data, and powertrip converts branches to individual directories with all of the extra presentation html for S3?

**Comment by jairideout** [comment]
Sorry if I wasn't clear, what didn't make sense to me was the use of `gh-pages` and S3. :+1: to Evan's idea of having powertrip run the benchmarks, store them in a git repo, and then push to S3.

**Comment by anderspitman** [comment]
@jairideout @ebolyen do we have an S3 location ready to be used for this?

**Comment by jairideout** [comment]
I don't think we have anything set up yet. I'll chat with @gregcaporaso and @ebolyen tomorrow about setting something up.

**Comment by anderspitman** [comment]
I believe this can be closed.
