### ISSUE TITLE
Build failing in 2.7 and 3.4

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1144]
```
======================================================================

ERROR: test_corr (skbio.stats.ordination.tests.test_util.TestUtils)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda3/envs/env_name/lib/python3.4/site-packages/skbio/stats/ordination/tests/test_util.py", line 45, in test_corr

    obs = corr(self.small_mat)

  File "/home/travis/miniconda3/envs/env_name/lib/python3.4/site-packages/skbio/stats/ordination/_utils.py", line 173, in corr

    x = scale(x)

  File "/home/travis/miniconda3/envs/env_name/lib/python3.4/site-packages/skbio/stats/ordination/_utils.py", line 123, in scale

    a -= avg

TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

----------------------------------------------------------------------
```

Looks like a package (numpy probably) has just been updated.

**Comment by ebolyen** [comment]
Will work on a fix today.

**Comment by ebolyen** [comment]
If I correct the dtype mismatch we get some dramatically different results:
```
======================================================================
FAIL: test_corr (__main__.TestUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "skbio/stats/ordination/tests/test_util.py", line 49, in test_corr
    obs)
  File "/home/evan/.conda/envs/skbio/lib/python3.4/site-packages/numpy/testing/utils.py", line 494, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/home/evan/.conda/envs/skbio/lib/python3.4/site-packages/numpy/testing/utils.py", line 886, in assert_array_almost_equal
    precision=decimal)
  File "/home/evan/.conda/envs/skbio/lib/python3.4/site-packages/numpy/testing/utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 100.0%)
 x: array([[ 0.3333333,  0.       , -0.3333333],
       [ 0.       ,  0.       ,  0.       ],
       [-0.3333333,  0.       ,  0.3333333]])
 y: array([[ 1.       ,  1.       , -0.9449112],
       [ 1.       ,  1.       , -0.9449112],
       [-0.9449112, -0.9449112,  1.       ]])
```

Any ideas?

**Comment by ebolyen** [comment]
I can replicate this behaviour exactly in Numpy 1.9 by changing the following:

```python
    if with_mean:
        # a -= avg            current
        a = a - avg
    if with_std:
        std[std == 0] = 1.0
        # a /= std            current
        a = a / std
```

I think the broadcasting rules are different between these two operations. However, I am not sure which is actually correct.

**Comment by ebolyen** [comment]
I see what is happening:

In 1.9 with `x op= thing` we get the dtype of `x`:
```
[[ 0  0  0]
 [-1  0  1]
 [ 0  0  0]]
```
But when it is `x = x op thing` we get type coersion:
```
[[ 0.70710678  0.70710678 -0.26726124]
 [-1.41421356 -1.41421356  1.33630621]
 [ 0.70710678  0.70710678 -1.06904497]]
```

I'm inclined to believe our current behaviour is buggy.

**Comment by ebolyen** [comment]
Actually that has to be backwards. I think `thing` is cast down to `int` in the above case, and left alone in the second. The numbers don't even match when the floor of the result is taken.

**Comment by ebolyen** [comment]
@Jorge-C It looks like you wrote this code, could you advise as to what the correct output should be?

Presently our code is implicitly downcasting the results of `mean_and_std` in `skbio.stats.ordination._util.scale` to whatever the dtype of the input matrix was. Should there (semantically) be a floor function in here? Or is the test incorrect?

**Comment by Jorge-C** [comment]
The input `a` should be casted to a float64 array. This means the test output is wrong and needs to be updated (it doesn't matter in any other code because the functions that call it use float64 arrays).

Also, I've just found out that `skbio....corr(x)` is equivalent to `np.corrcoeff(x.T)`. I'm not sure if any of the functions in `util` were meant to be exported.

I can submit a PR today that fixes this mess.

**Comment by ebolyen** [comment]
That would be awesome @Jorge-C! Also moving forward if we can drop `corr` for `np.corrcoeff` that would be ideal.
