### ISSUE TITLE
Arrange Act Assert in unit tests?

### ISSUE THREAD

**Issue by anderspitman** [biocore/scikit-bio#1149]
A lot of our unit tests have multiple assertions, reuse local variables, etc. This isn't really in alignment with the general practice of ["Arrange, Act, Assert"](http://c2.com/cgi/wiki?ArrangeActAssert) style tests. Ideally we would have one assertion per test. This doesn't necessarily mean a single assert call, but it means you only test one thing. Moving in this direction does require more tests (though they're smaller and simpler), which necessitates breaking down into test suite classes and more fully utilizing test fixtures.

I think this would be a desirable direction to move, at least for new tests. Thought?

**Comment by ebolyen** [comment]
I like this pattern, especially as it basically negates using `setUp` which I feel makes most tests pretty hard to maintain. Way too much of our code still operates as a single test for a given method. I'm not arguing for or against, but frankly I wouldn't be against creating a test-class for each method. Or at least a test-class for each protocol/interface. 

Do you think AAA precludes using a loop to deal with multiple arrange steps with identical act/assert? There are some tests which would expand to 5 or 6 individual tests that would be identical if not for the arrange step.

**Comment by jairideout** [comment]
:+1: for starting to use this pattern (I really like having a class for testing each method). I'm curious too about @ebolyen's question, these sorts of tests happen a lot in practice.

**Comment by wasade** [comment]
:+1:

**Comment by anderspitman** [comment]
@ebolyen I'm not sure what you mean when you say this negates using `setUp`. I try to use `setUp` extensively even when using AAA to reduce duplication. Maybe we're not talking about quite the same thing here.

As for loops, I think we should try to keep them if possible, at least for some cases. I think the key principle is that you want to minimize the risk that a test depends on the results of a previous test. So loops do introduce a higher risk of that, but I think it's reasonable. On the other hand loop tests are very difficult to maintain. I remember back when we were changin `Sequence` that was a huge pain to try and figure out how to shoehorn new (or removed) functionality into the test loops.

I guess overall I'm not too religious about what approach we take, so much as I feel we don't really have many conventions currently so there's a lot of variation in testing methodology.

**Comment by RNAer** [comment]
:+1: on AAA

**Comment by gregcaporaso** [comment]
I think this is a good idea for new tests, but not worth the time to port
existing tests (too much other stuff that's higher priority).

**Comment by ebolyen** [comment]
My only gripe about `setUp` is it couples the evolution of test cases and adds some indirection. You can't safely modify anything created in setUp without potentially violating the test conditions for some other test case resulting in spurious test passes. Basically putting actual data in setup feels wrong, if we are creating connections or managing resources that seems completely fine, but I feel that the semantics of a test-case should remain local to that test-case.

**Comment by josenavas** [comment]
:+1: on AAA

**Comment by jairideout** [comment]
@ebolyen :+1:, I try to avoid `setUp` now for the reasons you listed (basically DRY gone wrong)
