### ISSUE TITLE
[ENH] Cannot write SequenceCollection to StringIO object

### ISSUE THREAD

**Issue by dansondergaard** [biocore/scikit-bio#1152]
I'm trying to do this (in Python 2.7):

```python
def _dump_fasta(seqs):
    strio = StringIO()
    sk.write(seqs, format='fasta', into=strio)
    return strio.read()
```

This is pretty useful if you e.g. want to call BLAST from Python, but do not want to write a file with the query sequences to disk first. Writing to StringIO as FASTA and the passing that to the subprocess with `communicate()` is pretty useful. Unfortunately it doesn't work.

```
/Users/das/Code/scikit-bio/skbio/io/util.pyc in _resolve(file, mode, encoding, errors, newline, compression, compresslevel)
     65     if newfile is None:
     66         raise IOSourceError(
---> 67             "Could not open source: %r (mode: %r)" % (file, mode))
     68 
     69     return newfile, source, is_binary_file(newfile)

IOSourceError: Could not open source: <cStringIO.StringO object at 0x108f5e998> (mode: 'w')
```

The [documentation](http://biocore.github.io/scikit-bio/docs/0.4.0/generated/skbio.io.registry.write.html#skbio.io.registry.write) is a bit weird too, stating that the object which is written into much be "openable". Shouldn't it just be writable?

**Comment by ebolyen** [comment]
Hey @dansondergaard, you just have to use [`io.StringIO`](https://docs.python.org/2/library/io.html#io.StringIO#io.StringIO). It has the same API, but it uses unicode and therefore is encoding agnostic which is important to our IO system.

I would definitely recommend giving the entire [`io` subpackage](https://docs.python.org/2/library/io.html#io.StringIO) in Python a look, not many realize it exists. It is basically the same IO that Python 3 uses. 

It also looks like that documentation isn't linking correctly, ideally it would link to `skbio.io.util.open` which has [this table](http://scikit-bio.org/docs/latest/generated/generated/skbio.io.util.open.html#skbio.io.util.open).

**Comment by ebolyen** [comment]
Looks like links for the docs were already fixed in master.

**Comment by dansondergaard** [comment]
@ebolyen Thanks! Changed to use `io.StringIO` and that works perfectly. I actually thought that `io.StringIO` was the same as `StringIO.StringIO`.

Seeing the table for for `skbio.io.util.open` helped a lot, good to hear that the link has already been fixed! :)
