### ISSUE TITLE
test_genbank fails on non-US locale

### ISSUE THREAD

**Issue by jdrudolph** [biocore/scikit-bio#1153]
I was unable to pass all test for `scikit-bio` due to an assumed US locale and `datetime.strftime` in `skbio/io/format/genbank.py`. The error can be reproduced using:

    LC_TIME=de_DE.UTF-8 make test

will fail on '18-DEZ-2001' != '18-DEC-2001', while

    LC_TIME=en_US.UTF-8 make test

runs without error. I'm not sure if this is a bug i.e. if genbank requires US date formatting. If US formatting is required there does not seem to be a 100% waterproof solution. You could probably

    import locale
    locale.setlocale(locale.LC_TIME, "en_US")

but this will fail if the `en_US` locale is not installed on the system. Using a third party library such as `babel` would add another dependency but would also provide a cleaner solution to handling dates

    >>> from datetime import datetime
    >>> dt = datetime(2001, 12, 18, 0, 0)
    >>> from babel.dates import format_date
    >>> import locale
    >>> locale.setlocale(locale.LC_TIME, 'de_DE') # set 'wrong' locale
    >>> format_date(dt, 'yyyy-MMM-dd').upper() # will produce unintended result
    u'2001-DEZ.-18'
    >>> format_date(dt, 'yyyy-MMM-dd', locale='en_US').upper() # will produce expected result
    u'2001-DEC-18'

**Comment by ebolyen** [comment]
@jdrudolph Thanks for the report! This is very interesting, I suspect genbank would be a US locale, @RNAer do you know the answer to that?

**Comment by RNAer** [comment]
hmmm, good point. I am not sure either. I haven't seen a non US locale
record, though. To be more tolerant, we can also remove the date string
parsing. Just store the string alternatively.

**Comment by jairideout** [comment]
:+1: for removing the date string parsing. Any objections to me working on this?

**Comment by RNAer** [comment]
not at all. go for it!

**Comment by jairideout** [comment]
PR here: #1263
