### ISSUE TITLE
RFC: py3-only

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1168]
Please send all discussion to:
https://github.com/biocore/scikit-bio-rfcs/pull/6

Depending on the resolution of the RFC, this issue will be updated to include a milestone to track this RFC.

**Comment by ebolyen** [comment]
Milestone that tracks this RFC:
- [ ] [RFC 2: py3-only](https://github.com/biocore/scikit-bio/milestones/RFC%202:%20py3-only)

**Comment by jairideout** [comment]
Fixed in #1315.

**Comment by wasade** [comment]
Congratulations!!

**Comment by RNAer** [comment]
woo-hoo!
