### ISSUE TITLE
`TabularMSA`: __repr__

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1172]
Not sure what this looks like yet.

**Comment by jairideout** [comment]
@ebolyen and I came up with the following:

![img_1721](https://cloud.githubusercontent.com/assets/1847232/11345276/18cd8a66-91d3-11e5-9447-051f57040f9f.JPG)

Details:

- Similar to `Sequence` repr -- all lines should fit within a doctest-friendly width. There is code accounting for many of these details already so it can likely be refactored and reused on `Sequence` and `TabularMSA`.
- Display class name and parameterized type (`dtype`)
- Metadata and positional metadata repr is the same as `Sequence` (that code should be moved to the metadata mixins)
- Stats section displays MSA shape
- Alignment section displays head and tail of the alignment (up to five lines total including the ellipsis line). The head and tail of each sequence is displayed, and each sequence occupies a single line. Note the space before and after each ellipsis, this is to prevent confusion with "." gap character.

Note: `__repr__` and `__str__` will be the same (`__str__` calls `__repr__`).

@anderspitman is this something you'd be able to work on over the next few days?

**Comment by wasade** [comment]
Just two minor questions, pandas supports changing the number of rows/columns shown on `repr`. Are display settings like that going to be available and modifiable at runtime? Second, should the output include sequence IDs?

**Comment by ebolyen** [comment]
@wasade Potentially, but really we just need something and quickly. So mark both of those cases as future enhancements for this repr.

**Comment by anderspitman** [comment]
@jairideout yep I can work on this.

**Comment by jairideout** [comment]
@anderspitman thanks, assigned!

**Comment by anderspitman** [comment]
@jairideout @ebolyen is it ok if the common functionality lives in `util`?

**Comment by jairideout** [comment]
What functionality specifically? The metadata formatting code should move to the mixins, not sure what other shared code there is for the reprs but `skbio._base` is probably a good location.
