### ISSUE TITLE
Use Amazon S3 for static hosting

### ISSUE THREAD

**Issue by anderspitman** [biocore/scikit-bio#1184]
Once https://github.com/anderspitman/autobencher/pull/42 is merged into autobencher (close to finished), benchmark results will be pushed up to s3, to the scikit-bio.org/benchmarks directory. We need that directory set up to host static content.

**Comment by ebolyen** [comment]
@anderspitman, here is an example endpoint until we migrate the actual domain:
https://s3-us-west-2.amazonaws.com/scikit-bio.org/benchmarks/pull_requests/anderspitman/add_asv_config_and_benchmarks/index.html

**Comment by scikitten-bio** [comment]
Purrrfect

**Comment by anderspitman** [comment]
:+1:

**Comment by ebolyen** [comment]
Of course!

**Comment by anderspitman** [comment]
@ebolyen I see no reason not to close this. autobencher is working fine using the full URLs. The URLs are pretty much transparent to the users. So unless you want this left open feel free to close.
