### ISSUE TITLE
Segmentation fault on module import 

### ISSUE THREAD

**Issue by grayfall** [biocore/scikit-bio#1188]
I'm trying to install a new release of scikit-bio into a fresh virtualenv environment. I keep getting a segfault any time I try to import `skbio` or anything from `skbio`. I tried installing with pip and manually (setup.py build; setup.py install). I'm running on Ubuntu server 14.04, Python 2.7.6,  numpy/scipy/matplotlib/cython are all freshly deployed in the virtual environment.

**Comment by Jorge-C** [comment]
Hi @grayfall, would you mind pasting the traceback or error messages, if any? Thanks!

**Comment by grayfall** [comment]
Hello @Jorge-C, I'd gladly do that if there was a traceback. I can only tell that `python -m skbio.test` immediately returns a segfault as does any attempt to import `skbio` in ipython (even trying to evoke autocompletion by tabbing after `from skbio import` causes a segfault). I've downgraded to the previous release and it works fine.

**Comment by Jorge-C** [comment]
That's puzzling. Does it also happen if you install it via conda? I.e., use [miniconda](http://conda.pydata.org/miniconda.html) to create an environment, and then `conda install scikit-bio`?

**Comment by grayfall** [comment]
@Jorge-C it works fine with conda.

**Comment by Jorge-C** [comment]
Thanks for trying that, I'm glad it works! I'm not sure how to further debug the issue, though. Can you import fine numpy/scipy/matplotlib? If you have the installation log, could you post it please?

**Comment by grayfall** [comment]
@Jorge-C yes, I can import them. I no longer have the logs and I don't recall any errors during installation. Anyway, I guess the problem is related to virtualenv. I'll try to reinstall everything (including Python) from scratch and give it another shot.

**Comment by mortonjt** [comment]
@grayfall reopen if this hasn't been addressed

**Comment by grayfall** [comment]
@mortonjt I found the issue, but forgot to write back. This error happens when `matplotlib`'s backend is not properly configured on a server: https://askubuntu.com/a/771843/421439. The issue will not show up when you simply try to import the root `matplotlib` module, though. That's why it was not easy to isolate.

**Comment by grayfall** [comment]
@mortonjt I guess, you can mark this thread as closed. And I think adding a word or two about it in your documentation might help someone in the future. Thanks for your time.

**Comment by wasade** [comment]
I'm closing as I'm unsure what the specific guidance to provide a user is, or how to recreate the issue. The thread here documents what is known should another user encounter this type of segfault.
