### ISSUE TITLE
pcoa documentation doesn't contain a "Returns" section

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#1205]
I also can't find the docs for ``OrdinationResults`` - are those being linked from anywhere?

**Comment by jairideout** [comment]
It's possible `OrdinationResults` isn't being linked after it was moved from `skbio.stats.ordination` to `skbio._base` (importable from `skbio.OrdinationResults`). I'm not sure where/how we should link to this class, it's in an odd location now. Probably worth fixing this when we tackle the various diversity subpackages/classes (ContingencyTable, DistanceMatrix, alpha/beta diversity, etc.).
