### ISSUE TITLE
add Sequence.replace

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#1222]
This should likely take a boolean vector and a character to assign to all sequence positions corresponding to ``True`` values in the boolean vector. This would be useful, for example, for replacing all gap characters with the default gap character, or all degenerate characters with a single degenerate character (likely ``N``).

**Comment by ebolyen** [comment]
Depending on how people feel, we could also support both of these statements:
```python
with sequence.replace(mutate=True) as raw:
	raw[[3, 2, 1]] = [b'A', b'C', b'T']
```
and
```python
sequence.replace([3, 2, 1], b'N')
```

**Comment by jairideout** [comment]
:-1: for the first example. I think sequence data should remain immutable unless we have a real need for mutability. If we want to support mutability, the `__setitem__` API is likely more intuitive for users:

```python
sequence[[3, 2, 1]] = [b'A', b'C', b'T']
```

**Comment by ebolyen** [comment]
Good point
