### ISSUE TITLE
Add permdisp to distance stats 

### ISSUE THREAD

**Issue by johnchase** [biocore/scikit-bio#1228]
I am unable to find a python implementation of permdisp, and it seems like it fit well in scikit-bio and would be useful in conjuction with permanova which is already present. There is a good description of permdisp and it's value [here](http://www.esajournals.org/doi/abs/10.1890/12-2010.1).

Additionally the current version of QIIME [compare_categories.py](https://github.com/biocore/qiime/blob/master/qiime/compare_categories.py#L95) calls permdisp from R. This could be easily replaced in future versions of QIIME if implemented in scikit-bio.

**Comment by gregcaporaso** [comment]
:+1: This will be an important addition as we're planning to use it as a default in QIIME 2.

**Comment by lkursell** [comment]
Any movement on this one?

**Comment by gregcaporaso** [comment]
No, I wish. I'd love to get this in QIIME 2, but it's not highest priority for us at the moment (though if someone did get it in scikit-bio I'd get it hooked up to `qiime diversity beta-group-significance` quickly).

**Comment by lkursell** [comment]
+2
