### ISSUE TITLE
TreeNode.prune does not collapse single descendants from root properly

### ISSUE THREAD

**Issue by wasade** [biocore/scikit-bio#1247]
I noticed this while working on a collapse [method](https://github.com/wasade/yummy-octo-duck/blob/master/ipynb/Tree%20array%20shearing.ipynb) (i.e., prune) for the tree arrays. The expectation is that `((a,b)c)extra;` should become `(a,b)c` as `extra` only contains a single child. Interestingly, the collapse happens partially if there are multiple extras where `(((a,b)c)extra1)extra2;` becomes `((a,b)c)extra2;`.

```python
09:25:16 (daniel@sandbar):repicking> t = TreeNode.read(["((a,b)c)extra;"])

09:26:00 (daniel@sandbar):repicking> print(t.ascii_art())
                    /-a
-extra--- /c-------|
                    \-b

09:26:03 (daniel@sandbar):repicking> t.prune()

09:26:05 (daniel@sandbar):repicking> print(t.ascii_art())
                    /-a
-extra--- /c-------|
                    \-b
```

**Comment by jairideout** [comment]
@wasade, any bandwidth to work on this for the release? Ideally this could be fixed proper, but raising a `NotImplementedError` is also a big improvement over a silent bug.

**Comment by wasade** [comment]
Sure. Just for reference, I believe the only change necessary is to make [`include_self=True`](https://github.com/biocore/scikit-bio/blob/master/skbio/tree/_tree.py#L382)...

**Comment by jairideout** [comment]
Awesome, thanks @wasade!
