### ISSUE TITLE
Incorporate parser and data container for sequence assembly graphs?

### ISSUE THREAD

**Issue by tanaes** [biocore/scikit-bio#1249]
In talking with Zech and Jamie during a code review yesterday about the positional metadata problem (#1159), one thing that came up was incorporating support for graph-based representation of sequence collections (e.g. assemblies). Most microbial genomes aren't closed, and FASTA format leaves out a bunch of information about the relationships among contigs that can be recovered from the assembler. Would it be useful to have a way to explicitly encode that information within Skbio? In particular, this seems like it would be useful for projects comparing or manipulating large numbers of microbial genome assemblies.

There are a number of formats for representing assembly graphs currently in use, but [GFA](https://github.com/pmelsted/GFA-spec/blob/master/GFA-spec.md) in particular seems well specified and in use by a number of tools, such as the [BANDAGE](https://github.com/pmelsted/GFA-spec/blob/master/GFA-spec.md) assembly graph visualization tool. 

**UPDATE:** this is the same as issue #1248.

-j

**Comment by gregcaporaso** [comment]
Let's close this in favor of #1248.
