### ISSUE TITLE
problem in header when parsing fasta file with skbio.io.read

### ISSUE THREAD

**Issue by amnona** [biocore/scikit-bio#1252]
when i parse a fasta file with skbio.io.read:
    it=skbio.io.read(inputname, format='fasta')
    for cdat in it:
        seqid=cdat.metadata['id']

if the header of the fasta sequence contains spaces, it is truncated at the first space
(so for header >AY230771.1.1483 Bacteria;Firmicutes;Clostridia;Clostridiales;Lachnospiraceae;Lachnoanaerobaculum;Eubacterium sp. 'Smarlab BioMol-2301231'
i get 'AY230771.1.1483'

**Comment by ebolyen** [comment]
Yes, the rest is in `cdat.metadata['description']`.

**Comment by ebolyen** [comment]
Here is the [note](http://scikit-bio.org/docs/latest/generated/skbio.io.format.fasta.html#sequence-header) in our documentation that describes how `metadata` is set by the `fasta` format.
