### ISSUE TITLE
Python 3 Travis build timeout

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1256]
Master branch Python 3 builds are timing out on Travis. Able to reproduce locally after updating packages in `ci/pip_requirements.txt`.

**Comment by jairideout** [comment]
Still not sure what's going on. I was only able to reproduce this locally after updating packages in `ci/pip_requirements.txt` and it only happens in Python 3.4/3.5. The issue didn't surface when I had only updated the conda packages in `ci/conda_requirements.txt`.

The test that's hanging indefinitely is `python skbio/io/format/tests/test_fastq.py TestReaders.test_fastq_to_generator_solexa`. Commenting out this test "fixes" the issue. Running the code in this test from an IPython session freezes so it isn't the testing framework.

I think this has something to do with the changes to generators, `StopIteration`, and `RuntimeError` detailed in [this PEP](https://www.python.org/dev/peps/pep-0479/). The code freezes when raising a `NotImplementedError`, which is a subclass of `RuntimeError`. Changing the error type to something other than `RuntimeError` fixes the issue (e.g., `ValueError` works fine).

If anyone has time to dig in that'd be great, otherwise I'll keep working on it on Friday.

**Comment by jairideout** [comment]
Accidentally closed from commit.

**Comment by ebolyen** [comment]
This bug is truly awful. :-1: :x: :100:

**Comment by ebolyen** [comment]
For anyone who wants to play along, this example will spin-lock if run as a unittest, or in IPython. Normal Python interpreter does not produce this bug.
```python
import unittest
import contextlib

@contextlib.contextmanager
def single_context():
    yield

class Example(unittest.TestCase):
    def test(self):
        with contextlib.ExitStack() as stack:
            stack.enter_context(single_context())
            raise NotImplementedError("!")

if __name__ == '__main__':
    unittest.main()
```

This appears to be related to the following:
[`contextlib.ExitStack introduces a cycle in exception __context__` ](https://bugs.python.org/issue25786)


... :-(

**Comment by jairideout** [comment]
This is a bug in Python and there isn't much we can do to fix it. Bumping this issue to 0.5.0 milestone since we have a workaround (contextlib2 version cap).

**Comment by kdmurray91** [comment]
I've just hit this bug running the tests as a part of the Debian packaging. Aside from disabling this test, is there any workaround independent of capping contextlib2's version (which is verboten in Debian)

**Comment by ebolyen** [comment]
We aren't aware of any at this time. The best we could do is create our own `ExitStack` which is functionally the same as just capping `contextlib2`. This is a pretty serious bug in CPython for us, but we don't really know when it will be resolved properly.

If anyone knows more about `__context__` chaining in CPython and what it's good for, we would love to learn more.

**Comment by kdmurray91** [comment]
@ebolyen unfortunately I'm not that well versed with this corner of Python. For now, I'll just comment that test out, with a note that this is a CPython bug and a reference to this github issue. 

After doing so I've noticed some other test failures, but I'm going to create a separate issue for those.

Cheers,
K

**Comment by ebolyen** [comment]
Thanks @kdmurray91. We are planning a maintenance release this Wednesday, so we would be happy to try and address anything else you can find.

**Comment by kdmurray91** [comment]
@ebolyen  see #1275 :)

**Comment by jairideout** [comment]
@ebolyen @kdmurray91 maybe it would be better for the code to raise an error that isn't a subclass of `RuntimeError` for now until the bug is fixed in Python? This way users won't get spinlocked if they have a newer version of contextlib2, and we can remove the version cap.

**Comment by kdmurray91** [comment]
@jairideout That sounds sane to me. Will that break any user code doing `try: x except RuntimeError: pass`though? (This isn't a part of skbio i'm very familiar with).

**Comment by jairideout** [comment]
It's possible, but we're only raising `NotImplementedError` in a single place: it happens when trying to read a FASTQ or QSEQ file with `variant='solexa'`, which immediately raises the error. Technically this is a backwards-incompatible stable API change but we didn't explicitly document that `NotImplementedError` would be raised and I doubt user code would be broken, so in practice this change may not be that big of a deal. @ebolyen what do you think?

**Comment by ebolyen** [comment]
Probably better than spinlocking the process... Would we change it to `ValueError` for now?

**Comment by jairideout** [comment]
Yeah that makes sense. I'll add this issue back to the 0.4.2 milestone.

**Comment by jairideout** [comment]
#1279 implements the temporary `ValueError` change.

**Comment by ebolyen** [comment]
Merged, I'm going to bump this to 0.5.0 where we can revisit if this has been fixed.

**Comment by jairideout** [comment]
@kdmurray91 heads up that you shouldn't need to comment out that spinlocked test case or contextlib2 version cap for the Debian package. (I'm hoping with 0.4.2 you won't need to make any source code changes when creating the Debian package, please let us know if that isn't the case.)

**Comment by kdmurray91** [comment]
@jairideout Sweet as, I'll test that as soon as 0.4.2 is released.

Thanks for being so friendly to package maintainers!! Makes life much easier for us. As an aside, you can view the current patch stack for debian [on git.debian.org](http://anonscm.debian.org/cgit/debian-med/python-skbio.git/tree/debian/patches)

**Comment by jairideout** [comment]
Great, thanks! We're working on fixing some of those patches now. Just posted a couple questions on Gitter about the ones we're not sure of. Note that [this patch](http://anonscm.debian.org/cgit/debian-med/python-skbio.git/tree/debian/patches/0005-Fix-test-failure-patch-from-upstream.patch) can be dropped for 0.4.2.

**Comment by jairideout** [comment]
Confirmed this bug still exists in Python, removing from 0.5.0 milestone.
