### ISSUE TITLE
rendering issues with built HTML docs

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1268]
Noticed a couple issues with the built HTML docs (including the ones currently hosted on scikit-bio.org):

1. Function/method/class signatures have an extra space between the object name and its import path (was the color change intentional?):

    Previous:

    ![screen shot 2016-02-08 at 10 45 43 am](https://cloud.githubusercontent.com/assets/1847232/12893922/2f46eade-ce51-11e5-9d81-7518490fe83a.png)

    Current:

    ![screen shot 2016-02-08 at 10 46 02 am](https://cloud.githubusercontent.com/assets/1847232/12893934/3d1703f6-ce51-11e5-85b5-2926495395d7.png)

2. Text enclosed with `**` isn't rendered as bold (for example, the last sentence in this paragraph should be bold):

    ![screen shot 2016-02-08 at 10 49 39 am](https://cloud.githubusercontent.com/assets/1847232/12894023/afe9f636-ce51-11e5-9320-b1e6bce159fd.png)

**Comment by ebolyen** [comment]
1. The spacing seems to be a CSS bug (padding of code cells, signatures weren't originally code cells at all). Color change wasn't intentional so much as a side-effect that didn't matter.
2. This must be an issue with the latest version, the current site shows bold.

**Comment by ebolyen** [comment]
Update on 2: this is probably caused by a font installation issue. I suspect the bold ubuntu font isn't provided by the CSS.

**Comment by jairideout** [comment]
Yep I can confirm 2 is a font issue, removing "Ubuntu" font fixes it for me in Chrome for Mac.
