### ISSUE TITLE
`skbio.io.write` does not play well with `tempfile.NamedTemporaryFile`

### ISSUE THREAD

**Issue by RNAer** [biocore/scikit-bio#1291]
```
from skbio import DNA, write
from tempfile import  NamedTemporaryFile
s = DNA('ATGC')
with  NamedTemporaryFile('w+') as f:
    s.write(f, format='fasta')
```

errors:
```
/Users/zech/anaconda/envs/py35/lib/python3.5/site-packages/skbio/io/util.py in _resolve_file(file, **kwargs)
    202 @contextmanager
    203 def _resolve_file(file, **kwargs):
--> 204     file, source, is_binary_file = _resolve(file, **kwargs)
    205     try:
    206         yield file, source, is_binary_file

/Users/zech/anaconda/envs/py35/lib/python3.5/site-packages/skbio/io/util.py in _resolve(file, mode, encoding, errors, newline, compression, compresslevel)
     65     if newfile is None:
     66         raise IOSourceError(
---> 67             "Could not open source: %r (mode: %r)" % (file, mode))
     68 
     69     return newfile, source, is_binary_file(newfile)

IOSourceError: Could not open source: <tempfile._TemporaryFileWrapper object at 0x10e96df60> (mode: 'w')
```

**Comment by ebolyen** [comment]
:+1: This should be possible to support once Python 2.7 is dropped. The `NameTemporaryFile` will then be composable file object.

**Comment by RNAer** [comment]
cool. just curious, when is the plan to drop python2 support?

**Comment by jairideout** [comment]
I'm in the process of dropping Python 2 from the codebase, PR coming soon. The next release of scikit-bio will be Python 3 only.

**Comment by RNAer** [comment]
:+1: awesome!

**Comment by RNAer** [comment]
The problem still persists since py2 support is dropped

**Comment by jairideout** [comment]
Right, I think there's additional work to be done to get this working but it's technically possible now that Python 2 isn't supported.

**Comment by ebolyen** [comment]
Looks like `NamedTemproraryFile` doesn't subclass `io.BufferedRandom`, instead wraps transparently. So all that is needed is to add an IOSource for `NamedTemporaryFile` to the `io` package. IO had to be written fairly defensively to avoid odd things between Py2/3. 

Something that should be verified is that the file is actually deleted when it goes out of scope.

**Comment by RNAer** [comment]
should check `delete` attribute of `NamedTemporaryFile` object to decide
whether to delete the file.
