### ISSUE TITLE
cleaner unittest with mock

### ISSUE THREAD

**Issue by RNAer** [biocore/scikit-bio#1294]
Some of the unittests can be improved with `unittest.mock` (https://docs.python.org/3/library/unittest.mock-examples.html)?

**Comment by jairideout** [comment]
That looks useful! If there are specific tests that you think should be using this, can you create new issue(s) with those details? I'll mark this issue as a question and close it.

**Comment by RNAer** [comment]
not at the moment, I'll create specific issues when I see them. just
brought this to the spotlight.

**Comment by jairideout** [comment]
Awesome, thanks!

**Comment by jairideout** [comment]
@gregcaporaso and I made use of `unittest.mock` for mocking parts of the QIIME 2 plugin system in unit tests ([PR here](https://github.com/biocore/qiime2/pull/42)). It's incredibly handy, thanks for pointing out this package @RNAer!

**Comment by RNAer** [comment]
no problem! I have been using it in micronota - it is very handy.
