### ISSUE TITLE
remove numpy bootstrap hack in setup.py

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1296]
This hack causes #997, which doesn't have a clear/clean fix. Since we're moving forward with conda, which doesn't have this problem, I think we should remove the hack and acknowledge that when installing scikit-bio with pip/setup.py, numpy must be installed first.

Update README.rst pip install instructions to be:

```
pip install numpy
pip install scikit-bio
```

**Comment by souravsingh** [comment]
I would like to work on the issue

**Comment by ebolyen** [comment]
Sounds great, thanks @souravsingh!
