### ISSUE TITLE
Installation error when I "pip install scikit-bio" on Windows 7 related to Visual C++ for Python

### ISSUE THREAD

**Issue by aaajjj333** [biocore/scikit-bio#1300]
I got this error when installing Scikit-bio on Windows 7..
Any Ideas???

cl : Command line error D8021 : invalid numeric argument '/Wno-error=declaration-after-statement'
error: command '"C:\Users\n8451214\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe"' failed with exit status 2

**Comment by ebolyen** [comment]
Hey @aaajjj333, I suspect this is related to the SSW package and Windows support in general (#702). We are planning on replacing those finicky components in 0.5.0 which should make scikit-bio installable on Windows. Until then, Windows isn't supported yet.
