### ISSUE TITLE
scipy not installed automatically when using conda

### ISSUE THREAD

**Issue by jhcepas** [biocore/scikit-bio#1301]
Hi guys,
Our ETE Travis tests stopped working recently due to unresolved dependencies of scikit-bio (conda 4.0.2, skbio 0.4.0):
https://travis-ci.org/etetoolkit/ete/jobs/115001565

we solved it by adding scipy explicitly to the conda installation (https://travis-ci.org/etetoolkit/ete/jobs/115063171 ), but you may want to check.

**Comment by jairideout** [comment]
@jhcepas it looks like your `conda install` command is grabbing scikit-bio 0.4.0 from Anaconda's default channel, which AFAIK we don't have control over. The official conda scikit-bio releases are available under the `biocore` channel (versions 0.4.1 and later). You can install that with:

```
conda install -c https://conda.anaconda.org/biocore scikit-bio
```

I'll close this for now, please reopen if that doesn't resolve your issue.
