### ISSUE TITLE
skbio cannot read newick trees with partitions

### ISSUE THREAD

**Issue by kdm9** [biocore/scikit-bio#1305]
Hi all,

I'm working a lot recently with genome simulations using tools like `scrm` and `ms`. These simulators output newick trees with a partition length (representing recombinations). The format of this is:

```
[partition_length](newick tree);
```

An example of this [comes with seq-gen](https://github.com/rambaut/Seq-Gen/blob/master/examples/recombinant.tree).

Currently `skbio.read('filename.nwk', into=TreeNode)` fails with:

``` python
>>> samp = skbio.read(treefile, into=TreeNode)
  File "/usr/lib/python3/dist-packages/skbio/io/registry.py", line 1135, in read
    **kwargs)
  File "/usr/lib/python3/dist-packages/skbio/io/registry.py", line 497, in read
    return self._read_ret(file, format, into, verify, kwargs)
  File "/usr/lib/python3/dist-packages/skbio/io/registry.py", line 503, in _read_ret
    io_kwargs)
  File "/usr/lib/python3/dist-packages/skbio/io/registry.py", line 525, in _init_reader
    fmt, skwargs = self.sniff(file, **io_kwargs)
  File "/usr/lib/python3/dist-packages/skbio/io/registry.py", line 428, in sniff
    % file)
skbio.io._exception.UnrecognizedFormatError: Could not detect the format of <_io.BufferedReader name='125467289/population.nwk'>
```

A minimal failing example is:

```
import skbio
from skbio import TreeNode
t = skbio.read('https://github.com/rambaut/Seq-Gen/raw/master/examples/recombinant.tree', into=TreeNode)
```

I'm not sure how best to store or represent this information, for now I'm parsing out the components so that I can do:

``` python
from skbio import TreeNode

def iter_part_nwk(fname):
    with open(fname) as fh:
        for line in fh:
            m = re.match(r'\[(.*)\](\(.*;)', line)
            if m:
                l, t = m.groups()
                yield int(float(l)), TreeNode.read([t])

for partlen, tree in iter_part_nwk('recombinant.tree'):
    print(partlen, tree)
```

I'm happy to make a PR implementing a function that does a more rigorous version of this if that is the best way you can think of to handle this data type.

Cheers,
K

**Comment by jairideout** [comment]
@kdmurray91 this sounds like a useful feature to have in scikit-bio, thanks for offering to work on it! Do you have a reference to where this format extension is defined?

I'm wondering if this should be its own format, separate from `format='newick'`. I could see having a generator reader (`into=None`) that yields a partition length and `TreeNode`, similar to what `iter_part_nwk` is doing.

@ebolyen I know you spent some time looking into newick variants, do you have thoughts about where this format should fit in the API?

**Comment by kdmurray91** [comment]
Hi @jairideout 

I have no reference (and can't find one) but the earliest program I know of that produces this format is [Hudson's ms](http://home.uchicago.edu/~rhudson1/source/mksamples.html).

**Comment by jairideout** [comment]
@kdmurray91 thanks for investigating!

**Comment by wasade** [comment]
Closing as it seems the format isn't well defined. Please reopen if this should continue to be examined.
