### ISSUE TITLE
`skbio.stats.composition` add biplot, use as agnostic information for binary partitioning

### ISSUE THREAD

**Issue by jsevo** [biocore/scikit-bio#1310]
Hi,

I would like to begin contributing to the composition functions. In particular, I think that adding another way(s) to construct an orthogonal basis for the ILR transform would be neat. I have no good overview over the state of scikit-bio, but it seems that you guys are in some form of transition state (I get a lot of "broken with latest pandas" etc emails).
Is there at all interest in moving the composition section forward or should i fork, and create my own thing which is not relying on the rest of scikit-bio to be in good shape?

**Comment by ebolyen** [comment]
Hey @jsevo master should be fixed by Monday, the `pandas` thing is just something that happens in this ecosystem. Pinging @mortonjt who knows more about the composition statistics in scikit-bio.

**Comment by mortonjt** [comment]
Hi @jsevo . Yes, we have definite interest in adding in other ways to construct orthogonal bases in the ILR transform.  This is why I added a [basis](https://github.com/biocore/scikit-bio/blob/master/skbio/stats/composition.py#L510) option in the `ilr` function

If you want to commit some code to make this happen - I'll be more than happy to review it.

**Comment by jsevo** [comment]
Awesome,
I'm only getting into compositional data analysis, so it might not happen
that rapidly. Will let you know when I got something I think worthwhile
committing!
J

**Comment by jairideout** [comment]
@jsevo thanks for your interest in contributing to scikit-bio!

> I have no good overview over the state of scikit-bio, but it seems that you guys are in some form of transition state (I get a lot of "broken with latest pandas" etc emails).

Adding to what @ebolyen said:

scikit-bio is currently in beta and under active development (see the disclaimer on http://scikit-bio.org). scikit-bio's public API has varying degrees of stability, see the [API stability guide](http://scikit-bio.org/docs/0.4.0/user/api_stability.html) for details. All functionality in `skbio.stats.composition` is experimental, so API changes can be made as necessary without deprecation (unless you're completely removing functionality, which I don't think is the case here).

The periodic "master is broken" issues usually happen when one of scikit-bio's dependencies has a new release (we're testing against the latest versions of most dependencies).

Let us know if you have any questions about contributing and thanks again!

**Comment by wasade** [comment]
Closing as I think this is more a question that appears addressed, but please reopen if this was closed prematurely
