### ISSUE TITLE
IO: return empty generator instead of raising StopIteration for empty file

### ISSUE THREAD

**Issue by RNAer** [biocore/scikit-bio#1313]
For file read into generator, currently it raises `StopIteration` instead of return a generator if the file has zero record in it. This is a surprising behavior that does not comply with idiomatic python. It should return a generator and raise `StopIteration` only after the call of `__next__`, like the `open` and other builtin python iterator creators do.

```
a = read('/tmp/empty.fa', format='fasta')

/scikit-bio/skbio/io/registry.py in read(file, format, into, verify, **kwargs)
   1145 def read(file, format=None, into=None, verify=True, **kwargs):
   1146     return io_registry.read(file, format=format, into=into, verify=verify,
-> 1147                             **kwargs)
   1148 
   1149 

/scikit-bio/skbio/io/registry.py in read(self, file, format, into, verify, **kwargs)
    507             # eta-reduction is possible, but we want to the type to be
    508             # GeneratorType
--> 509             return (x for x in itertools.chain([next(gen)], gen))
    510         else:
    511             return self._read_ret(file, format, into, verify, kwargs)

StopIteration: 
```
On line 509, what if we just allow the error of wrong format occurs later instead of checking immediately? I am not convinced to sacrifice pythonic behavior for this reason.

**Comment by ebolyen** [comment]
:+1: This is an edge case we hadn't thought of. Typically the empty file
sniffer jumps in first.

**Comment by RNAer** [comment]
yep, this happens for multiple formats I have tested... The ultimate solution is to modify skbio.io.registry

**Comment by mortonjt** [comment]
:+1:

**Comment by jairideout** [comment]
:+1:

**Comment by jairideout** [comment]
Fixed in #1369.

**Comment by wasade** [comment]
Possibly relevant:

https://www.python.org/dev/peps/pep-0479/

**Comment by ebolyen** [comment]
We handled that PEP in #1245, we used to raise `StopIteration`, but now we behave better. This `StopIteration` was a legit call of `next` happening without handling it like other iterators.
