### ISSUE TITLE
add Python 3-only disclaimer to front page

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1316]
This is a follow-up issue for #1315. Detailed in [py3-only RFC](https://github.com/biocore/scikit-bio-rfcs/blob/master/active/002-py3-only.md) implementation step 3.

**Comment by Carreau** [comment]
#1315 says:

>  install-time guard in setup.py, checklist.py, and doc/source/conf.py to prevent Python 2 users from installing/executing

I just discover that if you publish a `tar.gz` on PyPI that end in `-py3.4.tar.gz`, pip will assume it can only install on this specific version of Python. Thus you might be able to publish a few source dist, and have python 2 user just never see the upgrade and not get their system broken by upgrade. 

cf https://github.com/pypa/pip/issues/3182

Hope that can help.

**Comment by jairideout** [comment]
Awesome, thanks for finding this and letting us know @Carreau! We'll definitely do this for our next release.

**Comment by Carreau** [comment]
> Awesome, thanks for finding this and letting us know @Carreau! We'll definitely do this for our next release.

Well I don't know if it's a pip "feature", but for now it works. You just have to be carefull not tu publish a tgz without a pyX.Y ending, and maybe also pre-publish py3.6 and py3.7 in advance just in case... Which is not optimal, but at least you don;t break legacy python user that try to upgrade.

**Comment by jairideout** [comment]
Thanks for the info! It seems like a relatively simple change to our release process (we have a similar step for conda releases). I'll keep the setup.py install-time guards in case this "feature" stops working at some point.
