### ISSUE TITLE
add guide for Python 2 devs transitioning to Python 3

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1317]
This is a follow-up issue for #1315. Detailed in [py3-only RFC](https://github.com/biocore/scikit-bio-rfcs/blob/master/active/002-py3-only.md) implementation step 4.

@Jorge-C you wrote the [supporting Python 2/3 guide](http://scikit-bio.org/docs/latest/development/py3.html), which will be removed in #1315. Do you have any interest in submitting a guide for Python 2 devs transitioning to Python 3?

**Comment by mortonjt** [comment]
We have switched to py3 yay
