### ISSUE TITLE
test against latest dev version of Python 3

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1318]
This is a follow-up issue for #1315. Detailed in [py3-only RFC](https://github.com/biocore/scikit-bio-rfcs/blob/master/active/002-py3-only.md) implementation step 8.

**Comment by jairideout** [comment]
This is not easy to do with our current CI setup. If we were using travis-ci's Python versions, we'd get the latest nightly build for free. Since we're using conda, I haven't been able to find a latest/nightly/dev version of Python.

One way to hack this would be to use travis-ci's Python versions to obtain nightly Python, then somehow trick conda into using that version of Python so that we can install dependencies the same way across Python versions. It [might be possible](http://stackoverflow.com/questions/29872316/allow-use-of-system-python-in-conda-env) but would be a terrible, fragile hack. I'd rather push this one off 0.5.0 milestone and resolve at a later time. Ideally there'd be a conda channel with builds of the latest dev version of Python 3. Does anyone know of such channel?

**Comment by wasade** [comment]
Given our dependency stack, I think we should test against released versions of Python
