### ISSUE TITLE
More Debian build failures

### ISSUE THREAD

**Issue by kdmurray91** [biocore/scikit-bio#1319]
This is for version 0.4.2 on i386. The package builds fine, however tests segfault. Is this a known issue (I can't see any GH issues that match)?

The build daemon log is [here](https://buildd.debian.org/status/fetch.php?pkg=python-skbio&arch=i386&ver=0.4.2-1&stamp=1458222699).

Cheers,
Kevin

**Comment by ebolyen** [comment]
My first guess is probably SSW. We had a similar issue with i686 in #409 which was theoretically solved with #761, but not really. Can you run the tests in verbose mode to verify?

If it is SSW (90% sure it is) then I'm not even sure if it's worth fixing, that time would be better invested in replacing it entirely, it's currently blocking Windows support as is.

**Comment by kdmurray91** [comment]
That's my assumption too. It's annoyingly difficult to accurately reproduce these builds locally, short of changing and re-uploading the package. I'm happy to assume that this is SSW, and await a fix in the form of removing libssw.

On that topic, has a replacement C implementation been found?

**Comment by jairideout** [comment]
We haven't found a replacement yet, @anderspitman will be starting to work on that soon though.
