### ISSUE TITLE
CCA issues

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#1322]
There are actually three problems going on

1. The environmental labels are being dropped.  [Here](https://github.com/biocore/scikit-bio/blob/master/skbio/stats/ordination/_canonical_correspondence_analysis.py#L224), you can see that no column or row labels are being passed into biplot_scores
2. The column rows don't actually match up with what is given in vegan.  In the example from [SO](http://stackoverflow.com/questions/36208741/how-can-i-make-a-cca-triplot-using-scikit-bio-python), there are only 3 columns (i.e. 3 dimension). This probably should be consistent with the PC ids.  
3. Its also becoming apparent that there is a sore need for biplots.  CA, RDA and CCA are essentially unusable without this functionality present in scikit-bio.  Its not trivial to tune these plots by hand.

**Comment by jairideout** [comment]
@mortonjt are you available to work on these bugs (items 1 and 2) for 0.5.0? We're shooting for June 7 to cut the release.

**Comment by mortonjt** [comment]
The main reason why I haven't pushed a PR for this is because I'm still not
on the same page exactly is going on with the `biplot_scores`.  If @Jorge-C
is still available, I think it would be best if he could take a look.

**Comment by jairideout** [comment]
I don't think @Jorge-C is available. Is there anyone else that can maintain the CCA code in scikit-bio?

**Comment by mortonjt** [comment]
Alright. Let me take another look at it

**Comment by jairideout** [comment]
Thanks!

**Comment by mortonjt** [comment]
I think I figured out the index/column headers for `rda` - `index=env_ids` and `columns=pc_ids`.
The same is the same for `cca`, but for some reason, some of the rows (i.e environmental variables) are being excluded.  No idea why ...

**Comment by mortonjt** [comment]
OK. I found the bloody bug.

Turns out to be in the [unittest](https://github.com/biocore/scikit-bio/blob/master/skbio/stats/ordination/tests/test_canonical_correspondence_analysis.py#L73)

We are ignoring the last column, which is why debugging this was really confusing.

**Comment by jairideout** [comment]
Fixed in #1368, thanks @mortonjt!
