### ISSUE TITLE
Different results scikit-bio and ecodist for mantel test

### ISSUE THREAD

**Issue by jwdebelius** [biocore/scikit-bio#1338]
I was running a mantel test in scikit-bio 0.4.2 and R's ecodist 1.2.9. 

In R, I coded my binary data to two vectors, and then converted it to a binary distance matrix, `pred`, and loaded my UniFrac distance matrix, `uwu`.
```R
> mantel(uww ~ case_ctrl, nperm=9999)

mantelr
0.0116570037310772
pval1
0.131131131131131
pval2
0.86986986986987
pval3
0.251251251251251
llim.2.5%
0.00271175063811381
ulim.97.5%
0.0211857644949996
```
I ran the same thing in scikit-bio, using the same two distance matrices.
```Python
>>> skbio.stats.distance.mantel(case_control_dm, unweighted, method='spearman')
(0.030750695058043068, 0.01, 322)
```

**Comment by jairideout** [comment]
Can you please post some example data that reproduces the issue?

**Comment by jairideout** [comment]
It looks like you're running a Pearson Mantel test in R and a Spearman Mantel test in scikit-bio. Can you try comparing results using the same correlation coefficient?

**Comment by jairideout** [comment]
@jwdebelius, can you confirm there is a discrepancy between scikit-bio and ecodist? We're having a release on June 7 so would be good to know if this is a bug or if the issue can be closed.

**Comment by jwdebelius** [comment]
@jairideout: I will update you by tomorrow. I remember running with pearson R and still seeing the discrepancy, but I will track down and let you know. Sorry for the delay.

**Comment by jwdebelius** [comment]
I can't reproduce the error. So, I must have done something wrong that day.

**Comment by jairideout** [comment]
Thanks for verifying!
