### ISSUE TITLE
Depsy 

### ISSUE THREAD

**Issue by wasade** [biocore/scikit-bio#1339]
Because we should have more tags. And to also better track utilization and statistics. Came across [Depsy](http://depsy.org/) as [matplotlib (depsy link)](http://depsy.org/package/python/matplotlib) is tied into it. The project itself is NSF [funded](http://blog.impactstory.org/impactstory-awarded-300k-nsf-grant/), so may be of broader @biocore interest. 

I'm filing this under CI but not sure if that is the most appropriate.

**Comment by josenavas** [comment]
You can actually already access to the scikit-bio link:
http://depsy.org/package/python/scikit-bio

**Comment by wasade** [comment]
Nifty...

**Comment by jairideout** [comment]
This looks really cool, nice find! Somehow @gregcaporaso is showing up as the only scikit-bio contributor, not sure where they're getting those stats from.

I'll tag this as a quick fix in case anyone's interested in adding the badge to scikit-bio's README.
