### ISSUE TITLE
target_end_optimal in StripedSmithWaterman alignment is off by one

### ISSUE THREAD

**Issue by haraball** [biocore/scikit-bio#1340]
When I do a protein sequence alignment using StripedSmithWaterman the resulting `target_end_optimal` is off by one. 

Code to reproduce:
```
from skbio.alignment import StripedSmithWaterman
from blosum import blosum62

query = StripedSmithWaterman("GLLVCAFWI", protein=True, substitution_matrix=blosum62)
target_sequence = "MTAPWRRLRSLVWEYWAGLLVCAFWIPDSRGMPHVIRIGGIFEYADGPNAQVMNAEEHAF"

al = query(target)

# Result:
{
    'optimal_alignment_score': 52,
    'suboptimal_alignment_score': 31,
    'query_begin': 0,
    'query_end': 8,
    'target_begin': 17,
    'target_end_optimal': 25,
    'target_end_suboptimal': 41,
    'cigar': '9M',
    'query_sequence': 'GLLVCAFWI',
    'target_sequence': 'MTAPWRRLRSLVWEYWAGLLVCAFWIPDSRGMPHVIRIGGIFEYADGPNAQVMNAEEHAF'
}
```
The Blosum62 matrix I'm using can be found in [this gist](https://gist.github.com/haraball/d061b85e62063d5f1daa94387a4f9491)

```
al.target_sequence[al.target_begin:al.target_end_optimal]  # 'GLLVCAFW'
len(GLLVCAFW)  # 8
```

The `al.cigar` indicates that the length of the alignment should be 9, the `optimal_alignment_score` is correct when adding up the 9 alignments according to the Blosum62 matrix. 

Is this a bug or is it something I don't understand correctly here?

**Comment by haraball** [comment]
Ok, I might have have misunderstood the result. When using the indices provided from `target_begin` and `target_end_optimal` in a python slice of the `target_sequence` as I've done above, it will be one position off. If I pad the `target_end_optimal` with 1 it returns the full matching string. 

From what I can find in the code, the result is [zero-indexed](https://github.com/biocore/scikit-bio/blob/138a3b678942acc5965c160dd29769ee07a69189/skbio/alignment/_ssw_wrapper.pyx#L184). Would it be more helpful to have either `+1` added to `target_end_optimal`, or having a variable `target_length_optimal` with the length of the sequence so one could use `[target_begin:target_begin+target_length_optimal] to slice out the full matching string?

**Comment by ebolyen** [comment]
Hey @haraball, you are actually using the "low-level" API to SSW. The result of running `query` against the target results in a very very light wrapper around the struct produced by [SSW](https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library), so it's indexing scheme doesn't feel particularly obligated to match python's `[start, end)` rules for ranges. 

In terms of a slightly nicer way of dealing with this code, check out [local_pairwise_align_ssw](http://scikit-bio.org/docs/0.4.2/generated/skbio.alignment.local_pairwise_align_ssw.html#skbio.alignment.local_pairwise_align_ssw) which returns more pythonic objects. 

We are currently trying to replace this module entirely as it is blocking Windows support, so it is unlikely that we will update the way the result struct works.

**Comment by haraball** [comment]
Thanks for the clarification and the suggestion, @ebolyen!
