### ISSUE TITLE
ancom returns false positives in small tables

### ISSUE THREAD

**Issue by antgonza** [biocore/scikit-bio#1376]
When you are dealing with small tables, 10-20 features, it's possible to get a W of 0 and True in the reject  column (significant features with a W of 0). This is expected based on how the algorithm works so it should raise a warning/error on this cases.

**Comment by mortonjt** [comment]
:+1:  We probably should raise a warning if a table with <20 features is
used.

**Comment by gregcaporaso** [comment]
I agree that this would be useful. Where does the number 20 come from? Do the developers of ANCOM recommend that?

**Comment by mortonjt** [comment]
That was just based on looking at Antonio's table. I'm not sure exactly
what would be a good threshold.

**Comment by jairideout** [comment]
Putting this on 0.5.0 milestone, it'll be important to figure out the minimum number of samples and features required by the method, and probably raise an error if the input is smaller than that (unless there's a good reason to only warn).

**Comment by gregcaporaso** [comment]
I'm going to review the paper to see if there is a recommendation on this. I'm not comfortable setting any kind of threshold (on minimum number of samples or features) unless we can back it up though.

**Comment by gregcaporaso** [comment]
I don't see any recommendation about this in the supplement or the main text of the paper. @wdwvt1, do you happen to know if there are recommendations for minimum number of features or samples that should be used with ANCOM? If not, should we ask the first/last authors what they think?

**Comment by mortonjt** [comment]
Reopen if this hasn't been addressed
