### ISSUE TITLE
`ImportError: No module named 'skbio.math'`

### ISSUE THREAD

**Issue by jolespin** [biocore/scikit-bio#1401]
Trying to import:
`skbio.math.stats.ordination.PCoA` 

so I did:
 `from skbio.math.stats.ordination import PCoA` 

but got:
 `ImportError: No module named 'skbio.math'`

**Comment by ebolyen** [comment]
Wow, that is a very old import, what version are you currently running?

The new path should be `from skbio.stats.ordination import pcoa`.

**Comment by jolespin** [comment]
Oh duh lol!  Sorry I didn't catch that.  Yea I just saw what doc I was looking at http://scikit-bio.org/docs/0.1.1/generated/skbio.math.stats.ordination.PCoA.html.  Thanks for the help. btw, when you google `https://www.google.com/?ion=1&espv=2#q=python%20principal%20coordinate%20analysis` the old docs come up before everything.

**Comment by jolespin** [comment]
Quick question, does `PCoA` essentially follow the same steps as `PCA` but w/ a distance matrix instead of a standardized/centered covariance matrix (or correlation)?  If you could point this to anyone who could help that would be really useful http://stats.stackexchange.com/questions/222664/how-does-principal-coordinate-analysis-pcoa-work-as-compared-to-pca

**Comment by gregcaporaso** [comment]
@jolespin, see [here](http://ordination.okstate.edu/glossary.htm#PCoA). That website is the best resource I know of for ordination.
