### ISSUE TITLE
pip install on OS X failing

### ISSUE THREAD

**Issue by ivirshup** [biocore/scikit-bio#1407]
Hi,

I'm running into some trouble installing `scikit-bio`, similar to #981.

When I run `$ pip3 install scikit-bio` I get a lot of output, the main part being building the wheel fails and then building from source fails, both ending with the following error:

```
   building 'skbio.stats.__subsample' extension
    creating build/temp.macosx-10.11-x86_64-3.5
    creating build/temp.macosx-10.11-x86_64-3.5/skbio
    creating build/temp.macosx-10.11-x86_64-3.5/skbio/stats
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c skbio/stats/__subsample.c -o build/temp.macosx-10.11-x86_64-3.5/skbio/stats/__subsample.o
    skbio/stats/__subsample.c:250:10: fatal error: 'numpy/arrayobject.h' file not found
    #include "numpy/arrayobject.h"
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
 ```

I'm running python 3.5, numpy 1.11.1,  and osx 10.11.6.

Thanks for any suggestions

**Comment by jairideout** [comment]
@ivirshup do you have the Apple developer tools installed and up-to-date (e.g. Xcode)?

**Comment by ivirshup** [comment]
I do

**Comment by ebolyen** [comment]
@ivirshup I think @bsmith89 was able to find the potential source of the issue, would you be open to testing out both the current `master` and #1408 to see if that resolves your problem? If it fixes it we should see `master` fail and #1408 succeed. 

If your not available that's fine as well, we'll see what we can do to reproduce.

**Comment by ebolyen** [comment]
@ivirshup Are you using Miniconda (Anaconda/Conda) or are you running this on your system-installed Python 3?

**Comment by ebolyen** [comment]
@thermokarst was able to reproduce locally, thanks for reporting @ivirshup!

**Comment by ebolyen** [comment]
In the meanwhile (until our next release), you should be able to use [Miniconda](http://conda.pydata.org/miniconda.html) which I would highly recommend generally.

**Comment by jairideout** [comment]
Installation with `pip` is now fixed for OS X El Capitan in master, thanks @ivirshup for reporting and thanks @bsmith89 for fixing!
