### ISSUE TITLE
ILR calculation from Gram-Schmidt - algorithm

### ISSUE THREAD

**Issue by edesz** [biocore/scikit-bio#1415]
I was going through the list of methods available in the `skbio.stats.composition` [module](http://scikit-bio.org/docs/0.4.2/generated/skbio.stats.composition.html#module-skbio.stats.composition). I am mainly interested in the `ilr` method and specifically in calculating a basis to be used in this method.

Using the Gram-Schmidt approach from [here](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process) , the basis `e` can be calculated based on an input NumPy array. In the scikit-bio `ilr` (or `ilr_inv`) [methods](https://github.com/biocore/scikit-bio/blob/master/skbio/stats/composition.py), I noticed scikit-bio only the dimension of the NumPy input array rather than the whole array itself in your calculation of the Gram-Schmidt basis.

It seems like this might be different that the traditional Gram-Schmidt approach (eg. see here - [1](http://www.rkinteractive.com/blogs/SoftwareDevelopment/file.axd?file=2014%2f3%2fGramSchmidt.py) or [2](https://github.com/whille/mylab/blob/master/algrithm/gram_schmidt.py)) for deriving a basis using the input data (2D NumPy array). Do you happen to have a literature reference for how scikit-bio calculates the basis for the `ilr` or `ilr_inv` methods from the `stats.composition` module? Is this a custom implementation of the Gram Schmidt process?

**Comment by anderspitman** [comment]
Link to the docs as well: http://scikit-bio.org/docs/0.5.0/generated/generated/skbio.stats.composition.ilr.html#skbio.stats.composition.ilr

**Comment by edesz** [comment]
Many thanks. Is there a reference for how the J. J. Egozcue orthonormal basis can be derived starting from the Gram-Scmidt orthogonalization? i.e. theory or an example?

**Comment by mortonjt** [comment]
Hi @edesz , the original paper detailing the ilr transform can be found [here](http://link.springer.com/article/10.1023/A:1023818214614). Not going to be lie, it is a pretty dense read.

But here's a more intuitive way to understand the calculation.  All orthonormal bases in the simplex, can be represented by a tree, including the Gram-Schmidt orthogonalization.  In fact, it can be represented as the following tree

```
>>> from skbio import TreeNode
>>> t = u"(((x1,x2)y3,x3)y2, x4)y1;"
>>> tree = TreeNode.read([tree])
>>> print(tree.ascii_art())
                              /-x1
                    /y3------|
          /y2------|          \-x2
         |         |
-y1------|          \-x3
         |
          \-x4
```

The balancing elements can be calculated for the internal nodes of the tree using the following equation

<img width="361" alt="screen shot 2016-08-20 at 10 47 15 am" src="https://cloud.githubusercontent.com/assets/4184797/17832889/8042c02e-66c3-11e6-9985-237e6537c008.png">

So for this particular tree, if I wanted to calculate y3, it would be
```
k = 2   # there are 2 tips, c, d that are below the y3 subtree
r = 1   # there is 1 tip, b
s = 1   # there is 1 tips, a
t  = 0  # there are no tips above the y3 subtree
a = np.sqrt(s / (r*(r+s))
b = np.sqrt(r / (s*(r+s))
```
And the rest of the balancing elements, y1 and y2 can be calculated the same way.
See this [paper](http://link.springer.com/article/10.1007/s11004-005-7381-9) for more information about this procedure.

To actually test this yourself, you can look at the [_balance_basis](https://github.com/biocore/gneiss/blob/master/gneiss/balances.py#L18) functionality in [gneiss](https://github.com/biocore/gneiss).  
```
>>> from gneiss.balance_basis import _balance_basis
>>> basis, nodes = _balance_basis(t)
>>> basis
array([[-0.28867513, -0.28867513, -0.28867513,  0.8660254 ],
       [-0.40824829, -0.40824829,  0.81649658,  0.        ],
       [-0.70710678,  0.70710678,  0.        ,  0.        ]]
```  
If you compare this to the gram_schmidt orthogonalization procedure, it generates reflection of the above basis (its different by a negative sign).
```
>>> from skbio.stats.composition import _gram_schmidt_basis
>>> _gram_schmidt_basis(4)
array([[-0.70710678,  0.70710678, -0.        , -0.        ],
       [-0.40824829, -0.40824829,  0.81649658, -0.        ],
       [-0.28867513, -0.28867513, -0.28867513,  0.8660254 ]]
```

Hope this helps!

**Comment by edesz** [comment]
Ah, thanks! Those last 2 examples are great! This answers my questions about the orthogonalization process.
