### ISSUE TITLE
Unexpected result when parsing fasta into DNA

### ISSUE THREAD

**Issue by wasade** [biocore/scikit-bio#1418]
This results in the first record of the fasta file being split into individual nucleotide records all with the same sequence ID:

```python
In [1]: import skbio

In [2]: !cat foo.fasta
>a b c
ATA
>x y z
GCG

In [3]: list(skbio.read('foo.fasta', into=skbio.DNA))
Out[3]:
[DNA
 --------------------------
 Metadata:
     'description': 'b c'
     'id': 'a'
 Stats:
     length: 1
     has gaps: False
     has degenerates: False
     has definites: True
     GC-content: 0.00%
 --------------------------
 0 A, DNA
 --------------------------
 Metadata:
     'description': 'b c'
     'id': 'a'
 Stats:
     length: 1
     has gaps: False
     has degenerates: False
     has definites: True
     GC-content: 0.00%
 --------------------------
 0 T, DNA
 --------------------------
 Metadata:
     'description': 'b c'
     'id': 'a'
 Stats:
     length: 1
     has gaps: False
     has degenerates: False
     has definites: True
     GC-content: 0.00%
 --------------------------
 0 A]
```

**Comment by jairideout** [comment]
@wasade you're telling scikit-bio to read the first record of your FASTA file into an `skbio.DNA` object (that's what `into=skbio.DNA` does). When you call `list` on your `skbio.DNA` object, you get an `skbio.DNA` object for each character in the sequence because that is how iterating over an `skbio.DNA` object works.

Here's how to get a generator yielding `skbio.DNA` sequences:

```python
import skbio
import skbio.io

seq_gen = skbio.io.read('foo.fasta', format='fasta', constructor=skbio.DNA)
for seq in seq_gen:
    # seq is an `skbio.DNA` object
```

**Comment by jairideout** [comment]
For more examples of I/O in scikit-bio, see [this cookbook recipe](http://nbviewer.jupyter.org/github/biocore/scikit-bio-cookbook/blob/master/Reading%20and%20writing%20files.ipynb).

**Comment by wasade** [comment]
I'd argue that my use is intuitive and the result is unexpected...

**Comment by jairideout** [comment]
I agree. The API changes proposed in https://github.com/biocore/scikit-bio/issues/1031 should make this much less confusing. I closed this issue because it is an API question and we have a supported solution (this is how the I/O registry is currently intended to work).

**Comment by wasade** [comment]
Okay, sounds good. Thanks!
