### ISSUE TITLE
Closure bug

### ISSUE THREAD

**Issue by jwdebelius** [biocore/scikit-bio#1420]
Closure throws an error with numpy 1.11.1 (latest version) with Python 3.

In this version, the sum of an array does not have a `keepdims` argument, but the np.sum function does.

**Comment by mortonjt** [comment]
Hmm.  I've been using numpy 1.11.1 and Python 3 for a while, and this works just fine on my machine.

Can you attach the exact commands you tried to run, along with your error message?

**Comment by jwdebelius** [comment]
I run the following on my biom 2.1 table, generated using QIIME 1.9:

```python
closure(otu_15k_f.matrix_data.todense() + 1)
```

The following error is raised

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-127-ffa9a2af4037> in <module>()
----> 1 closure(otu_15k_f.matrix_data.todense() + 1)

/Users/jdebelius/miniconda2/envs/smarr_fall2016/lib/python3.5/site-packages/skbio/stats/composition.py in closure(mat)
    151     if np.all(mat == 0, axis=1).sum() > 0:
    152         raise ValueError("Input matrix cannot have rows with all zeros")
--> 153     mat = mat / mat.sum(axis=1, keepdims=True)
    154     return mat.squeeze()
    155 

TypeError: sum() got an unexpected keyword argument 'keepdims'
```

I can generate another test matrix,

```
test = biom.Table(np.array([[0, 0, 1], [2, 1, 3], [0, 3, 0]]), 
                  observation_ids=['A', 'B', 'C'], 
                  sample_ids=[1, 2, 3])
closure(test.matrix_data.todense() + 1)

ypeError                                 Traceback (most recent call last)
<ipython-input-136-87a3d1195daa> in <module>()
----> 1 closure(test.matrix_data.todense() + 1)

/Users/jdebelius/miniconda2/envs/smarr_fall2016/lib/python3.5/site-packages/skbio/stats/composition.py in closure(mat)
    151     if np.all(mat == 0, axis=1).sum() > 0:
    152         raise ValueError("Input matrix cannot have rows with all zeros")
--> 153     mat = mat / mat.sum(axis=1, keepdims=True)
    154     return mat.squeeze()
    155 

TypeError: sum() got an unexpected keyword argument 'keepdims'
```

When I check my version of numpy in the notebook, I get numpy 1.11.1. I'm running Python 3 with the latest scikit-bio release pip installed into my enviroment.

**Comment by wasade** [comment]
Can you try "toarray()" instead of "todense()"? Former is np.array, latter
is np.matrix

**Comment by mortonjt** [comment]
Yeah, I think that's the problem - its expecting an array instead of a matrix.

**Comment by jairideout** [comment]
The ndarray/matrix distinction in numpy is so much fun...

**Comment by mortonjt** [comment]
I think it is ok not to support handling numpy matrix.  This is pretty much
a standard with scipy.  See this post on the difference between np.matrix
and np.array.  http://stackoverflow.com/a/4151251/1167475

**Comment by ebolyen** [comment]
I agree, matrix doesn't really need to exist in practice and I don't think
we want to encourage it's use anyhow.

**Comment by wasade** [comment]
@jwdebelius, can this be closed?

**Comment by jwdebelius** [comment]
Given that it's a single line change `m.sum()` vs `np.sum(m)`, I'd push for the change.

**Comment by wasade** [comment]
I disagree, having type specificity is nice and protects from additional downstream unknowns. `array` and `matrix` behave differently in a few ways.
