### ISSUE TITLE
Feature Request: Using DNA.find_with_regex and DNA.as_regex together

### ISSUE THREAD

**Issue by clintval** [biocore/scikit-bio#1431]
One thing I wish was possible is using `skbio.DNA.find_with_regex` and `skbio.sequence.GrammaredSequence.to_regex` together. This is most useful when considering DNA patterned with degenerate bases such as the pattern `RGYW`.

[to_regex() documentation](http://scikit-bio.org/docs/0.4.2/generated/skbio.sequence.GrammaredSequence.to_regex.html)
[find_with_regex() documentation](http://scikit-bio.org/docs/0.4.2/generated/skbio.sequence.Sequence.find_with_regex.html)

Example usage:

```python
from skbio import DNA

reference = DNA("GGTA")
motif = DNA("RGYW")

for match in reference.find_with_regex(motif.as_regex()):
     pass # One match result yield here
```

The issue is that `find_with_regex` looks for match groups which `as_regex` does not include. Would this be possible to implement?

**Comment by ebolyen** [comment]
Hey @clintval! 

First off, so sorry for the very late response! we've been absolutely swamped with QIIME 2 related efforts

I really like this suggestion. In principle these two APIs *should* be composable, however since `to_regex` compiles the expression, there is little that can really be done with it after the fact.

One thing to note is that these are stable APIs which means we need to think carefully about how we modify them. 

Pinging @gregcaporaso and @jairideout (they won't be able to respond until later next week)

**Comment by jairideout** [comment]
I agree this would be useful. To avoid breaking backward-compatibility, we could add a keyword argument to either `as_regex` or `find_with_regex` that produces the desired behavior (will defer to you guys on what method that should be added to)?

**Comment by clintval** [comment]
I recommend including a keyword argument `capture` (or something similar) which would accept `True` or `False` to `as_regex()`. This would simply return your regex with or without the capture group parenthesis.

Example:

    DNA('RGYW').as_regex()
    >> '[AG]G[CT][AT]'

    DNA('RGYW').as_regex(capture=True)
    >> '([AG]G[CT][AT])'

**Comment by ebolyen** [comment]
:+1: :+1: :+1:  for `capture=True`, would you be open to creating a PR @clintval?

**Comment by clintval** [comment]
Sure thing! Thanks

**Comment by jairideout** [comment]
I really like this, thanks @clintval!

**Comment by clintval** [comment]
If anyone here is interested, I rebased on upstream and would be eager to hear your opinion on the API change proposed here: https://github.com/biocore/scikit-bio/pull/1522.

That PR would enable the user to write the following expression:

```python
>>> from skbio import DNA

>>> query = DNA('RGYW')
>>> DNA('AGTA').find_with_regex(query.to_regex(within_capture=True))
[slice(0, 4, None)]
```

Without the PR, the expression will not return anything:

```python
>>> from skbio import DNA

>>> query = DNA('RGYW')
>>> DNA('AGTA').find_with_regex(query.to_regex())
[]
```

**Comment by ebolyen** [comment]
I love this! :heart:
