### ISSUE TITLE
Feature Request: Include reverse complement search in DNA.find_with_regex

### ISSUE THREAD

**Issue by clintval** [biocore/scikit-bio#1432]
It would be nice have a method that not only finds patterns on the `+` strand of the DNA but also the `-` strand. At the moment you could use `DNA.find_with_regex` on both strands separately and then join all of the slice objects together but the difficulty in this approach is that slice objects are not hashable so you will have some duplicate objects when a pattern matches both the `+` and `-` in the same genomic interval.

Example:

    import skbio
    
    for match in skbio.DNA("GATT").find_with_regex("TC", reverse=True):
        pass # Yield one slice object here (found on the reverse complement)

The above example uses a boolean parameter that would allow the user to scan both strands at once. The method would then slide across the reference sequence and yield a slice object if either the sequence or the reverse complement of the sequence were a match. Hope this makes sense! First time using the scikit-bio library! I would be willing to make these changes if a consensus deemed them useful.

**Comment by ebolyen** [comment]
I'm definitely open to this idea, but how would you determine which strand the slice was matching? If you were to slice the sequence with the results, e.g. `seq[seq.find_with_regex("TC", reverse=True)]` what would you get?

**Comment by wasade** [comment]
Does there exist a reverse complement for all allowed regex in this method,
and if so, is it a one-one mapping in all cases (or does it need to be...)?

**Comment by clintval** [comment]
There should be a complement and likewise a reverse complement to any valid regex this method produces, although I have not checked coverage over every degenerate base. The degenerate base set is guaranteed to have complements if it follows IUPAC convention:

http://www.boekhoff.info/?pid=data&dat=fasta-codes

@ebolyen I imagine you would lose your stranded information since slice objects are intuitively left-to-right slices and therefore only have `+` polarity.

For example I can imagine this being a valid behavior:

    >>> for match in DNA("GATT").find_with_regex("TC", reverse=True):
    ...    match
    slice(0, 1, None)

One way to preserve stranded information is to return which strand the match was found on by yielding a slice object plus a Boolean or string representing the polarity:

    >>> for match in DNA("GATT").find_with_regex("TC", reverse=True):
    ...    match
    (slice(0, 2, None), '-')
    - OR -
    (slice(0, 2, None), 1)

This gets contrived, however, for palindromic matches when a pattern matches both the positive and negative strand.

    >>> for match in DNA("ACGT").find_with_regex("CG", reverse=True):
    ...    match
    [(slice(1, 3, None), '+'), (slice(1, 3, None), '-')]

I can think of uses for this functionality such as simply finding motifs on both strands and searching for palindromic sequences, all of which are common routines in working with nucleic acids. What do you all think? Would this method addition be too complicated or hard to understand from a user's perspective?

**Comment by ebolyen** [comment]
Thanks for expanding @clintval! 
I'm probably leaning towards this being "too much" for `find_with_regex` to deal with, especially considering the following composition would do roughly the same thing: 
```python
itertools.chain(seq.find_with_regex("TC"), seq.reverse_complement().find_with_regex("TC"))
```

Keeping them as separate calls also keeps the return type simple and allows you to handle either strand as needed. Indeed a sequence object doesn't really know which strand it is, so that is already up to the user to keep track of. It seems simpler to have a single way to handle the reverse strand and composing instead of baking that knowledge into every applicable method.

**Comment by clintval** [comment]
Sounds good! I'll close this out! Thanks for humoring me!

**Comment by ebolyen** [comment]
Thanks for the nice proposal @clintval!
