### ISSUE TITLE
CI appears broken

### ISSUE THREAD

**Issue by wasade** [biocore/scikit-bio#1435]
Two separate PRs, test output [here](https://travis-ci.org/biocore/scikit-bio/jobs/165854392) and [here](https://travis-ci.org/biocore/scikit-bio/builds/165854390), impact is on both traces through build matrix. Failure appears to stem from repeated exceptions along the lines of:

```python
======================================================================
ERROR: test_custom_valid_multi_line (skbio.io.format.tests.test_blast6.TestBlast6Reader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/env_name/lib/python3.5/site-packages/skbio/io/format/tests/test_blast6.py", line 57, in test_custom_valid_multi_line
    'sallacc', 'qaccver'])
  File "/home/travis/miniconda3/envs/env_name/lib/python3.5/site-packages/skbio/io/registry.py", line 998, in wrapped_reader
    return reader_function(fhs[-1], **kwargs)
  File "/home/travis/miniconda3/envs/env_name/lib/python3.5/site-packages/skbio/io/format/blast6.py", line 272, in _blast6_to_data_frame
    "Specified number of columns (%r) does not equal"
  File "/home/travis/miniconda3/envs/env_name/lib/python3.5/site-packages/skbio/io/format/_blast.py", line 40, in _parse_blast_data
    fh.seek(0)
ValueError: I/O operation on closed file.
```

I've marked this as blocking as it blocks review on pull requests.

tagging #1352 and #1430

**Comment by ebolyen** [comment]
From just looking at that real quick, it looks like the python version might be getting mixed up... Travis caches the `.travis.yml` in weird ways sometimes...

**Comment by jairideout** [comment]
Weird, it's using python 3.5

**Comment by ebolyen** [comment]
But when it print `python --version` I see 2.7

**Comment by ebolyen** [comment]
Oh nevermind, that is pre-conda

**Comment by wasade** [comment]
I'm able to recreate the issue independently. It appears that `wrapped_reader` is returning from within a file open context. Doing so similarly and independently results in a closed file and the same exception:

```python
09:22:43 (mcdonadt@Daniels-MacBook-Pro-2):~> with open('stuff.txt', 'w') as fp:
   ...:    fp.write('asdasdasdasd')
   ...:

09:22:48 (mcdonadt@Daniels-MacBook-Pro-2):~> def foo():
   ...:     with open('stuff.txt', 'r') as fp:
   ...:         return fp
   ...:

09:22:59 (mcdonadt@Daniels-MacBook-Pro-2):~> bar = foo()

09:23:04 (mcdonadt@Daniels-MacBook-Pro-2):~> bar.seek(0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-b09908afe439> in <module>()
----> 1 bar.seek(0)

ValueError: I/O operation on closed file.
```

**Comment by wasade** [comment]
oddly, `nosetests` passes locally despite the ability to recreate a similar traceback using similar code independent of skbio.

**Comment by ebolyen** [comment]
Usually these things happen because of a version bump in one of our dependencies, that might be related.

**Comment by ebolyen** [comment]
I'll be looking into this issue this week.

**Comment by wasade** [comment]
Thanks!

**Comment by ebolyen** [comment]
I'm able to reproduce with latest dependencies. I suspect natsort is to blame.

**Comment by ebolyen** [comment]
Turns out `pd.read_csv` closes a filehandle passed to it now. How thoughtful!

**Comment by ElDeveloper** [comment]
... I mean, it makes sense.
