### ISSUE TITLE
Master broken on Linux (strange)

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1448]
Master is currently broken after merging both #1440 and #1445. Based on #1447 and #1446 it appears that either of these PRs in isolation work fine. So there is something *really* strange happening.

We are able to reproduce this runtime split locally in a couple of linux (which fail) and mac (which succeed) environments.

**Comment by RNAer** [comment]
@wasade and @mortonjt , you guys have any idea?

**Comment by mortonjt** [comment]
Taking a look now!

**Comment by ebolyen** [comment]
Fixed by #1449
