### ISSUE TITLE
execute doctests defined in .pyx files

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1458]
doctests defined in .pyx files currently are not executed by Travis-CI builds or PyPI source installs. I can only get them to execute after building a conda package and running the tests.

Currently there are only two doctests in .pyx files (both defined in `skbio/metadata/_intersection.pyx`). Both are failing; installing the 0.5.1 release via conda and executing the tests will reproduce the failures. See https://github.com/biocore/scikit-bio/pull/1457 for a workaround that removes the broken tests until this issue is solved generally.

**Comment by ebolyen** [comment]
Loosely following the conversation, an alternative approach would be to strip the doctests of their `>` making them un-executable. That way they persist for *dev* documentation purposes, but we don't make any guarantees on them as user-facing docs. Not ideal, but a potential compromise.
