### ISSUE TITLE
private vs. package-private vs. public API

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1466]
scikit-bio has a notion of private vs. package-private vs. public APIs. A draft describing these APIs can be found [here](https://github.com/jairideout/scikit-bio/blob/e10afe2c7e1cb0127d90d7e6cf72b3ac7cb58b4d/REVIEWING.md#public-vs-private-api).

@RNAer suggested dropping the idea of a package-private API so that it is easy to see whether an API is private by simply looking at the API name -- if it starts with an underscore, it is private, otherwise it is public. The current scheme requires devs to look at the API's *import path* to determine whether the API is private, package-private, or public.

I would like to keep the distinction between private and package-private API because they exist for different purposes. A truly *private* API is only to be used within the *module* it is defined in, and a *package-private* API can be used anywhere within the project (e.g. promoting code reuse). Without this distinction, it isn't possible for a scikit-bio dev to know whether a private API can be reused in the codebase or if it is intended only for use within a module (e.g. functions with a specific purpose that are not intended for general use).

If the notion of package-private API is removed, this will require a massive amount of changes to the codebase. Let's start initial discussion here and move to an RFC if necessary.

cc: @ebolyen

**Comment by RNAer** [comment]
I feel like the distinction between truly private and package-private API is not that useful, because the concept of truly private API is not neccessary - it is difficult to predict a function is useful only in current module or in other modules at the time of implementation. Howerver, this dinstinction adds burden on manually checking the imports if an API is private or public.

Regarding to current code, I don't think we need to change it because no public APIs are impacted. We can leave it there and phase it out gradually.

This is my personal opinion, but I don't think it is critical for now.

**Comment by jairideout** [comment]
> Regarding to current code, I don't think we need to change it because no public APIs are impacted. We can leave it there and phase it out gradually.

We'd need to change the code because package-private APIs have names that don't start with an underscore. This API would technically become public based on its naming scheme, so all package-private APIs would need to be renamed to start with an underscore. This seems like a lot of work without clear gains.

**Comment by ebolyen** [comment]
@jairideout wouldn't private modules still be private?

**Comment by jairideout** [comment]
They would still be private in the sense that they are defined in private modules. But from @RNAer's comment above, and discussion on a call, he wants to remove package-private API so that an API can be identified as public or private based purely on its *name*,  and not its *import path*. Given this, we wouldn't want a mix of old package-private APIs and public APIs, because a developer won't know whether the API is public or an old package-private API *based on the API name alone*. It is true that the dev could look at its *import path*, but then we've defeated the purpose of removing package-private API in the first place.

I think if this change is going to happen, all package-private APIs will need to be renamed to have a leading underscore.

**Comment by gregcaporaso** [comment]
I don't think we should make this change now. As @jairideout notes, it'll be a big change, and there are not clear gains. (It's not user-facing at all, and developers can differentiate private, package-private, and public easily enough. And, that distinction has been useful in the project to-date, so it doesn't seem like something we should just scrap.) If we devote the same effort to new functionality, we could have some nice, new user facing features.

**Comment by jairideout** [comment]
I'm closing this issue since it doesn't seem like a change that we want to make. If anyone disagrees with this, please comment/reopen.
