### ISSUE TITLE
GSOC 2017: NumFOCUS will be an umbrella organization

### ISSUE THREAD

**Issue by kain88-de** [biocore/scikit-bio#1475]
Hi

Organizations can start submitting applications for Google Summer of Code
2017 on January 19 (and the deadline is February 9)

https://developers.google.com/open-source/gsoc/timeline?hl=en

NumFOCUS will be applying again this year. If you want to work with us
please let me know and if you apply as an organization yourself or under a
different umbrella organization please tell me as well. If you participate
with us it would be great if you start to add possible projects to the
ideas page on github soon. We some general information for mentors on
github.

https://github.com/numfocus/gsoc/blob/master/CONTRIBUTING-mentors.md

We also have a template for ideas that might help. It lists the things
Google likes to see.

https://github.com/numfocus/gsoc/blob/master/2017/ideas-list-skeleton.md

In case you participated in earlier years with NumFOCUS there are some
small changes this year. Raniere won't be the admin this year. Instead I'm
going to be the admin. We are also planning to include two explicit rules
when a student should be failed, they have to communicate regularly and
commit code into your development branch at the end of the summer.

best, Max

I hope it is OK to bring this up as an issue, I haven't found information for an email list.

**Comment by gregcaporaso** [comment]
@kain88-de, we discussed and are not going to submit a proposal this year. Thanks for getting in touch about it, and good luck!
