### ISSUE TITLE
bug: make test fails with a status code != 0

### ISSUE THREAD

**Issue by bunop** [biocore/scikit-bio#1481]
Dear all,

I've set up a developing environment as described [here](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md#setting-up-a-development-environment), but when doing the `make test` phase, I obtain an error message like this:
```
----------------------------------------------------------------------
Ran 2502 tests in 49.091s

OK
flake8 skbio setup.py checklist.py
./checklist.py
./checklist.py:215: ChecklistWarning: File skbio/metadata/tests/test_intersection.py has IGNORE directive. Ignoring scikit-bio copyright header validation.
  ChecklistWarning)
The following tests import `A` but should import `B` (file: A => B):
    skbio/alignment/tests/test_pairwise.py: skbio.util._decorator.classproperty => skbio.util.classproperty
    skbio/alignment/tests/test_tabular_msa.py: skbio.util._decorator.classproperty => skbio.util.classproperty
    skbio/alignment/tests/test_tabular_msa.py: skbio.util._testing.assert_data_frame_almost_equal => skbio.util.assert_data_frame_almost_equal
    skbio/io/format/tests/test_fastq.py: skbio.sequence._grammared_sequence.GrammaredSequence => skbio.sequence.GrammaredSequence
    skbio/io/format/tests/test_fastq.py: skbio.util._decorator.classproperty => skbio.util.classproperty
    skbio/io/format/tests/test_clustal.py: skbio.sequence._grammared_sequence.GrammaredSequence => skbio.sequence.GrammaredSequence
    skbio/io/format/tests/test_clustal.py: skbio.util._decorator.classproperty => skbio.util.classproperty
    skbio/io/format/tests/test_fasta.py: skbio.sequence._grammared_sequence.GrammaredSequence => skbio.sequence.GrammaredSequence
    skbio/io/format/tests/test_fasta.py: skbio.util._decorator.classproperty => skbio.util.classproperty

Makefile:23: set di istruzioni per l'obiettivo "test" non riuscito
make: *** [test] Errore 1
```
The error is thrown by `./checklist.py`, which raises this warnings but returns a `1` status code and test fails. I noticed that classes like `skbio.util._decorator.classproperty` are imported from the main module `skbio.util` so I've fixed imports to have a `0` status from `./checklist.py`. I will try to submit those fixes with a pull request. Maybe this problems is related in a different version of a module required by your test. [Here](https://gist.github.com/bunop/8e279640417c5cd1a5fb1759b6f4201c) are details of my conda environment.

Regards,

Paolo

**Comment by jairideout** [comment]
These specific imports were fixed in #1482 (thanks @bunop!). #769 tracks this checklist.py issue (it's come up in the past), so I'll close this issue to prevent duplicates.
