### ISSUE TITLE
bug: make test fails in travis ci (python 3.6?)

### ISSUE THREAD

**Issue by bunop** [biocore/scikit-bio#1497]
Dear all,

I found that my PR #1495 fail to pass the `travis CI` test for a problem related to the conda environment. Briefly, by inspecting the travis output I noticed that modules were tested on a python `3.6` environment, even if `3.5` version is specified in configuration. The commands to repruduce error locally are the following:
```bash
$ conda create -n travis python=3.6
$ source activate travis
$ conda install --file ci/conda_requirements.txt
$ pip install -r ci/pip_requirements.txt
$ pip install . --no-deps
$ WITH_COVERAGE=TRUE make test
```
This will raise the same errors raised by `Travis CI`. By inspecting code, I found that the problem arises from `skbio.stats.power`, at line [1076](https://github.com/biocore/scikit-bio/blob/master/skbio/stats/power.py#L1076): The order of items of `collections.Counter(set_pos)` is different from python `3.5` to `3.6`. Here is a sample code to reproduce the error:
```python
import collections
set_pos = [2,0,3,1,3,2,2,0,4,3,2,1,5,0,0,3,0,3,3,1,1]
collections.Counter(set_pos).items()
# in python 3.5
# dict_items([(0, 5), (1, 4), (2, 4), (3, 6), (4, 1), (5, 1)])
# in python 3.6
# dict_items([(2, 4), (0, 5), (3, 6), (1, 4), (4, 1), (5, 1)])
```
I think i've fixed the issue in python code, I will open a new PR. Another solution could be fixing `.travis.yml` to force python `3.5` installation, however make test will fail in `3.6` enviroment.
Thank you for your support,
regards,
Paolo

**Comment by wasade** [comment]
Thanks, @bunop! I think this has to do with Python3.6's `OrderedDict`. Good find!

**Comment by wasade** [comment]
And thank you also for the reproducible examples

**Comment by ElDeveloper** [comment]
Just tried installing the latest release in python 3.6 and saw a bunch of failures when I ran the test suite, also note that the [current build is failing](https://travis-ci.org/biocore/scikit-bio).
