### ISSUE TITLE
Tips not returned for tips

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#1509]
When the following code is run

```python
>>> from skbio import TreeNode
>>> tree = TreeNode.read(['(c, (b,a)x)y;'])
>>> list(tree.children[0].tips(include_self=True))
[]
```
No tips are returned, even when `include_self=True`.

When is actually happening is that the information from `include_self` is not based passed into the underlying postorder traversal function.

**Comment by nreeve17** [comment]
It looks like this issue was fixed in #1508
