### ISSUE TITLE
qiime-generated phylogenetic trees and unifrac

### ISSUE THREAD

**Issue by grayfall** [biocore/scikit-bio#1517]
I've got problems with UniFrac implementations in `diversity.beta` and the tree-parser. Basically, I can't make the tree-parser read a QIIME-generated newick tree with branch lengths and support.

```
from io import StringIO
from skbio import read
from skbio.tree import TreeNode
from skbio.diversity import beta 

tree_fp = "..."
tree = read(tree_fp, format="newick", into=TreeNode)
```

When I try to calculate UniFrac using this tree

```
bdiv = beta.weighted_unifrac(s1, s2, ids, tree)
```

where `s1`, `s2` are OTU-counts and `ids` are OTU-labels, I get `ValueError: ``tree`` must be rooted.`. The error comes from `skbio/diversity/_util.py`

```
...
    if len(tree.root().children) > 2:
        # this is an imperfect check for whether the tree is rooted or not.
        # can this be improved?
        raise ValueError("``tree`` must be rooted.")
```

When I try to root the tree using `tree.root_at` by passing a tip label (i.e. an OTU id): `rooted_tree = tree.root_at("denovo6631") `, the method raises `TreeError: Can't use a tip ('denovo6631') as the root `. Do you have a fix for this issue? 

I guess it is related to https://github.com/biocore/scikit-bio/issues/1355 because the tree is not properly parsed, i.e. the parser treats either branch-lengths or support values as node labels.

**Comment by wasade** [comment]
Hi @grayfall, I do not believe the tree is being improperly parsed from the description here. I think QIIME is creating an unrooted tree. The reason that `root_at` is failing is that it is expecting an internal node, not a tip. Does the situation resolve itself if [`root_at_midpoint`](http://scikit-bio.org/docs/latest/generated/skbio.tree.TreeNode.root_at_midpoint.html#skbio.tree.TreeNode.root_at_midpoint) is used?

**Comment by grayfall** [comment]
@wasade thank you for reviewing the issue. I still believe the tree is not parsed properly.

```
In [113]: biom_fp = "bench/denovo/100/otu_table.biom"

In [114]: tree_fp = "bench/denovo/100/rep_set.tre"

In [115]: table = biom.load_table(biom_fp)

In [116]: samples = table.ids(axis="sample")

In [117]: ids = table.ids(axis="observation")

In [118]: s1 = table.data(samples[0])

In [119]: s2 = table.data(samples[1])

In [120]: s1.shape, s2.shape
Out[120]: ((11095,), (11095,))

In [121]: ids.shape
Out[121]: (11095,)

In [122]: tree = read(open(tree_fp), format="newick", into=TreeNode).root_at_midpoint()

In [123]: bdiv = beta.weighted_unifrac(s1, s2, ids, tree)

---------------------------------------------------------------------------
MissingNodeError                          Traceback (most recent call last)
...
MissingNodeError: All ``otu_ids`` must be present as tip names in ``tree``. ``otu_ids`` not corresponding to tip names (n=5606): denovo3626 denovo1536 denovo483 denovo6644 denovo
8305 denovo2624 denovo730 denovo5984 denovo141...
```

I can provide the OTU-table and the tree

**Comment by grayfall** [comment]
@wasade oh, sorry, I forgot to remove analigned OTUs from the tree

```
In [19]: biom_fp = "bench/denovo/100/otu_table.biom"

In [20]: tree_fp = "bench/denovo/100/rep_set.tre"

In [21]: failed_fp = "bench/denovo/100/aln/rep_set_failures_id.txt"

In [22]: table = biom.load_table(biom_fp)

In [23]: samples = table.ids(axis="sample")

In [24]: ids = table.ids(axis="observation")

In [25]: failed_otus = set(open(failed_fp).read().splitlines())

In [26]: id_mask = [id_ not in failed_otus for id_ in ids]

In [27]: masked_ids = ids[id_mask]

In [28]: s1 = table.data(samples[0])[id_mask]

In [29]: s2 = table.data(samples[1])[id_mask] 

In [30]: tree = read(open(tree_fp), format="newick", into=TreeNode).root_at_midpoint()

In [31]: bdiv = beta.weighted_unifrac(s1, s2, masked_ids, tree)

In [32]: bdiv
Out[32]: 0.7860005232414643
```

It works fine now. Thank you.

**Comment by wasade** [comment]
Great to hear! I'm going to close out the issue -- please reopen it if necessary
