### ISSUE TITLE
skbio.stats._subsample.subsample_counts bootstrap should be agnostic of counts

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#1526]
When `replace=True`, this method should not care about how large `n` is, since it is just sampling from a multinomial distribution in the end.

We'll want to remove the `ValueError` [here](https://github.com/biocore/scikit-bio/blob/master/skbio/stats/_subsample.py#L235) when `replace=True`

**Comment by jairideout** [comment]
Fixed in #1527
