### ISSUE TITLE
Test failure on Debian system

### ISSUE THREAD

**Issue by tillea** [biocore/scikit-bio#1531]
Hi,
I'm one of the Debian maintainers of scikit-bio.  There was a [failure in the test suite](https://bugs.debian.org/868962) reported.  Do you have any hint how to fix this?
Kind regards, Andreas.

**Comment by mortonjt** [comment]
Hi @tillea .  that looks like that issue is stemming from the deepcopy issues that we've seen in the newest release in pandas (see this [PR thread](https://github.com/biocore/scikit-bio/pull/1530)).  The best way proceed with this is to only rely on the previous release of pandas ( before 0.20.3 ).
