### ISSUE TITLE
TreeNode.prune can push length to the root

### ISSUE THREAD

**Issue by wasade** [biocore/scikit-bio#1533]
Outlined in the example below:

```python
In [1]: import skbio

In [2]: t = skbio.TreeNode.read(["(a:1)b;"])

In [3]: t.prune()

In [4]: str(t)
Out[4]: 'a:1.0;\n'
```

`prune` collapses single descendent nodes. However, when a single descendent node falls from the root, it is incorrect to collapse that node as the end effect is to push the `length` to the root, thereby indicating the root as a disconnected edge. 

This issue was first noted in biocore/unifrac#46.

**Comment by tanaes** [comment]
Lots of phylogenetic programs give trees with roots with nonzero branch lengths. I think this behavior is fine.

**Comment by wasade** [comment]
Okay, awesome. Thanks!
