### ISSUE TITLE
Conda can't find scikit-bio

### ISSUE THREAD

**Issue by DLFinney** [biocore/scikit-bio#1536]
Hello,

I'm fairly new to installing python packages. However, I have successfully used conda to install other packages e.g. iris.

I'm having trouble with scikit-bio. As a side issue, I'm looking to install version 0.2.3 with the hope it's compatible with python2.7. All the same, I can't find any version.

>  conda install -c https://conda.anaconda.org/biocore scikit-bio

Result:
Fetching package metadata ...............

PackageNotFoundError: Packages missing in current channels:

  - scikit-bio

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/biocore/win-64
  - https://conda.anaconda.org/biocore/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

Do you have any idea why this is not working?

**Comment by ebolyen** [comment]
Hi @DLFinney, the biocore channel doesn't have versions that early (though defaults does). I would recommend installing scikit-bio `0.4.2` if you absolutely must have Python 2.7 though, it was the lastest version with Python 2 support.

**Comment by DLFinney** [comment]
Thank you @ebolyen . I appreciate the advice. 

Unfortunately, as I say, I can't seem to find any scikit-bio version using conda install. Do have any idea why it wouldn't coming up?

**Comment by ebolyen** [comment]
Are you on Windows? scikit-bio has some not-so-portable dependencies that
prevent us from compiling a Windows build.

**Comment by DLFinney** [comment]
Ah, yes, I am on Windows. Does that make it difficult/impossible to install scikit-bio?

I still find it strange that conda install can't even find the package though.

**Comment by jairideout** [comment]
scikit-bio doesn't officially support Windows. conda can't find a scikit-bio package matching your specs because we don't have Windows builds up (conda is architecture-aware in its searches).

**Comment by ThirstyGeo** [comment]
This is too bad; your compositional data coding is really good.

**Comment by gbrunner** [comment]
@jairideout Any plans to get a Windows build up?

**Comment by jairideout** [comment]
Not to my knowledge (perhaps @biocore/scikit-bio-core-devs can comment more on this).

**Comment by mortonjt** [comment]
@gbrunner, there are numerous difficulties getting skbio fully integrated into windows, its hard for me to see skbio becoming windows compatible in the near future.

However, the Ubuntu emulators are getting really solid (see [here](https://insights.ubuntu.com/2016/03/30/ubuntu-on-windows-the-ubuntu-userspace-for-windows-developers)).  Just because skbio is not windows compatible, doesn't mean that you should have issues running skbio on a windows machine.

**Comment by mortonjt** [comment]
@DLFinney @gbrunner @ThirstyGeo this issue should be resolved.  Reopen if not.

**Comment by marianess** [comment]
Is it still relevant in 2020? No scikit-bio on windows?

**Comment by ElDeveloper** [comment]
@marianess yes this is still the case.

**Comment by pearseb** [comment]
well that's really really annoying! Is there any plans to make this available to window users?

**Comment by mortonjt** [comment]
Probably not. Maintaining windows would not be fun ...

But if you want to install skbio on your machine, it should be fine - you
can always install a Ubuntu terminal
https://ubuntu.com/tutorials/ubuntu-on-windows#1-overview

**Comment by UniverseCraft** [comment]
If I might make a suggestion, this compatibility information should be advertised very prominently on your website. I'm sure I'm not the only one who wasted hours trying to figure out why it wouldn't install.
