### ISSUE TITLE
How to deal with unrooted tree from TreeNode.from_taxonomy() when computing phylogenetic diversity measures

### ISSUE THREAD

**Issue by boulund** [biocore/scikit-bio#1538]
Hi,

Not sure exactly what to set as title for this issue, but I'll try to describe my problem as best I can here:

1. I've created a `skbio.TreeNode` using `TreeNode.from_taxonomy()`, and that works just fine. I get a `tree` that can be printed using `TreeNode.ascii_art()`. This `tree` is unrooted.
2. I can root the tree, by calling e.g. `tree_rooted = tree.root_at(tree)`. I printed with the `ascii_art` function, this produces a tree that looks rooted.
3. When trying to compute phylogenetic distances e.g. a unifrac distance or a phylogentic alpha diversity metric such as `faith_pd`, I get an error stating I need to use a rooted tree:

```
beta_diversity = skbio.diversity.beta_diversity("weighted_unifrac", 
                                                              counts=df_16S.transpose().values, 
                                                              ids=df_16S.columns,
                                                              otu_ids=tax_otus,
                                                              tree=taxtree.root_at(taxtree))

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-418-f638b12a75ce> in <module>()
      5                                                               ids=df_16S.columns,
      6                                                               otu_ids=tax_otus,
----> 7                                                               tree=taxtree.root_at(taxtree))

/home/ctmr/anaconda3/lib/python3.6/site-packages/skbio/diversity/_driver.py in beta_diversity(metric, counts, ids, validate, pairwise_func, **kwargs)
    252         otu_ids, tree, kwargs = _get_phylogenetic_kwargs(counts, **kwargs)
    253         metric, counts_by_node = _setup_multiple_unweighted_unifrac(
--> 254                 counts, otu_ids=otu_ids, tree=tree, validate=validate)
    255         counts = counts_by_node
    256     elif metric == 'weighted_unifrac':

/home/ctmr/anaconda3/lib/python3.6/site-packages/skbio/diversity/beta/_unifrac.py in _setup_multiple_unweighted_unifrac(counts, otu_ids, tree, validate)
    485     """
    486     counts_by_node, _, branch_lengths = \
--> 487         _setup_multiple_unifrac(counts, otu_ids, tree, validate)
    488 
    489     f = functools.partial(_unweighted_unifrac, branch_lengths=branch_lengths)

/home/ctmr/anaconda3/lib/python3.6/site-packages/skbio/diversity/beta/_unifrac.py in _setup_multiple_unifrac(counts, otu_ids, tree, validate)
    449 def _setup_multiple_unifrac(counts, otu_ids, tree, validate):
    450     if validate:
--> 451         _validate_otu_ids_and_tree(counts[0], otu_ids, tree)
    452 
    453     counts_by_node, tree_index, branch_lengths = \

/home/ctmr/anaconda3/lib/python3.6/site-packages/skbio/diversity/_util.py in _validate_otu_ids_and_tree(counts, otu_ids, tree)
     87         # this is an imperfect check for whether the tree is rooted or not.
     88         # can this be improved?
---> 89         raise ValueError("``tree`` must be rooted.")
     90 
     91     # all nodes (except the root node) have corresponding branch lengths

ValueError: ``tree`` must be rooted.
```

I can compute the non-phylogenetic metrics just fine, no problems there. 
Is there a better (intended) way of doing what I'm trying to do?

**Comment by wasade** [comment]
Hi @boulund,

Would you be able to share the taxonomy you're using? I'm curious, why is a taxonomy being used instead of a phylogeny?

The "workaround" here is to pass `validate=False`. But, I agree the call to `root_at` should return a rooted tree. My guess is `root_at` does not handle the identity case properly as it's being used right now, in which case it should through an exception.

**Comment by boulund** [comment]
Hi, thanks for such a swift reply! 

I'm just making the tree based on the lineages of the OTUs identified in the specific samples I'm currently working with. Mostly trying out scikit-bio to see if it does what I want it to without too much hassle :).

Not validating seems to work just fine! Thanks for the help. Now I'll just have to be extra careful to validate the results that come out :)

**Comment by wasade** [comment]
Okay, thanks. I do recommend using a phylogeny based on the OTU data, not the taxonomy. What I suspect is the lineage information being passed in only represents a single domain, which would put the root of the taxonomy at, for instance, `d__Bacteria`. That domain has > 80 phyla below it. The definition of "rooted" is whether the top node has 2 or fewer children, which for taxonomy does not make sense. 

Note that the input taxonomy tree will not have any branch length set. That is one reason why the distances returned would be zero. One potential way around this is to set unit distances for every edge in the taxonomy, which can be done using the code below. But again, I do recommend using a phylogeny if possible.

```python
for n in taxtree.traverse(include_self=False):
   n.length = 1.0
```

**Comment by boulund** [comment]
I'll try with unit distances tomorrow morning when I get back to work, just to see if that'll produce something more meaningful. 

I didn't know about the definition of a tree root only having max two children, but of course that makes sense. Thanks for that! For my toy example here it doesn't really matter if the tree I'm using is a suboptimal representation of the distances, but I agree that it would make much more sense with a phylogeny instead of just the taxonomy. Can you recommend a good way of importing a meaningful phylogeny for any given subset of taxa? I can't seem to find anything useful in the skbio documentation, unfortunately :(.

**Comment by wasade** [comment]
I'm not sure I fully understand the question. The normal workflow would be to load an phylogeny generated by some upstream step:

```
tree = skbio.TreeNode.read('/path/to/tree.newick')
```

The internal calls to the diversity metrics will automatically subset the tree to only the relevant tips.

**Comment by boulund** [comment]
Ok, that's the problem right there. I don't have an upstream step that produces a phylogeny.

**Comment by wasade** [comment]
@boulund, I'm closing this issue in favor of #1539 which is specifically about `TreeNode.root_at`. Please reopen if you think there is more that should be discussed on this thread.

**Comment by boulund** [comment]
Setting unit distances across all branches in the tree produced unifrac distances that seem reasonable. Thank you, I very much appreciate the help.

**Comment by wasade** [comment]
Great!

**Comment by MathGon** [comment]
Same procedure, generating a `skbio.TreeNode` using `TreeNode.from_taxonomy()` produce a tree. I also used `root_at(tree)`. My tree seems to be valid, `tree.is_root()` returns `True` but the beta_diversity computing returns the `ValueError: tree must be rooted.` :(

**Comment by wasade** [comment]
The `is_root` check tests whether the root node is bifurcating or multifurcating. If it is a multifurcation, it is considered to not be rooted. If you specify `validate=False` on the call to `beta_diversity`, it should not perform this check.

**Comment by khp1** [comment]
Hello,

I have a similar problem that I've asked about here [https://www.biostars.org/p/467682/](url) and here [https://bioinformatics.stackexchange.com/questions/14570/skbio-valueerror-tree-must-be-rooted-when-using-tree-generated-from-silvas-a](url). 

I'm using a tree generated from SILVA ACT to calculate unweighted unifrac distances on a windows machine (`np.dtype("l") gives dtype('int32')`). I was getting the ` tree must be rooted` error even though  `tree.is_root()` yields `True`.

As suggested, I then used `validate=False` in the function call, but then I get a different error: `ValueError: Buffer dtype mismatch, expected 'DTYPE_t' but got 'long'`

Here is the entire error message:
```
Traceback (most recent call last):

  File "<ipython-input-72-683106e23371>", line 1, in <module>
    unweighted_unifrac(seq1, seq2, esvs, tree,validate=False)

  File "C:\Users\Kaumudi\Anaconda3\lib\site-packages\skbio\diversity\beta\_unifrac.py", line 147, in unweighted_unifrac
    normalized=False, unweighted=True)

  File "C:\Users\Kaumudi\Anaconda3\lib\site-packages\skbio\diversity\beta\_unifrac.py", line 315, in _setup_pairwise_unifrac
    _vectorize_counts_and_tree(counts, otu_ids, tree)

  File "C:\Users\Kaumudi\Anaconda3\lib\site-packages\skbio\diversity\_util.py", line 126, in _vectorize_counts_and_tree
    counts_by_node = _nodes_by_counts(counts, otu_ids, tree_index)

  File "skbio/diversity/_phylogenetic.pyx", line 213, in skbio.diversity._phylogenetic._nodes_by_counts

  File "skbio/diversity/_phylogenetic.pyx", line 68, in skbio.diversity._phylogenetic._traverse_reduce
```

Please let me know if you'd like me to attach the tree file. 
Thank you!
