### ISSUE TITLE
error: AttributeError: 'Tree' object has no attribute 'root'

### ISSUE THREAD

**Issue by smazrouee** [biocore/scikit-bio#1552]
unweighted_unifrac from skbio.diversity.beta keeps giving me this error while I am sure my tree is rooted: AttributeError: 'Tree' object has no attribute 'root'

So is there a specific way of reading the tree that unifrac enforces? I read a tree using dendropy as: 

tree = dendropy.Tree.get(path='blah blah', schema="newick",rooting='force-rooted')

**Comment by wasade** [comment]
The UniFrac method in skbio relies on `skbio.TreeNode`, can you try using `tree = skbio.TreeNode.read("path/to/tree")`?

**Comment by wasade** [comment]
Closing this issue as this method was not intended to take dendropy trees but please reopen if the documentation needs clarification.
