### ISSUE TITLE
update RELEASE.md for conda pkg build instruction

### ISSUE THREAD

**Issue by RNAer** [biocore/scikit-bio#1563]
Specifically, [here](https://github.com/biocore/scikit-bio/blob/master/RELEASE.md#publish-the-release)

**Comment by mortonjt** [comment]
@RNAer is this still relevant?

**Comment by RNAer** [comment]
I recall so

**Comment by RNAer** [comment]
wait, i mis-read the thread. I don't remember - looks like it is updated. I'll close it.
