### ISSUE TITLE
ValueError: The samples by features table 'y' must be nonnegative

### ISSUE THREAD

**Issue by prubbens** [biocore/scikit-bio#1575]
I am using the function `cca(X,y)` to perform canonical correspondence analysis. 

When calling the method, I get the following error: 
`ValueError: The samples by features table 'y' must be nonnegative`. 

Yet when I call y.min() the lowest value is positive. 

Can this be a possible bug in the implementation? 

This is using both scikit-bio 0.4.2 and 0.5.1.

**Comment by jaredraynes** [comment]
@prubbens checking the documentation, the function is def cca(y, x) not cca(X, y) so you have just got your order mixed up. Reversing them should fix the problem.

**Comment by jni** [comment]
Alternatively, you named your features table 'X' but that is where you should check for nonnegative values.

**Comment by mortonjt** [comment]
@prubbens reopen if this has not bee addressed
