### ISSUE TITLE
[Question] How to correctly use ILR with balance tree basis?

### ISSUE THREAD

**Issue by jolespin** [biocore/scikit-bio#1582]
There are two details that confuse me regarding using `ilr` and a custom `basis` argument.

I understand that `gneiss` is used for the `balance_basis` and that `m-1` attributes/coumns are returned by `ilr` which are supposed to represent the balances of the nodes in the tree.

**My first question, how can I know which column goes to which node in my dendrogram?

My second question, how does the `ilr` function know the labels/order of the nodes in the tree that was provided and does my order for the `mat` input matter at all?**

Lastly, (bonus) is the implementation below equivalent to [PhILR](https://elifesciences.org/articles/21887)? 

My `df_otus` is a `pd.DataFrame` that I filtered.  The `newick` tree was created by `clustalo` when I did a multiple sequence alignment of the `Otu` centroid sequences from `uparse`.

```python
import ete3, skbio
from gneiss.balances import balance_basis
import pandas as pd
from io import StringIO

# Otu table
df_otus = df_counts_f1.copy() # filter Otu counts where n=64 samples, m=883 otus
# Path to the newick file generated from 16S sequences in clustalo
path_to_newick_from_clustalo = "./Data/otu_clustering/clustalo_output/otus.qfilter.EE0.15.guidetree"
# Convert ete3 tree
t = ete3.Tree(newick=path_to_newick_from_clustalo)
# Prune tree
t.prune(df_otus.columns)
# Get newick string for pruned tree
newick = t.write(outfile=None)
# Convert to skbio Tree object
t_skbio = skbio.TreeNode.read(StringIO(newick))
# Gneiss
basis, nodes = balance_basis(t_skbio)
# ILR
df_ilr = pd.DataFrame(ilr(df_otus+1, basis=basis), index=df_otus.index)
```

**Comment by mortonjt** [comment]
@jolespin reopen if this hasn't been addressed
