### ISSUE TITLE
Update pandas version to newest

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/scikit-bio#1585]
As noted in #1584, that is a temporary fix and we should find a way to update the codebase or dependencies to be able to use the latest release of pandas.

**Comment by tillea** [comment]
Any news about this?

**Comment by ElDeveloper** [comment]
Yes, just one quick update. We are planning to update the dependency 
stack for scikit-bio so that this is no longer a problem. We'll 
hopefully have updates in the next coming weeks.

**Comment by mortonjt** [comment]
This is addressed here: https://github.com/biocore/scikit-bio/pull/1618

**Comment by tillea** [comment]
I can confirm that the Debian package builds now.  Do you plan any release incorporating these changes soon?

**Comment by ElDeveloper** [comment]
Yes we do. However, we don't have a specific target release date (lots of moving pieces at the moment).

**Comment by ElDeveloper** [comment]
The version pins have been removed and the release has been pushed to pypi and conda-forge.
