### ISSUE TITLE
Test suite fails with Python 3.7

### ISSUE THREAD

**Issue by tillea** [biocore/scikit-bio#1595]
Hi,
there is a [bug report](https://bugs.debian.org/906156) against the Debian packaged version of python-skbio when building with Python 3.7.  While Debian has currently version 0.5.2 I verified that the problem persists in the (to be packaged) version 0.5.3.   The [bug report](https://bugs.debian.org/906156) contains a full log of the error - but feel free to ping me for more details about it.
Kind regards, Andreas.

**Comment by ElDeveloper** [comment]
Thanks for reporting this @tillea. These failures/errors seem to be related to the pandas version restriction that was put in place for 0.5.3 (after it was first tagged). If you check with `pandas >= 0.19.2, < 0.23.0`, tests should pass.

**Comment by tillea** [comment]
Hi,
On Mon, Aug 20, 2018 at 02:15:06PM -0700, Yoshiki Vázquez Baeza wrote:
> If you check with `pandas >= 0.19.2, < 0.23.0`, tests should pass.
Ahh, this means skbio is not yet adapted to latest pandas version?  For the Debian package I do not have an option to pick some specific pandas version since only one version is supported as Debian package and I need to build against a packaged version.  Do you intend to support latest pandas in the near future?
Kind regards, Andreas.

**Comment by tillea** [comment]
Update:  Even with version 0.5.4 the test suite keeps on failing.  Here is the relevant part of a test build of the Debian package.
[python-skbio_0.5.4.log](https://github.com/biocore/scikit-bio/files/2329291/python-skbio_0.5.4.log)

**Comment by mortonjt** [comment]
This is addressed here: https://github.com/biocore/scikit-bio/pull/1618

**Comment by mortonjt** [comment]
Relevant issue: https://github.com/conda-forge/scikit-bio-feedstock/pull/12#issuecomment-437708432

**Comment by ElDeveloper** [comment]
The release has been pushed to pypi and conda-forge. The version pins have been removed. Please let us know if you still see any failures.

**Comment by lynalbct** [comment]
cant seem to figure out why this error keep on appearing. already installed scikit-bio in my ubuntu machine.
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-b1de7c6dfb25> in <module>()
      4 from IPython.core import page
      5 page.page = print
----> 6 from iab.algorithm import show_F

ModuleNotFoundError: No module named 'iab'

**Comment by thermokarst** [comment]
Hi @lynalbct - this looks like you are running into problems importing `iab`, an entirely [different project](https://github.com/applied-bioinformatics) - perhaps you could open an issue up [there?](https://github.com/applied-bioinformatics/An-Introduction-To-Applied-Bioinformatics) Thanks!

**Comment by kanochan** [comment]
Hi,
I just followed cookbook of scibio-kit to construct a nj tree, but it seems that nj() function cannot correctly accept DataMatrix, the command: tree = nj(dm) will raise **IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices.**
Even if I extract numpy array from DadaMatrix to use tree = nj(dm.data) will give another error: **AttributeError: 'memoryview' object has no attribute 'sum'**
Is that my mistake in usage or bug in this function?
