### ISSUE TITLE
ImportError: No module named skbio.stats.distance

### ISSUE THREAD

**Issue by CassieMai** [biocore/scikit-bio#1628]
Hello, it happens to have a problem in importing modules after scikit-bio installed under python 2.7.
I used this command but failed. Does anyone have idea?

`from skbio.stats.distance import mantel`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named skbio.stats.distance
```

**Comment by CassieMai** [comment]
Oh, scikit-bio can only be used on python3.

**Comment by ElDeveloper** [comment]
The newest version can only be used with Python 3, if you are using that version then that import should work. If you are using Python 2.7 can you check which version you have installed? For example by doing `python -c 'import skbio; print(skbio.__version__)'`.

**Comment by ElDeveloper** [comment]
You would need to install scikit-bio like this: `pip install scikit-bio==0.4.2`.

**Comment by CassieMai** [comment]
Sure. Thank you very much. @ElDeveloper
