### ISSUE TITLE
Update package on pypi

### ISSUE THREAD

**Issue by haobibo** [biocore/scikit-bio#1634]
The latest version of `scikit-bio` on pypi fall behind github code: https://pypi.org/project/scikit-bio
The current version on pypi is 0.5.4, which has some version requirements for some packages, e.g: `pandas<0.23`, this drags pandas from updating to latest version.

Update `scikit-bio` will help users benefit from the latest version of pandas and other packages.

Also, here is a tutorial for using travis CI to update pypi automatically: https://docs.travis-ci.com/user/deployment/pypi/

**Comment by thermokarst** [comment]
Hey there @haobibo - we are anticipating a new release that drops the version pins in the near-ish future (no current ETA). Please stay tuned.

**Comment by ElDeveloper** [comment]
The release has been pushed to pypi and conda-forge.
