### ISSUE TITLE
Test suite uncovers issues with latest numpy version

### ISSUE THREAD

**Issue by tillea** [biocore/scikit-bio#1648]
Hi,
Debian just upgraded to latest numpy which resulted in a [Bug report](https://bugs.debian.org/917693) against the python-skbio package.  The log says something like:

    ...
    ======================================================================
    ERROR: test_values_property (skbio.sequence.tests.test_sequence.TestSequence)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_skbio/build/skbio/sequence/tests/test_sequence.py", line 81, in setUp
        self.lowercase_seq = Sequence('AAAAaaaa', lowercase='key')
      File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_skbio/build/skbio/sequence/_sequence.py", line 647, in __init__
        self._convert_to_uppercase(lowercase_mask)
      File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_skbio/build/skbio/sequence/_sequence.py", line 676, in _convert_to_uppercase
        with self._byte_ownership():
      File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_skbio/build/skbio/sequence/_sequence.py", line 2191, in _byte_ownership
        self._bytes.flags.writeable = True
    ValueError: cannot set WRITEABLE flag to True of this array
  
    ======================================================================
    FAIL: test_init_lowercase_no_validation (skbio.sequence.tests.test_grammared_sequence.TestGrammaredSequence)
    ----------------------------------------------------------------------
    ValueError: cannot set WRITEABLE flag to True of this array
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_skbio/build/skbio/sequence/tests/test_grammared_sequence.py", line 238, in test_init_lowercase_no_validation
        ExampleGrammaredSequence(s, lowercase=True)
    AssertionError: "character.*'R'" does not match "cannot set WRITEABLE flag to True of this array"
  
    ----------------------------------------------------------------------
    Ran 2340 tests in 42.261s
  
    FAILED (SKIP=30, errors=193, failures=1)

The numpy version that was used is 1.16.0~rc1.

Kind regards, Andreas.

**Comment by ElDeveloper** [comment]
Thanks for reporting this. From looking around, it looks like this was the consequence of a bug-fix in NumPy 1.16:

```
Arrays based off readonly buffers cannot be set writeable
-------------------------------------------------------------
We now disallow setting the writeable flag True on arrays created
from fromstring(readonly-buffer).
```

PR in Numpy here: https://github.com/numpy/numpy/pull/11739

I am not familiar with the code in sequence.py but maybe @ebolyen can have a look? From some tinkering in the console, it looks like copying the data into a byte array and then passing that to `np.frombuffer` should suffice. For example:


This is what we have in _sequence.py.

```
# this fails 👎
In [1]: import numpy as np
   ...: s = 'asdf'.encode('ascii')
   ...: x = np.frombuffer(s, dtype=np.uint8)
   ...:

In [2]: x.flags.writeable = True
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-95da424ff829> in <module>
----> 1 x.flags.writeable = True

ValueError: cannot set WRITEABLE flag to True of this array

```

This is as inspired from some comments in the NumPy PR:

```
# this works 👍
In [3]: q = bytearray(4)

In [4]: q[:] = 'asdf'.encode('ascii')

In [10]: x = np.frombuffer(q, dtype=np.uint8)

In [11]: x.flags.writeable = True
```



--------------

This is the [failing unit test](https://github.com/biocore/scikit-bio/blob/master/skbio/sequence/tests/test_grammared_sequence.py#L238).

**Comment by ebolyen** [comment]
I need to look into this more, but mutating a view of a shared buffer sounds bad, so I'm currently thinking either we disable support for that (was this accidental?), or do as you suggest and transparently build a copy. This can probably be done automatically within the `_byte_ownership` private context manager, which should be used anywhere mutation is allowed to happen.

**Comment by ebolyen** [comment]
I think [this section](https://github.com/biocore/scikit-bio/blob/master/skbio/sequence/_sequence.py#L2187-L2189) may no longer be behaving as expected.

If I understand correctly, assuming we own those bytes, setting writable should be fine. So this means that either that state is invalid sometimes (looks like there might be a way to detect if we're using a read-only buffer). Or the copy is not creating a copy of the bytes themselves (or perhaps it's preserving the read-only state on the array?)

**Comment by RizzerOnGitHub** [comment]
It's not a question of shallow copy vs deep copy, is it?

**Comment by tillea** [comment]
Hi again.  Do you see any solution for this problem?  If not we will not be able to ship skbio with the next Debian stable release.

**Comment by ebolyen** [comment]
Hi @tillea, very sorry I lost track of this issue, I may have some time to fix this, when would you need this by?

**Comment by tillea** [comment]
On Thu, Feb 07, 2019 at 09:36:06PM +0000, Evan Bolyen wrote:
> Hi @tillea, very sorry I lost track of this issue, I may have some time to fix this, when would you need this by?
Things are happening _ I also lost this out of focus.  The *very* latest is tomorrow but better today.

**Comment by ebolyen** [comment]
Presumably it is too late at this point, but it turns out the fix was extremely simple. 

scikit-bio already understood ownership of the bytes, it was just mistaken in thinking it had any say in byte/string literals, which this numpy change exposed.

**Comment by RizzerOnGitHub** [comment]
Thanks @ebolyen. The Debian freeze means we can't get new packages into the stable release, but a simple patch is no problem (full freeze comes next month).

**Comment by afrubin** [comment]
Will there be a scikit-bio release soon that incorporates this fix?
