### ISSUE TITLE
New `DistanceMatrix` file format

### ISSUE THREAD

**Issue by wasade** [biocore/scikit-bio#1650]
The `DistanceMatrix` file format is ASCII-based leading to large overhead as the number of samples stored increases. This overhead contributes to high load times both from the volume of data to read from disk, and the necessary type conversions. We can do much better. At a minimum, representing the distance matrix values as double precision floats will reduce the amount of data stored by > 2X as at present, the distance matrix object is typically writing 17 or 18 bytes per element. We're also using a fairly large amount of storage for whitespace: a 10,000 sample distance matrix uses roughly 100MB of storage for `\t` characters. 

This ASCII format additionally does not easily afford random access, or mmap support. 

In this issue, we propose YABF (yet another bioinformatics format) for representing a distance matrix on disk. This format is a simple binary format suitable for random access when obtaining individual samples. The format is as follows:

```text
16-bytes char, magic number and version, and is the file header
32-bit unsigned integer, the number of samples in the distance matrix
N * 16-bit unsigned integer, the number of bytes needed each sample identifier; N is the number of samples in the distance matrix
M bytes char, a character array of the sample identifiers; M is the sum of the sample identifier sizes
N * 64-bit float, a row in the distance matrix
<...snip...>
N * 64-bit float, the last row in the distance matrix
16-bytes char, magic number and version, and is the file footer
```

The rows of the distance matrix are to be stored in order with respect to the sample identifiers. And the values in a row are to be in order with respect to the sample identifiers. This is somewhat similar to the partial distance matrix format used (internally) by Striped UniFrac (relevant description [here](https://github.com/biocore/unifrac/blob/master/sucpp/api.hpp#L139-L179)). 

The motivation to store this format as a dense representation is it allows for random access relatively easily, where as a condensed representation requires loading the full condensed structure first. Notably, the rows are all the same number of bytes and are contiguous meaning that offsets can be easily determined from the header. 

Alternative to the above, a format that is based off of numpy `save` or `savez` or `savez_compressed` is certainly possible. The hesitation is ease of interaction with that format from other languages, and it's not clear if this would easily allow for random access. It is also feasible to represent this using HDF5 with the caveat that it would add `h5py` as a dependency, although it would easily support random access and portability.  

A brief google search did not yield another existing format we could just use here but it's certainly possible the search wasn't wide enough.

**Comment by mortonjt** [comment]
To follow up on this discussion, the amount of memory required to generate large distance matrices will scale quadratically.  While this may be ok in the short-term, this problem will blow up once we start hitting past 1 million samples.

It maybe worthwhile to start thinking about alternative representations (i.e. embeddings from [word2vec](https://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf)) where only the embedding matrices are stored.  These matrices are small, and can regenerate corresponding distances.

If we were using Unifrac as an example, rather than storing a matrix of 1 million by 1 million, we could have a matrix of 1 million by 100 latent dimensions (i.e. PC components), and we'd never explicitly compute the full distance matrix.

**Comment by wasade** [comment]
Yes, certainly quadratically, and 1M samples is distant but not that distant of a problem. 100k is a reality right now, is a problem with the present structure, and I believe that distance matrices are unlikely to stop being useful in the near or far future. 

I think an alternative embedding space and representation is wonderful, and that it should be pursued, however in my opinion it is a separate and distinct issue.

**Comment by wasade** [comment]
We now have a binary format that can be used
