### ISSUE TITLE
Project Plans

### ISSUE THREAD

**Issue by averagehat** [biocore/scikit-bio#1661]
What's the status of this project? Are there plans to maintain it in the future?

The current release on conda is broken due to #1648

**Comment by ElDeveloper** [comment]
@averagehat, we plan to continue to maintain the available functionality and to fix some outstanding bugs. However we don't have a clear timeline on some of these issues.

As for pushing out a new release, I'll try to do that next week. Thanks for the reminder, I'll post an update when I do that.

**Comment by wasade** [comment]
skbio is a core dependency for QIIME 2 and other large efforts. The project will continue to live on, however we remain bandwidth limited on addressing new functionality requests
