### ISSUE TITLE
Is the center log-ratio implementation correct?

### ISSUE THREAD

**Issue by jolespin** [biocore/scikit-bio#1668]
I'm looking at the implementation of `clr` and I noticed it says geometric mean. 
```
where :math:`g_m(x) = (\prod\limits_{i=1}^{D} x_i)^{1/D}` is the geometric
    mean of :math:`x`.
```
https://github.com/biocore/scikit-bio/blob/0.5.4/skbio/stats/composition.py#L436

The actual implantation is using [numpy's arithmetic mean](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html#numpy.mean) which is different than [scipy's gmean](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gmean.html).

Am I misinterpreting this?

**Comment by mortonjt** [comment]
This should be ok, since the log of the geometric mean is the arithmetic mean of the logs

**Comment by jolespin** [comment]
Nice,  I didn't know that!  Thanks
