### ISSUE TITLE
Incorporate features data for PCoA methods features and biplot_scores

### ISSUE THREAD

**Issue by DKioroglou** [biocore/scikit-bio#1670]
The PCoA class has the methods **biplot_scores** and **features**.  
However they return None as they need the features data.  

Is there any way to pass features data along with the distance matrix?

**Comment by ElDeveloper** [comment]
In order to get the biplot features you need to use the results from pcoa into `skbio.stats.ordination.pcoa_biplot` together with a table of features or additional variables for each sample (in the form of a DataFrame). For example:

```python
from skbio.stats.ordination import pcoa_biplot, pcoa

biplot = pcoa_biplot(pcoa(dm), table_of_features)
```
