### ISSUE TITLE
ssw alignments returning incorrect aligned sequences

### ISSUE THREAD

**Issue by jeshleman-sgmo** [biocore/scikit-bio#1677]
Alignments with indels are not producing the correct aligned sequences in some cases

from skbio.alignment import StripedSmithWaterman
>>> q = 'GTGACCGCCCCTAGGCTGCAGAGGCCCTTCCAGTGTCG'
>>> t =  'GTGACCCGCCCTATGGCTGAGAGGCCCTTCCAGTGTCG'
>>> query = StripedSmithWaterman(q)
>>> alignment = query(t)
>>> alignment.target_sequence
'GTGACCCGCCCTATGGCTGAGAGGCCCTTCCAGTGTCG'
>>> alignment.query_sequence
'GTGACCGCCCCTAGGCTGCAGAGGCCCTTCCAGTGTCG'
>>> alignment.aligned_target_sequence
'GTGACCCGCCCTATGGCT-GAGAGGCCCTTCCAGTGTCG'
>>> alignment.aligned_query_sequence
GTGACCGCCCCTA-GGCTGCAGAGGCCCTTCCAGTGTCG
>>> alignment.cigar
'13M1D5M1I19M'

These sequences do not match the cigar string nor do they match the actual optimal alignment. 

The insertion is positioned incorrectly, resulting in the alignment:
GTGACCGCCCCTA-GGCTGCAGAGGCCCTTCCAGTGTCG
||||||xx|||||x||||xx|||||||||||||||||||
GTGACCCGCCCTATGGCT-GAGAGGCCCTTCCAGTGTCG 

The correct aligned sequences should be: 

'GTGACCCGCCCTATGGCTG-AGAGGCCCTTCCAGTGTCG', 
and 
'GTGACCGCCCCTA-GGCTGCAGAGGCCCTTCCAGTGTCG'

**Comment by ebolyen** [comment]
Thanks for the report @jeshleman-sgmo, I can't believe this went unnoticed for as long as it did. You are absolutely right about the CIGAR string/alignment.
