### ISSUE TITLE
3 testsuite issues with Python3 / pandas 0.25

### ISSUE THREAD

**Issue by tillea** [biocore/scikit-bio#1678]
Hi,
I've tried to build the Debian package from latest HEAD with Python 3.7 and Pandas 0.25.  There are three remaining errors in the test suite:

    ======================================================================
    ERROR: test_munging_invalid_type_to_self_type (skbio.sequence.tests.test_sequence.TestDistance)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/build/python-skbio-0.5.5a/.pybuild/cpython3_3.7_skbio/build/skbio/sequence/tests/test_sequence.py", line 2369, in test_munging_invalid_type_to_self_type
        Sequence("ACGT").distance(42)
      File "/build/python-skbio-0.5.5a/.pybuild/cpython3_3.7_skbio/build/skbio/sequence/_sequence.py", line 1539, in distance
        other = self._munge_to_self_type(other, 'distance')
      File "/build/python-skbio-0.5.5a/.pybuild/cpython3_3.7_skbio/build/skbio/sequence/_sequence.py", line 2161, in _munge_to_self_type
        return self.__class__(other)
      File "/build/python-skbio-0.5.5a/.pybuild/cpython3_3.7_skbio/build/skbio/sequence/_sequence.py", line 622, in __init__
        s = np.frombuffer(sequence, dtype=np.uint8)
    TypeError: a bytes-like object is required, not 'int'

    ======================================================================
    ERROR: test_init_invalid_sequence (skbio.sequence.tests.test_sequence.TestSequence)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/build/python-skbio-0.5.5a/.pybuild/cpython3_3.7_skbio/build/skbio/sequence/tests/test_sequence.py", line 465, in test_init_invalid_sequence
        Sequence(('a', 'b', 'c'))
      File "/build/python-skbio-0.5.5a/.pybuild/cpython3_3.7_skbio/build/skbio/sequence/_sequence.py", line 622, in __init__
        s = np.frombuffer(sequence, dtype=np.uint8)
    TypeError: a bytes-like object is required, not 'tuple'

    ======================================================================
    FAIL: test_no_variation_pearson (skbio.stats.distance.tests.test_mantel.MantelTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/build/python-skbio-0.5.5a/.pybuild/cpython3_3.7_skbio/build/skbio/stats/distance/tests/test_mantel.py", line 247, in test_no_variation_pearson
        npt.assert_equal(obs, (np.nan, np.nan, 3))
      File "/usr/lib/python3/dist-packages/numpy/testing/_private/utils.py", line 355, in assert_equal
        assert_equal(actual[k], desired[k], 'item=%r\n%s' % (k, err_msg), verbose)
      File "/usr/lib/python3/dist-packages/numpy/testing/_private/utils.py", line 427, in assert_equal
        raise AssertionError(msg)
    AssertionError:
    Items are not equal:
    item=0

     ACTUAL: 0.0
     DESIRED: nan

    ----------------------------------------------------------------------
    Ran 2352 tests in 44.011s

    FAILED (SKIP=30, errors=2, failures=1)

Are you able to reproduce this? Any idea how to fix these?
Kind regards, Andreas.

**Comment by ElDeveloper** [comment]
@tillea thanks for reporting this. From [this Travis build](https://travis-ci.org/biocore/scikit-bio/jobs/610252775) Python 3.7 and Pandas 0.25 seem to be working fine. What version of NumPy were you using?

**Comment by tillea** [comment]
Thanks for the quick reply.
On Thu, Nov 14, 2019 at 09:24:50AM -0800, Yoshiki Vázquez Baeza wrote:
> @tillea thanks for reporting this. From [this Travis build](https://travis-ci.org/biocore/scikit-bio/jobs/610252775) Python 3.7 and Pandas 0.25 seem to be working fine. What version of NumPy were you using?
I'm using the Debian packaged numpy 1.17.4.

**Comment by ElDeveloper** [comment]
@tillea thanks for reporting this, after building a brand new environment with the latest dependencies (`conda create -n test --file ci/conda_requirements.txt && pip install -r ci/pip_requirements.txt && pip install --no-deps .`) I was also able to reproduce this error.


@ebolyen any chance you can have a look at this?

<details>

The output from running make test

```bash
self = <skbio.sequence.tests.test_sequence.TestSequence testMethod=test_init_invalid_sequence>

    def test_init_invalid_sequence(self):
        # invalid dtype (numpy.ndarray input)
        with self.assertRaises(TypeError):
            # int64
            Sequence(np.array([1, 2, 3]))
        with self.assertRaises(TypeError):
            # |S21
            Sequence(np.array([1, "23", 3]))
        with self.assertRaises(TypeError):
            # object
            Sequence(np.array([1, {}, ()]))

        # invalid input type (non-numpy.ndarray input)
        with self.assertRaisesRegex(AttributeError, r'tuple'):
>           Sequence(('a', 'b', 'c'))

../../../miniconda3/envs/latest-skbio/lib/python3.7/site-packages/skbio/sequence/tests/test_sequence.py:465:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    @stable(as_of="0.4.0")
    def __init__(self, sequence, metadata=None, positional_metadata=None,
                 interval_metadata=None, lowercase=False):
        if isinstance(sequence, np.ndarray):
            if sequence.dtype == np.uint8:
                self._set_bytes_contiguous(sequence)
            elif sequence.dtype == '|S1':
                sequence = sequence.view(np.uint8)
                # Guarantee the sequence is an array (might be scalar before
                # this).
                if sequence.shape == ():
                    sequence = np.array([sequence], dtype=np.uint8)
                self._set_bytes_contiguous(sequence)
            else:
                raise TypeError(
                    "Can only create sequence from numpy.ndarray of dtype "
                    "np.uint8 or '|S1'. Invalid dtype: %s" %
                    sequence.dtype)
        elif isinstance(sequence, Sequence):
            # Sequence casting is acceptable between direct
            # decendants/ancestors
            sequence._assert_can_cast_to(type(self))

            if metadata is None and sequence.has_metadata():
                metadata = sequence.metadata
            if (positional_metadata is None and
                    sequence.has_positional_metadata()):
                positional_metadata = sequence.positional_metadata
            if (interval_metadata is None and
                    sequence.has_interval_metadata()):
                interval_metadata = sequence.interval_metadata
            sequence = sequence._bytes
            self._owns_bytes = False
            self._set_bytes(sequence)
        else:
            # Encode as ascii to raise UnicodeEncodeError if necessary.
            if isinstance(sequence, str):
                sequence = sequence.encode("ascii")
>           s = np.frombuffer(sequence, dtype=np.uint8)
E           TypeError: a bytes-like object is required, not 'tuple'

../../../miniconda3/envs/latest-skbio/lib/python3.7/site-packages/skbio/sequence/_sequence.py:622: TypeError
_____________ TestDistance.test_munging_invalid_type_to_self_type ______________

self = <skbio.sequence.tests.test_sequence.TestDistance testMethod=test_munging_invalid_type_to_self_type>

    def test_munging_invalid_type_to_self_type(self):
        with self.assertRaises(AttributeError):
>           Sequence("ACGT").distance(42)

../../../miniconda3/envs/latest-skbio/lib/python3.7/site-packages/skbio/sequence/tests/test_sequence.py:2369:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../miniconda3/envs/latest-skbio/lib/python3.7/site-packages/skbio/sequence/_sequence.py:1539: in distance
    other = self._munge_to_self_type(other, 'distance')
../../../miniconda3/envs/latest-skbio/lib/python3.7/site-packages/skbio/sequence/_sequence.py:2161: in _munge_to_self_type
    return self.__class__(other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    @stable(as_of="0.4.0")
    def __init__(self, sequence, metadata=None, positional_metadata=None,
                 interval_metadata=None, lowercase=False):
        if isinstance(sequence, np.ndarray):
            if sequence.dtype == np.uint8:
                self._set_bytes_contiguous(sequence)
            elif sequence.dtype == '|S1':
                sequence = sequence.view(np.uint8)
                # Guarantee the sequence is an array (might be scalar before
                # this).
                if sequence.shape == ():
                    sequence = np.array([sequence], dtype=np.uint8)
                self._set_bytes_contiguous(sequence)
            else:
                raise TypeError(
                    "Can only create sequence from numpy.ndarray of dtype "
                    "np.uint8 or '|S1'. Invalid dtype: %s" %
                    sequence.dtype)
        elif isinstance(sequence, Sequence):
            # Sequence casting is acceptable between direct
            # decendants/ancestors
            sequence._assert_can_cast_to(type(self))

            if metadata is None and sequence.has_metadata():
                metadata = sequence.metadata
            if (positional_metadata is None and
                    sequence.has_positional_metadata()):
                positional_metadata = sequence.positional_metadata
            if (interval_metadata is None and
                    sequence.has_interval_metadata()):
                interval_metadata = sequence.interval_metadata
            sequence = sequence._bytes
            self._owns_bytes = False
            self._set_bytes(sequence)
        else:
            # Encode as ascii to raise UnicodeEncodeError if necessary.
            if isinstance(sequence, str):
                sequence = sequence.encode("ascii")
>           s = np.frombuffer(sequence, dtype=np.uint8)
E           TypeError: a bytes-like object is required, not 'int'

../../../miniconda3/envs/latest-skbio/lib/python3.7/site-packages/skbio/sequence/_sequence.py:622: TypeError
```

</details>

**Comment by ebolyen** [comment]
@ElDeveloper, looks like it is just a change from `AttributeError` to `TypeError` from numpy, which makes a lot more sense for the tests involved. I'll have a PR for this shortly.

**Comment by ebolyen** [comment]
Sorry, spoke too soon, not 100% sure what is happening with `FAIL: test_no_variation_pearson (skbio.stats.distance.tests.test_mantel.MantelTests)`, but the sequence ones are straight-forward.

**Comment by ebolyen** [comment]
I am unable to reproduce the last item with:
```
§ conda list pandas
# packages in environment at /home/evan/.conda/envs/test:
#
# Name                    Version                   Build  Channel
pandas                    0.25.3           py37he6710b0_0
(test) 13:32:29 ~/workspace/biocore/scikit-bio@bug-cigar
§ conda list numpy
# packages in environment at /home/evan/.conda/envs/test:
#
# Name                    Version                   Build  Channel
numpy                     1.17.4                   pypi_0    pypi
```
(numpy 1.17.4 isn't on conda yet, but they do note that it needs a new Cython which is perhaps why its being slow to get integrated)

**Comment by tillea** [comment]
On Mon, Nov 18, 2019 at 12:34:50PM -0800, Evan Bolyen wrote:
> I am unable to reproduce the last item with:
> ...
> (numpy 1.17.4 isn't on conda yet, but they do note that it needs a new Cython which is perhaps why its being slow to get integrated)
Do you see any chance to create a virtual machine with Debian unstable?

**Comment by ElDeveloper** [comment]
From looking into this, it seems like an issue associated with the version of SciPy being used. When there's no variance `pearson` can return `0` or `np.nan` depending on the version. 1.3.1 seems to work fine, @tillea what version of scipy are you running?

**Comment by mr-c** [comment]
@ElDeveloper Currently we are at SciPy 1.2.2

**Comment by mr-c** [comment]
We are transitioning to SciPy 1.3.1 as being tracked at https://release.debian.org/transitions/html/auto-python-scipy.html

**Comment by ElDeveloper** [comment]
Thanks for the information. Then it sounds like the solution to this issue is to update the test suite with the new exception classes (as noted by @ebolyen).
