### ISSUE TITLE
Seed in PERMANOVA

### ISSUE THREAD

**Issue by y1zhong** [biocore/scikit-bio#1686]
Is there any seed generator or default value in permanova function to make the significance p-value reproducible?

**Comment by ElDeveloper** [comment]
Yes, you would need to use NumPy's random number generator seeding interface. From the usage examples for ANOSIM [here](http://scikit-bio.org/docs/latest/generated/skbio.stats.distance.anosim.html#skbio.stats.distance.anosim):

```python
from skbio import DistanceMatrix
dm = DistanceMatrix([[0, 1, 1, 4],
                     [1, 0, 3, 2],
                     [1, 3, 0, 3],
                     [4, 2, 3, 0]],
                    ['s1', 's2', 's3', 's4'])
grouping = ['Group1', 'Group1', 'Group2', 'Group2']
```

The seeding is done using NumPy's seed function, and needs to happen before using your test of interest (in your case PERMANOVA):

```python
import numpy as np
# make output deterministic; not necessary for normal use
np.random.seed(0)
from skbio.stats.distance import anosim
anosim(dm, grouping, permutations=99)
```
