### ISSUE TITLE
how to cite

### ISSUE THREAD

**Issue by WSDeWitt** [biocore/scikit-bio#1691]
Hi there! Maybe I missed it, but can you advise on how scikit-bio should be cited in published work (preferably in bibtex format)? As a random example, the JAX package recommends:
```
@software{jax2018github,
  author = {James Bradbury and Roy Frostig and Peter Hawkins and Matthew James Johnson and Chris Leary and Dougal Maclaurin and Skye Wanderman-Milne},
  title = {{JAX}: composable transformations of {P}ython+{N}um{P}y programs},
  url = {http://github.com/google/jax},
  version = {0.1.55},
  year = {2018},
}
```

**Comment by ElDeveloper** [comment]
@WSDeWitt we currently don't have a citation tag for scikit-bio, but you can use this:                                               

```
@software{skbio2020,                                                   
  author = {The scikit-bio development team},                          
  title = {scikit-bio: A Bioinformatics Library for Data Scientists, Students, and Developers},                                                 
  url = {http://scikit-bio.org},                        
  version = {0.5.5},                                                   
  year = {2020},                                                       
}
```

**Comment by vinisalazar** [comment]
Hi @ElDeveloper, I think many users would agree that it would be great to see a DOI-conforming citation (Zenodo maybe?)!

Thank you!

**Comment by hbsmith** [comment]
Hard agree with @vinisalazar, I want to give credit where it's due. 

@ElDeveloper at the very least you should add the citation above to the readme, it took me way too long to find this thread.

**Comment by antgonza** [comment]
Opened this: https://github.com/biocore/scikit-bio/pull/1871
