### ISSUE TITLE
scikit-learn breaks python-skbio autopkgtest: skbio.stats.distance._permdisp.permdisp

### ISSUE THREAD

**Issue by tillea** [biocore/scikit-bio#1693]
Hi,
there was another test suite [error reported in Debian](https://bugs.debian.org/951222) now with the latest upload of scikit-learn.  While you can find the full test log [here](https://ci.debian.net/data/autopkgtest/testing/amd64/p/python-skbio/4266056/log.gz) this might be the relevant extract:

    =================================== FAILURES
    ===================================
    ______________ [doctest] skbio.stats.distance._permdisp.permdisp
    _______________
    129     ...                       ['s1', 's2', 's3', 's4', 's5', 's6'])
    130     >>> grouping = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
    131
    132     Run PERMDISP using 99 permutations to caluculate the p-value:
    133
    134     >>> from skbio.stats.distance import permdisp
    135     >>> import numpy as np
    136     >>> #make output deterministic, should not be included during
    normal use
    137     >>> np.random.seed(0)
    138     >>> permdisp(dm, grouping, permutations=99)
    Differences (unified diff with -expected +actual):
        @@ -4,5 +4,5 @@
         number of groups                 2
         test statistic             1.03296
        -p-value                       0.35
        +p-value                       0.29
         number of permutations          99
         Name: PERMDISP results, dtype: object

Any comment would be helpful.
Kind regards, Andreas.

**Comment by thermokarst** [comment]
Hi @tillea --- our [latest commit(s) on master are testing scikit-bio against scikit-learn 0.22.1](https://travis-ci.org/biocore/scikit-bio/jobs/653522211?utm_medium=notification&utm_source=github_status) and we aren't seeing this error - can you provide more details about the build/test environment that produced this error? Are you still seeing this error?

**Comment by ckastner** [comment]
Here's an odd thing: the relevant code executed manually in a Python shell returns the expected result (p = 0.35), and our build-time tests also pass without issue.

It's our as-installed tests ("autopkgtest", we use it to eg: retest packages anytime a dependency has changed) that fail.

At build time, tests are invoked with `python3 -m pytest`. The failing as-installed tests are invoked with `python3 -m skbio.test`, so presumably there is some kind of setup going on there that affects the tests, although I couldn't find one at first glance.

@thermokarst: can you confirm that your tests against 0.22.1 passed with the `skbio.test` test runner? Or do you have any other idea what could be going on?

**Comment by thermokarst** [comment]
Here is the link to the latest travis run on master:

https://travis-ci.org/github/biocore/scikit-bio/jobs/664032112

Here is the relevant link confirming scikit-learn 0.22.1:

https://travis-ci.org/github/biocore/scikit-bio/jobs/664032112#L508

> Or do you have any other idea what could be going on?

Is it an architecture/precision type of issue? I'm sorry, I'm not much help here...
