### ISSUE TITLE
Can´t install via conda

### ISSUE THREAD

**Issue by DFHydrogeologist** [biocore/scikit-bio#1711]
Hi! I tired to install this package via conda but I got the following error:

PackagesNotFoundError: The following packages are not available from current channels:

  - scikit-bio

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Could you help me? What is the error?

**Comment by mortonjt** [comment]
It has to be from conda forge

conda install scikit-bio -c conda-forge

**Comment by DFHydrogeologist** [comment]
It´s my Python versión (3.7)

**Comment by thermokarst** [comment]
Hi @DFHydrogeologist - there are conda packages for python 3.7 up on conda-forge. What isn't on conda-forge though are packages for win-64, which according to your post above, is what your channels were configured to search for. Hope that helps.
