### ISSUE TITLE
Incompatible with Python 3.8

### ISSUE THREAD

**Issue by michaelsilverstein** [biocore/scikit-bio#1726]
Can't install scikit-bio with Python 3.8:

```
% conda install -c https://conda.anaconda.org/biocore scikit-bio

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - scikit-bio -> python[version='2.7.*|3.4.*|3.5.*|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8

```

Could just require adding `Programming Language :: Python :: 3.8` below? https://github.com/biocore/scikit-bio/blob/06e0b513bfc8ef68e0899596d002b5c112049382/setup.py#L46

**Comment by ElDeveloper** [comment]
I think the problem is the channel you are using. Can you try running: 

```
conda install scikit-bio -c conda-forge
```

I ran this locally in a python 3.8.5 environment and it worked just fine.

**Comment by thermokarst** [comment]
Please see https://anaconda.org/conda-forge/scikit-bio/files for a complete list of package builds, @michaelsilverstein.

**Comment by michaelsilverstein** [comment]
Thanks @ElDeveloper, that worked! May be worth updating scikit-bio homepage with that command as the one list is currently the one I used above: 

![image](https://user-images.githubusercontent.com/22639569/93385254-ff643800-f833-11ea-989b-b843f4b47be2.png)
