### ISSUE TITLE
Patches for pandas 1.1 available from Debian packaging

### ISSUE THREAD

**Issue by tillea** [biocore/scikit-bio#1731]
Hi,
please find a [patch for ordination](https://salsa.debian.org/med-team/python-skbio/-/blob/master/debian/patches/pandas1.1-ordination-fix.patch) and a [patch for value errors](https://salsa.debian.org/med-team/python-skbio/-/blob/master/debian/patches/pandas1.1-valueerror.patch) in the Debian packaging to make scikit-bio compatible with Pandas 1.1.
Hope this helps, Andreas.

**Comment by mr-c** [comment]
Hello @tillea , both of those patches are derived from pull requests that are already merged here.

Therefore this issue can be closed. I've updated the Debian patches to more accurately reflect their provenance.
