### ISSUE TITLE
AttributeError: 'TreeNode' object has no attribute 'to_newick'

### ISSUE THREAD

**Issue by YanaHrytsenko** [biocore/scikit-bio#1732]
I need the newick tree to not contain the distances, and I should be able to do that with the to_newick(with_distances = False, semicolon=True, escape_name=True). 
But I get this error:
AttributeError: **'TreeNode' object has no attribute 'to_newick'**

Here is the code:

```
ids = list('abcde')

#reconstruct phylogeny tree using Neigbour Joining algorithm
dm = DistanceMatrix(distMatrix, ids)
tree = nj(dm)

print(tree.to_newick(with_distances = False, semicolon=True, escape_name=True))
```

**Comment by wasade** [comment]
Hi @YanaHrytsenko, you may be looking at out-dated documentation -- the `to_newick` was deprecated in [0.4.0](https://github.com/biocore/scikit-bio/blob/2b3fada7718c17e1586516eeefbb9e50c016e199/CHANGELOG.md#L621). It doesn't look like `with_distances` is supported by `write`. However, the following should work for you:

```
In [21]: example_tree = skbio.TreeNode.read(["(a:0.1,b:0.2)c;"])

In [22]: str(example_tree)
Out[22]: '(a:0.1,b:0.2)c;\n'

In [23]: no_distances = example_tree.copy()

In [24]: for node in no_distances.traverse():
    ...:     node.length = None
    ...:

In [25]: str(no_distances)
Out[25]: '(a,b)c;\n'
```

It is also possible to use `.write`. The latest Newick IO documentation can be found [here](http://scikit-bio.org/docs/latest/generated/skbio.io.format.newick.html).
