### ISSUE TITLE
New release from master 

### ISSUE THREAD

**Issue by danodonovan** [biocore/scikit-bio#1735]
v0.5.7 🚢 ? 
It would be great if scikit-bio could issue a new release, including changes from https://github.com/biocore/scikit-bio/pull/1690 and https://github.com/biocore/scikit-bio/pull/1728 - as this would fix issues relating to `numpy` pre-installation requirements (cf #1734). 
I see @thermokarst made the last release in March 2020 👍 , would it be possible to release again? thanks 🎉

**Comment by danodonovan** [comment]
Thanks - but this issue is requesting a new release from master, I believe you've linked to a commit. A the time of writing, the last release was v0.5.6 from March 2020 https://github.com/biocore/scikit-bio/releases/tag/0.5.6 - it would be great if v0.5.7 (or higher) could be released and uploaded to PyPI

**Comment by wasade** [comment]
Right, I'm working on finalizing the release

**Comment by wasade** [comment]
@danodonovan, the release is now out on pypi and conda-forge. Thanks for the (incredible) patience!
