### ISSUE TITLE
Error when plotting PCoA results

### ISSUE THREAD

**Issue by asmirn1** [biocore/scikit-bio#1736]
Hi,

I'm getting an error when trying to plot PCoA results. Here is my code

```python
similarities = pd.read_csv('35_matrix.txt', header=0, index_col=0)
metadata = pd.read_csv('35_metadata.txt', header=0)

pcoa_result = pcoa(similarities)
pcoa_result.plot(metadata, 'species', cmap="plasma", title='Studies colored by species', axis_labels=("PC1", "PC2", "PC3"))
```

with these files:
[35_matrix.txt](https://github.com/biocore/scikit-bio/files/5554573/35_matrix.txt)
[35_metadata.txt](https://github.com/biocore/scikit-bio/files/5554574/35_metadata.txt)

When I run the code above, I'm getting error:
> Traceback (most recent call last):
>   File "/Users/aleksandrsmirnov/Projects/du-lab/lc-ms/new script/PCoA_plot.py", line 33, in <module>
>     main()
>   File "/Users/aleksandrsmirnov/Projects/du-lab/lc-ms/new script/PCoA_plot.py", line 26, in main
>     pcoa_result.plot(metadata, 'species', cmap="plasma", title='Studies collored by species',
>   File "/usr/local/lib/python3.9/site-packages/skbio/stats/ordination/_ordination_results.py", line 256, in plot
>     point_colors, category_to_color = self._get_plot_point_colors(
>   File "/usr/local/lib/python3.9/site-packages/skbio/stats/ordination/_ordination_results.py", line 327, in _get_plot_point_colors
>     raise ValueError("One or more IDs in the ordination results "
> ValueError: One or more IDs in the ordination results are not in the data frame, or there is missing data in the data frame's 'species' column.

After debugging the code, I realized that `pcoa` produces a result with indices being strings "0", "1", "2", etc. Therefore, the `metadata` must also have the same indices. So the following code actually works:
```python
similarities = pd.read_csv('35_matrix.txt', header=0, index_col=0)
metadata = pd.read_csv('35_metadata.txt', header=0)

# change the index to string type, because the plot function later we use, it uses index in str type
metadata.rename(index=lambda x: str(x), inplace=True)

pcoa_result = pcoa(similarities)
pcoa_result.plot(metadata, 'species', cmap="plasma", title='Studies colored by species', axis_labels=("PC1", "PC2", "PC3"))
``` 

Although the code works now, the solution wasn't intuitive, and we had to debug the scikit-bio code to figure this out. It would be great to relax this index requirement on the meta data.

**Comment by wasade** [comment]
Hi @asmirn1,

I think `metadata` is missing its index. See below, note that I specified an `index_col` on `35_metadata.txt` parse.

```python
In [12]: import pandas as pd

In [13]: import skbio

In [14]: mat = pd.read_csv('35_matrix.txt', header=0, index_col=0)

In [15]: metadata = pd.read_csv('35_metadata.txt', header=0, index_col=0)

In [16]: dm = skbio.DistanceMatrix(mat.values, mat.index)

In [17]: pc = skbio.stats.ordination.pcoa(dm)
/Users/dtmcdonald/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/skbio/stats/ordination/_principal_coordinate_analysis.py:152: RuntimeWarning: The result contains negative eigenvalues. Please compare their magnitude with the magnitude of some of the largest positive eigenvalues. If the negative ones are smaller, it's probably safe to ignore them, but if they are large in magnitude, the results won't be useful. See the Notes section for more details. The smallest eigenvalue is -0.022348140561834432 and the largest is 4.029764047530317.
  RuntimeWarning

In [18]: pc.plot(metadata, 'species', cmap="plasma", title='Studies colored by species', axis_labels=("PC1", "PC2", "PC3"))
Out[18]: <Figure size 640x480 with 1 Axes>
```

**Comment by asmirn1** [comment]
I tried running your code (in Python)
```python
import pandas as pd
import skbio

mat = pd.read_csv('35_matrix.txt', header=0, index_col=0)

metadata = pd.read_csv('35_metadata.txt', header=0, index_col=0)

dm = skbio.DistanceMatrix(mat.values, mat.index)

pc = skbio.stats.ordination.pcoa(dm)

pc.plot(metadata, 'species', cmap="plasma", title='Studies colored by species', axis_labels=("PC1", "PC2", "PC3"))
```

and got the same error "ValueError: One or more IDs in the ordination results are not in the data frame, or there is missing data in the data frame's 'species' column."

I'm running it under Python 3.9 though. Maybe, that's the problem. Or a different version of pandas.

**Comment by wasade** [comment]
That is unexpected -- I just copyed/pasted that into a new session and it worked without issue. What version of pandas?

**Comment by asmirn1** [comment]
I'm attaching the output of `pip3 freeze`
[packages.txt](https://github.com/biocore/scikit-bio/files/5556020/packages.txt)

The version of pandas is 1.1.4

**Comment by wasade** [comment]
Thanks! I'm having a hard time creating a functional skbio environment using python 3.9.0 and pandas 1.1.4. The latter does not appear available in conda. If dependencies are sourced from pip, I'm unable to finalize the build due to what appears to be cython compilation issues w.r.t. numpy. 

We don't currently test python 3.9 in CI, so I'm unsure of what the support status is. Any chance you could test if you're able to recreate with python 3.6 - 3.8?

**Comment by asmirn1** [comment]
Yes. I can try running Python 3.6. What version of pandas are you using?

**Comment by wasade** [comment]
At the moment, our [described](https://github.com/biocore/scikit-bio/blob/master/setup.py#L120) support is > 1.0.0. Just retried using python 3.6.12 and pandas 1.1.3 (latest in conda)

**Comment by asmirn1** [comment]
Well, I couldn't install Python 3.6, but I tried running the code under Python 3.7 with pandas 1.1.0 and Python 3.8 with pandas 1.1.3. It still gives the same error to me. 

> Traceback (most recent call last):
  File "/Users/aleksandrsmirnov/Projects/du-lab/lc-ms/new script/test.py", line 12, in <module>
    pc.plot(metadata, 'species', cmap="plasma", title='Studies colored by species', axis_labels=("PC1", "PC2", "PC3"))
  File "/Users/aleksandrsmirnov/Projects/du-lab/lc-ms/venv3.7/lib/python3.7/site-packages/skbio/stats/ordination/_ordination_results.py", line 257, in plot
    df, column, self.samples.index, cmap)
  File "/Users/aleksandrsmirnov/Projects/du-lab/lc-ms/venv3.7/lib/python3.7/site-packages/skbio/stats/ordination/_ordination_results.py", line 330, in _get_plot_point_colors
    "column." % column)
ValueError: One or more IDs in the ordination results are not in the data frame, or there is missing data in the data frame's 'species' column.

Maybe the problem is with some other package.

**Comment by wasade** [comment]
I just copied and pasted the code in a py37 environment with pandas 1.1.0 and it works. Is there any chance the `test.py` script differs slightly from what's in the chat history here? 

Going back to the original question, the `OrdinationResults` object has a `samples` member which is a `DataFrame`, indexed by the sample IDs in the input distance matrix. The plot function expects the index of the input metadata to represent a superset of the index elements of the `samples` index. 

I think, in the original example, the underlying issue was that an index was not explicitly set on the metadata so pandas used a default index which is numeric. There may be some data confusion here too as what is being used as indices (via `index_col`) are integer-like, resembling the implicit index that pandas will place on a dataframe in the absence of intentionally setting one.

**Comment by asmirn1** [comment]
@wasade It actually works for me now! You were right about file `35_metadata.txt`. I actually modified that file and was using wrong indices. Sorry about that! After I fixed the index column, it works now.

So the original issue was that I used
```python
mat = pd.read_csv('35_matrix.csv', header=0, index_col=0)
pc = skbio.stats.ordination.pcoa(mat)
```
instead of
```python
mat = pd.read_csv('35_matrix.csv', header=0, index_col=0)
dm = skbio.DistanceMatrix(mat.values, mat.index)
pc = skbio.stats.ordination.pcoa(dm)
```

**Comment by wasade** [comment]
No worries!! We've all been there :) Glad to hear this is resolved!
