### ISSUE TITLE
Error Alignment score and position are not consensus leaves python hanging

### ISSUE THREAD

**Issue by marcpaga** [biocore/scikit-bio#1740]
https://github.com/biocore/scikit-bio/blob/e044f5bfe3712a631f67a710661f0a0294c2eef8/skbio/alignment/_lib/ssw.c#L579-L587

I think that because C makes closes the program and python is not aware of it the program is just left hanging on there, in a jupyter notebook this causes the kernel to be restarted.

Is there a way to avoid the `exit(1)` and throw and error instead that python can catch with `try/except`? I have not found a way around in python and might require the modification of the C code, see: https://stackoverflow.com/questions/1439533/how-to-catch-exit-in-embedded-c-module-from-python-code

Thanks

**Comment by mcouch-lg** [comment]
Why closed? E.g. #1855

**Comment by AFTownsend** [comment]
Why has this been closed? Has it been done?
