### ISSUE TITLE
Potential error in docs page for skbio.stats.composition.ancom

### ISSUE THREAD

**Issue by sbslee** [biocore/scikit-bio#1741]
Hello,

I'm a QIIME 2 user who recently ran the `skbio.stats.composition.ancom()` method. When I was reading the [docs page](http://scikit-bio.org/docs/0.5.0/generated/generated/skbio.stats.composition.ancom.html) for the method, I found this statement under the Notes section:

> The developers of this method recommend the following significance tests ([R60], Supplementary File 1, top of page 11): if there are 2 groups, use the standard parametric t-test (scipy.stats.ttest_ind) or non-parametric Wilcoxon rank sum test (scipy.stats.wilcoxon).

Contrary to what's written above, shouldn't `scipy.stats.wilcoxon()` be replaced with `scipy.stats.mannwhitneyu()` or `scipy.stats.ranksums()` because `scipy.stats.wilcoxon()` will actually perform the Wilcoxon signed-rank test instead of the Wilcoxon rank sum test, as written in its [docs page](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html) in scipy.

Perhpas I'm missing something here, but I thought I would report this.

**Comment by mortonjt** [comment]
Hi @sbslee thank you for raising this issue. I'm ok with changing the skbio documentation to say its a Wilcoxon signed-rank test instead of a rank test.  Would you like to make a contribution a create a pull request?

And to answer your previous question, it is ok to use both `scipy.stats.wilcoxon()` and `scipy.stats.mannwhitneyu()` - the difference here is that `scipy.stats.wilcoxon()`  can handle repeated measures whereas `scipy.stats.mannwhitneyu()` doesn't.

**Comment by sbslee** [comment]
Hi @mortonjt,

Thanks for the reply. And yes, I'll submit a PR for this. Before I do that though:

1. Don't you think changing `scipy.stats.wilcoxon` to `scipy.stats.mannwhitneyu` would make more sense in this case because the sentence ("The developers of this method...") is drawing a comparison between parametric test vs. non-parametric test for two groups of **unrelated** samples? Therefore, the original statement is correct in comparing t-test vs. Wilcoxon rank sum test; we just need to change `scipy.stats.wilcoxon` because this performs Wilcoxon signed-rank test which is a non-parametric test for two groups of **related (or paired) samples** (similar to paired t-test).

2. This question is really for me to better understand the concept at hand: By "... scipy.stats.wilcoxon() can handle repeated measures...", are you implying that `scipy.stats.wilcoxon` can be used for unrelated samples as well as related samples? The [docs page](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html) for the method seems to be clear about this matter:

    > The Wilcoxon signed-rank test tests the null hypothesis that two related paired samples come from the same distribution.

    I always thought the correct comparisons are: `scipy.stats.ttest_ind` (t-test) vs. `scipy.stats.mannwhitneyu` (Wilcoxon rank sum test) and `scipy.stats.ttest_rel` (paired t-test) vs. `scipy.stats.wilcoxon` (Wilcoxon signed-rank test). Please correct me if I'm wrong. Appreciate your time!

**Comment by mortonjt** [comment]
I'd need see the full doc change to make an informed comment -- but at a first glance I think your proposed changes make sense.

**Comment by wasade** [comment]
@mortonjt does these need to be solved or can this issue be closed?
