### ISSUE TITLE
Check that counts are integers in  _validate_counts_vector

### ISSUE THREAD

**Issue by adrianomartinelli** [biocore/scikit-bio#1742]
It is possible to pass non-int values to the Shannon entropy without throwing an error:

```
import skbio.diversity.alpha as skdiv
import numpy as np
counts = [1, 2.2]
skdiv.shannon(counts) # 0.8960
```

The _validate_counts_vector only checks if the numbers are non-negative and real. I suggest one substitutes the check "isreal" with a "is integer" check. 

```
np.issubdtype(np.asarray([1, 2.2]).dtype, np.integer) # false
np.issubdtype(np.asarray([1, 2]).dtype, np.integer) # true
```

**Comment by wasade** [comment]
It's not usual to compute shannon on floating point values. I'm closing as I don't think this is a concern but please reopen if I'm wrong
