### ISSUE TITLE
skbio.stats.distance.DissimilarityMatrix.copy() too slow

### ISSUE THREAD

**Issue by sfiligoi** [biocore/scikit-bio#1745]
DissimilarityMatrix.copy() is extremely slow.
The root cause is the validation performed during the initialization of the class.

However, a copy operation does not need to perform the expensive validation;
the object being copied should already be in a valid state.

I propose to remove validation during the copy stage.
As a side effect, there qill now be the option to disable validation at DissimilarityMatrix (and DistanceMatrix) create, e.g. when the caller has already validate the input data by other means.

**Comment by wasade** [comment]
:+1:

**Comment by wasade** [comment]
Fixed in #1747
