### ISSUE TITLE
BLD/CI: Move to clang from conda 

### ISSUE THREAD

**Issue by wasade** [biocore/scikit-bio#1758]
As [suggested](https://github.com/biocore/scikit-bio/pull/1753#issuecomment-774118381) by @sfiligoi, we should consider moving to clang to benefit cython/optimization work, and which can be sourced from conda.

**Comment by mr-c** [comment]
Was this fixed in https://github.com/biocore/scikit-bio/pull/1756/files ?

**Comment by ElDeveloper** [comment]
Doesn't seem like it, I think clang is only in use for the macOS build. But I could be missing something.

**Comment by sfiligoi** [comment]
Yes, recent builds use clang from conda, as pointed out by @mr-c

**Comment by ElDeveloper** [comment]
Alright, then closing this issue. Thanks both!
