### ISSUE TITLE
FSVD too slow, main compoonent of PCOA

### ISSUE THREAD

**Issue by sfiligoi** [biocore/scikit-bio#1761]
With center_distance_matrix now optimized( #1748 ), FSVD became the leading bottleneck of PCOA.
It takes about 40s on a laptop for EMP sized  (25k^2) matrices.

**Comment by wasade** [comment]
@sfiligoi did you ever resolve this one? 40s isn't *that* bad for 25k samples...

**Comment by sfiligoi** [comment]
Yes, I think I misdiagnosed the problem at  that time.
