### ISSUE TITLE
Malformed TreeNode instantiation can be confusing

### ISSUE THREAD

**Issue by gibsramen** [biocore/scikit-bio#1764]
This came up when I was trying to import a Newick tree - I was trying to instantiate a `TreeNode` object with `skbio.tree.TreeNode(filename)` rather than `skbio.tree.TreeNode.read(filename)`. The former would result in a tree with 0 nodes but I didn't realize until my downstream analyses at which point it was a bit difficult to debug.

Would it be useful to add some sort of warning in the `TreeNode` constructor when this occurs? I'm not experienced with the usage of `TreeNode` for trees not read from an existing file so a base "empty" tree may be useful for situations that don't arise for me.

(I realize this is a case of RTFM so understandable if behavior is unchanged)

## Example

```python
import skbio

with open("tmp.tre", "w") as f:
    f.write("nonsense")
tree = skbio.tree.TreeNode("tmp.tre")  # would expect some sort of warning here
print(tree)
```

## Output

```
<TreeNode, name: tmp.tre, internal node count: 0, tips count: 0>
```

**Comment by wasade** [comment]
Hi @gibsramen, I'm not sure how this could be detected readily. The construction of `skbio.tree.TreeNode("some string")` is how individual nodes (without an edge) are constructed and assigned a `name`. We could potentially force the constructor to use kwargs only, however that would trigger an API change and accordingly, a minor or possibly major bump in version number, as it has a high likelihood of impacting packages which depend on scikit-bio.

**Comment by gibsramen** [comment]
Gotcha - that makes sense. I think switching to kwargs only would be overkill for what is a fairly minor benefit.

**Comment by bkille** [comment]
Perhaps a warning could be issued if `name` matches an existing file on the system?

**Comment by wasade** [comment]
@bkille for large trees that would add an incredible amount of overhead unfortunately
