### ISSUE TITLE
How to perform unifrac on a pruned tree?

### ISSUE THREAD

**Issue by wanglu2014** [biocore/scikit-bio#1792]
We have performed unweighted_unifrac on a sparse dateset, and found only 0 distance. Then, we plan to performed unweighted_unifrac only on most abundant microbe. With skbio, how to filter and performed unifrac on the only most abundant microbe?
Code example： unweighted_unifrac(abun_table.iloc[:,14],abun_table.iloc[:,5], otu_ids, tree)

**Comment by wasade** [comment]
Hi @wanglu2014, it may be easier to do the filter table manipulation described using QIIME 2's [feature-table](https://docs.qiime2.org/2021.11/tutorials/filtering/#filtering-feature-tables) plugin, and it's possible to get a lot of quick help from the QIIME 2 Forum that way as well. The example provided here appears to use the pandas API, and relies on operations performed outside of skbio -- the best source of information there would be the pandas docs for how to manipulate the dataframe to contain the rows and columns desired.
