### ISSUE TITLE
DOC: Documentation does not link back to website/GitHub repo at all

### ISSUE THREAD

**Issue by corneliusroemer** [biocore/scikit-bio#1793]
Just stumbled upon skbio when looking for an alternative to BioPython Phylo with better tree walking methods and it looks good!

Read through the docs and was surprised to find no way to get to GitHub.

I completely missed the homepage: http://scikit-bio.org/ because there is no link from the docs back up. Very undiscoverable website which is a shame!

Google also landed me on version 0.4.1 of the docs and there was no indication this wasn't latest nor was there a way to get to the latest version.

Possible Improvements:
- Include link to homepage/start page in docs website (menu/footer)
- Include link to latest version of docs in docs website
- Include link to GitHub in docs website

**Comment by thermokarst** [comment]
Hi there @corneliusroemer! Thanks for submitting this issue.

> Read through the docs and was surprised to find no way to get to GitHub.

> Include link to GitHub in docs website

I have highlighted the relevant link, below:

![image](https://user-images.githubusercontent.com/274668/149352462-1282a5c1-7aa2-4b71-b8bd-2bf85e9020cb.png)

> I completely missed the homepage: http://scikit-bio.org/ because there is no link from the docs back up

> Include link to homepage/start page in docs website (menu/footer)

I have highlighted the relevant link, below:

![image](https://user-images.githubusercontent.com/274668/149352638-8f415017-1396-4c8d-9ba7-7b6e01e228d3.png)

> Include link to latest version of docs in docs website

I have highlighted the relevant link, below:

![image](https://user-images.githubusercontent.com/274668/149353198-6b67f87a-68ad-436a-a9b2-ed9bd6a5d698.png)

> Google also landed me on version 0.4.1 of the docs

Strange, maybe you clicked on an old link somewhere, perhaps on a forum or discussion board? There isn't a ton we can do there, but perhaps we could add a robots.txt?

I hope that helps clear things up a bit.

**Comment by corneliusroemer** [comment]
Sorry, I didn't express myself as well as I should have and didn't add screenshots because I was on my phone.

This is the docs sub-website I meant which doesn't link back up: http://scikit-bio.org/docs/0.5.6/index.html

The Github link is not visible on mobile, the banner only appears above a certain screen width.

![image](https://user-images.githubusercontent.com/25161793/149357652-3be2005a-cd51-4e10-a4f6-023f804a131b.png)

I found a previous report of the same issue here https://github.com/biocore/scikit-bio/issues/1434

The robots txt thing has been mentioned before: https://github.com/biocore/scikit-bio/issues/1516

I'm rediscovering the wheel ;)

**Comment by thermokarst** [comment]
Great, closing in favor of those pre-existing issues. Let's continue any relevant discussion there.
