### ISSUE TITLE
SIMD Everywhere commit (b470a55) breaks build on Windows

### ISSUE THREAD

**Issue by theAeon** [biocore/scikit-bio#1796]
Running setup.py on windows 10 x64 halts on line 91 of setup.py with a KeyError. As far as I can tell, the setup script is trying to look up a config variable with `sysconfig.get_config_vars()['CC']` that does not exist on windows, causing an unhandled exception. Should be a quick patch.

**Comment by wasade** [comment]
@theAeon with #1797 and 1798 merged, can you check if this issue is now resolved?

**Comment by theAeon** [comment]
Well, they were my PRs, I know for a fact they resolve it haha

**Comment by wasade** [comment]
:) great thanks
