### ISSUE TITLE
specified SciPy requirements don't work with latest SciPy

### ISSUE THREAD

**Issue by ajtritt** [biocore/scikit-bio#1822]
# Problem

`setup.py` has a minimum requirement of 1.3:
https://github.com/biocore/scikit-bio/blob/541498807b67554353fc8aeb65bb66c28966a1f6/setup.py#L155

The `skbio.stats.distance` subpackage uses function specific warnings from scipy: 
https://github.com/biocore/scikit-bio/blob/master/skbio/stats/distance/_mantel.py#L16-L18

And those warnings have been removed starting in scipy 1.9.0
https://docs.scipy.org/doc/scipy/release.1.9.0.html#backwards-incompatible-changes

The practical implications of this are that pip installs no longer work without restricting the scipy version.

**Comment by SilasK** [comment]
Should be fixed with #1821

**Comment by ajtritt** [comment]
Closing this since #1818 already addresses it
