### ISSUE TITLE
Unable to install scikit-bio in docker container

### ISSUE THREAD

**Issue by baireddy417** [biocore/scikit-bio#1823]
I was trying to create a docker image with python 3.7.10 version with numpy, SciPy, pandas, scikit-bio as my pip packages but I was facing some Cython issues, pasted the logs below. Can you please help me on how to resolve it
#13 21.62 Collecting scikit-bio
#13 21.62   Downloading scikit-bio-0.5.7.tar.gz (8.7 MB)
#13 21.62      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 5.3 MB/s eta 0:00:00
#13 21.62   Installing build dependencies: started
#13 21.62   Installing build dependencies: finished with status 'done'
#13 21.62   Getting requirements to build wheel: started
#13 21.62   Getting requirements to build wheel: finished with status 'error'
#13 21.62 
  error: subprocess-exited-with-error
#13 21.62   
#13 21.62   × Getting requirements to build wheel did not run successfully.
#13 21.62   │ exit code: 1
#13 21.62   ╰─> [44 lines of output]
#13 21.62       /tmp/pip-build-env-8kxe2khj/overlay/lib/python3.7/site-packages/Cython/Compiler/Main.py:345: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-vhkanq4p/scikit-bio_f6b22aea74a84eb9bc798fe2103acefb/skbio/alignment/_ssw_wrapper.pyx
#13 21.62         tree = Parsing.p_module(s, pxd, full_module_name)
#13 21.62       
#13 21.62       Error compiling Cython file:
#13 21.62       ------------------------------------------------------------
#13 21.62       ...
#13 21.62               else:
#13 21.62                   matrix = self._convert_dict2d_to_matrix(substitution_matrix)
#13 21.62               # Set up our mask_length
#13 21.62               # Mask is recommended to be max(query_sequence/2, 15)
#13 21.62               if mask_auto:
#13 21.62                   self.mask_length = len(query_sequence) / 2
#13 21.62                                                          ^
#13 21.62       ------------------------------------------------------------
#13 21.62       
#13 21.62       skbio/alignment/_ssw_wrapper.pyx:584:51: Cannot assign type 'double' to 'int32_t'
#13 21.62       Compiling skbio/metadata/_intersection.pyx because it changed.
#13 21.62       Compiling skbio/stats/__subsample.pyx because it changed.
#13 21.62       Compiling skbio/alignment/_ssw_wrapper.pyx because it changed.
#13 21.62       Compiling skbio/diversity/_phylogenetic.pyx because it changed.
#13 21.62       Compiling skbio/stats/ordination/_cutils.pyx because it changed.
#13 21.62       Compiling skbio/stats/distance/_cutils.pyx because it changed.
#13 21.62       [1/6] Cythonizing skbio/alignment/_ssw_wrapper.pyx
#13 21.62       Traceback (most recent call last):
#13 21.62         File "/root/.local/share/virtualenvs/my-project-nllx_0AM/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#13 21.62           main()
#13 21.62         File "/root/.local/share/virtualenvs/my-project-nllx_0AM/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#13 21.62           json_out['return_val'] = hook(**hook_input['kwargs'])
#13 21.62         File "/root/.local/share/virtualenvs/my-project-nllx_0AM/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
#13 21.62           return hook(config_settings)
#13 21.62         File "/tmp/pip-build-env-8kxe2khj/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
#13 21.62           return self._get_build_requires(config_settings, requirements=['wheel'])
#13 21.62         File "/tmp/pip-build-env-8kxe2khj/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
#13 21.62           self.run_setup()
#13 21.62         File "/tmp/pip-build-env-8kxe2khj/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 483, in run_setup
#13 21.62           self).run_setup(setup_script=setup_script)
#13 21.62         File "/tmp/pip-build-env-8kxe2khj/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
#13 21.62           exec(code, locals())
#13 21.62         File "<string>", line 130, in <module>
#13 21.62         File "/tmp/pip-build-env-8kxe2khj/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1129, in cythonize
#13 21.62           cythonize_one(*args)
#13 21.62         File "/tmp/pip-build-env-8kxe2khj/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1296, in cythonize_one
#13 21.62           raise CompileError(None, pyx_file)
#13 21.62       Cython.Compiler.Errors.CompileError: skbio/alignment/_ssw_wrapper.pyx
#13 21.62       [end of output]
#13 21.62   
#13 21.62   note: This error originates from a subprocess, and is likely not a problem with pip.
#13 21.62 error: subprocess-exited-with-error
#13 21.62 
#13 21.62 × Getting requirements to build wheel did not run successfully.
#13 21.62 │ exit code: 1
#13 21.62 ╰─> See above for output.
#13 21.62 
#13 21.62 note: This error originates from a subprocess, and is likely not a problem with pip.
#13 21.62 
#13 21.65✘ Installation Failed 
------
executor failed running [/bin/sh -c pipenv install scikit-bio]: exit code: 1
make: *** [build] Error 1

**Comment by gregcaporaso** [comment]
@baireddy417, I don't have a solution for you unfortunately, but just FYI the skbio functionality that requires Cython (and is therefore indirectly causing this issue) is deprecated and will be removed in the next release of scikit-bio (https://github.com/biocore/scikit-bio/issues/1814). That release is planned for this month or next.

**Comment by ebolyen** [comment]
This issue seems to be because the language_level of the Cython compiler is 3x instead of 2x in your example.

For what it's worth, I believe that the default has been changed back to 2x in the latest Cython.

Another workaround is to not use Cython here and just compile the distributed C code.
If you omit the `USE_CYTHON` env var, then Cython won't recompile the code.

**Comment by pratyushmohitkommalapati** [comment]
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
numpy = "==1.21.6"
pandas = "==1.3.5"
scipy = "==1.7.3"
statsmodels = "==0.13.2"
scikit-posthocs = "==0.7.0"
rpy2 = "==3.5.6"
typeguard = "==2.13.3"
scikit-bio = "==0.5.7"
```

Above is the Pipfile we are using to generate a Pipfile.lock through pipenv. However, we are facing the same issue with cython. Could you please let me know how to set the env variable `USE_CYTHON` as false through the terminal?

**Comment by baireddy417** [comment]
@ebolyen, Even after setting USE_CYTHON env variable to False the issue is occuring. if i wish to migrate to version 0.5.8, it has pandas dependency of 1.5.0 which requires python 3.8 or above and iam currently working with python 3.7. can you tell me how to proceed
