### ISSUE TITLE
TreeNode.read unexpectedly slow

### ISSUE THREAD

**Issue by sjanssen2** [biocore/scikit-bio#1825]
I am noticing since years that `TreeNode.read()` has very different execution times on basically the same trees - one version is directly generated by Qiita (deblur reference hit table (ID: 158540)) [158540_insertion_tree.relabelled.tre.zip](https://github.com/biocore/scikit-bio/files/10021456/158540_insertion_tree.relabelled.tre.zip) - note you have to extract it from the zipped version), the other 
[sepp.nwk.zip](https://github.com/biocore/scikit-bio/files/10021466/sepp.nwk.zip) tree is generated for the same study, but through a wrapper of the SEPP python package: https://github.com/sjanssen2/ggmap/blob/465995e936497b525a7bfc721c092c5bdb46db52/ggmap/analyses.py#L856

I have not yet systematically checked that, but want to use this issue to collect evidence. You might want to add your observations as well?

I am using `scikit-bio-0.5.6`, the Qiita artefact has been generated today (Nov 16th 2022)

```
Python 3.9.15 (main, Nov  4 2022, 16:13:54) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.6.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from timeit import default_timer as timer
In [2]: from skbio.tree import TreeNode
In [3]: import sys
In [4]: start = timer()
    ...: t_sepp = TreeNode.read('sepp.nwk')
    ...: end = timer()
    ...: walltime = end - start
    ...: print('loading took actually %.1f minutes.' % (walltime / 60), file=sys.stderr)
loading took actually 0.2 minutes.

In [14]: start = timer()
    ...: t_sepp = TreeNode.read('158540_insertion_tree.relabelled.tre')
    ...: end = timer()
    ...: walltime = end - start
    ...: print('loading took actually %.1f minutes.' % (walltime / 60), file=sys.stderr)
loading took actually 14.6 minutes.
```

|    |      Qiita      |  SEPP |
|----------|:-------------:|------:|
| str |  <TreeNode, name: unnamed, internal node count: 258878, tips count: 258880> | <TreeNode, name: unnamed, internal node count: 258876, tips count: 258880> |
| # unique tip names | 258880 | 258880 |
| # tips with `None` name | 0 | 0 |

against my intuition, not all tips are identical. The reference OTU `4259390` comes with slightly different branch lengths `0.000001` vs `0.000000572949`, six AVS tips also come with differences within rounding issues, but 160 ASV tips have `0.0` branch length in the SEPP tree, VS some positive numbers in the Qiita tree?!

**Comment by mortonjt** [comment]
Hi Stefan, if you are loading large trees, it maybe worth looking into
https://github.com/biocore/improved-octo-waddle/blob/master/ipynb/performance%20comparison.ipynb

The read time is easily >100x faster

**Comment by sjanssen2** [comment]
forget the above examples, trees are more different than I thought. However, the observation persists and I think it has something to do with node names.
Here is a sub-tree from Qiita (all below `p__Bacteroidetes`: `<TreeNode, name: p__Bacteroidetes, internal node count: 32234, tips count: 32236>`) [qiita_sub.nwk.zip](https://github.com/biocore/scikit-bio/files/10022273/qiita_sub.nwk.zip) and the same sub-tree after replacing `;`, `[`, `]`, ` ` within node names and removing `' ` afterwards: [qiita_sub_escaped.nwk.zip](https://github.com/biocore/scikit-bio/files/10022283/qiita_sub_escaped.nwk.zip)

The escaped tree loads approx. 5 times faster (1.86 vs. 9.55 seconds)

**Comment by sjanssen2** [comment]
> Hi Stefan, if you are loading large trees, it maybe worth looking into https://github.com/biocore/improved-octo-waddle/blob/master/ipynb/performance%20comparison.ipynb The read time is easily >100x faster
very cool! Thanks. Not sure if I can seamlessly replace code, though.

**Comment by sjanssen2** [comment]
wow, it looks like it makes a huge difference if I either use `from skbio.io.format.newick import _newick_to_tree_node` or `TreeNode.read`?! 
![image](https://user-images.githubusercontent.com/11960616/202208020-f7762aaf-8fa1-4b10-b713-2c67aa8c4a38.png)

**Comment by sjanssen2** [comment]
it is the missing format information! When providing the format, everything is up to speed:
![image](https://user-images.githubusercontent.com/11960616/202211161-18e5b654-edbc-4135-a7e3-4d1593d74850.png)

**Comment by sjanssen2** [comment]
profiling shows that "sniffing" e.g. for csv takes a long time:
`1    0.000    0.000    0.498    0.498 csv.py:176(sniff)` for `qiita_sub_escaped.nwk` vs.
`1    0.000    0.000    7.792    7.792 csv.py:176(sniff)` for `qiita_sub_quotes.nwk`

```
import cProfile
cProfile.run('TreeNode.read(\'qiita_sub_escaped.nwk\')')
cProfile.run('TreeNode.read(\'qiita_sub_quotes.nwk\')')
```

**Comment by wasade** [comment]
@sjanssen2, with `bp` you can do `sktree = bp.to_skbio_treenode(bp.parse_newick(open('foo').read()))` and it will be substantially faster than the present skbio parser

**Comment by wasade** [comment]
That is a great observation on the need for `format='newick'` here! Good find. 

@ebolyen, can the readers default to an expected format type? I think `TreeNode` almost universally uses `newick` for example

**Comment by ebolyen** [comment]
I don't think the readers have any way of doing that, but it's a good idea. 
Or perhaps the set of valid sniffers could be constrained when the constructor is known.

**Comment by ebolyen** [comment]
Created a new issue #1834 to track the general problem of rogue sniffers.
