### ISSUE TITLE
Need a new release to address dependency problems

### ISSUE THREAD

**Issue by sfiligoi** [biocore/scikit-bio#1828]
The current version of skbio (0.5.7) has at least one known problem (#1818) that makes it unusable out of the box in the conda install.
The problem has been fixed in master, but that does not help until a new version is released.

**Comment by sfiligoi** [comment]
CC @wasade

**Comment by ebolyen** [comment]
We're working on it, we've got a short todo-list of things to clean up first, but a release will follow shortly after. (Ideally before the next QIIME 2 release.)

**Comment by ebolyen** [comment]
Fixed by 0.5.8.
