### ISSUE TITLE
Numpy 1.24 issues

### ISSUE THREAD

**Issue by tillea** [biocore/scikit-bio#1839]
Hi,
Debian migrated to numpy 1.24 and we developed some [patch](https://salsa.debian.org/med-team/python-skbio/-/blob/master/debian/patches/numpy-1.24.patch) which worked to let all test of the scikit-bio test suite pass.  Its kind of a hack and we would like you to comment on this.  Some confirmed solution from your side to work with numpy 1.24 properly would be welcome.
Kind regards, Andreas.

**Comment by ebolyen** [comment]
Welcome back @tillea :)

That looks quite fine to me to be honest. It looks like the numpy constructor has just become more strict with it's dtype inference, the changes listed seem like they preserve the semantics that had existed before.

I suspect this is also backwards compatible with older versions of numpy, so I would be happy to merge a PR with that changeset.

**Comment by tillea** [comment]
Am Wed, Jan 25, 2023 at 09:42:56AM -0800 schrieb Evan Bolyen:
> Welcome back @tillea :)
:-)

> That looks quite fine to me to be honest. It looks like the numpy constructor has just become more strict with it's dtype inference, the changes listed seem like they preserve the semantics that had existed before.
Thanks for confirming.

> I suspect this is also backwards compatible with older versions of numpy, so I would be happy to merge a PR with that changeset.
I'd be happy if you save me the work to create a PR and simply use

    patch -p1 < downloaded_patch

Hope this helps, Andreas.

**Comment by ebolyen** [comment]
Sounds good, thanks @tillea.

**Comment by wasade** [comment]
@ebolyen can this be closed?

**Comment by tillea** [comment]
Am Tue, May 02, 2023 at 04:49:35PM -0700 schrieb Daniel McDonald:
> @ebolyen can this be closed?

Since the patch worked for me and you confirmed its OK I think it can be closed.  It might be sensible to tag a bugfix release, thought.
Kind regards, Andreas.

**Comment by wasade** [comment]
Thanks, @tillea! We are getting a maintenance release organized right now.
