### ISSUE TITLE
Inconsistent root handling in descending_branch_length

### ISSUE THREAD

**Issue by havranej** [biocore/scikit-bio#1847]
Hello everyone!

I have noticed inconsistent handling of root length in the `skbio.tree.TreeNode.descending_branch_length` function. According to the documentation, the root length is ignored, but that is not true if the `tip_subset` parameter is not set:

```
from six import StringIO
from skbio import TreeNode

# Example tree from the documentation
test_tree = TreeNode.read(StringIO("(((A:.1,B:1.2)C:.6,(D:.9,E:.6)F:.9)G:2.4,(H:.4,I:.5)J:1.3)K;"))

test_tree.descending_branch_length()
# Returns 8.9

# Assign length to the root
test_tree.length = 1
test_tree.descending_branch_length()

# Returns 9.9
```

If `tip_subset` is passed, everything works as documented:

```
test_tree.descending_branch_length([t.name for t in test_tree.tips()])
# Returns 8.9
```

Looking at the code, this seems to be easily fixable, but decision needs to be taken on which behavior is the desired one.

Cheers,
Jan

**Comment by wasade** [comment]
Thanks @havranej, good find!
