### ISSUE TITLE
CCA - Correlations of environmental variables with site scores

### ISSUE THREAD

**Issue by ForTozs** [biocore/scikit-bio#285]
I am very excited about and grateful for this new project. I have been experimenting with canonical correlation analysis (skbio.maths.stats.ordination.cca) and the results look great. One thing I noticed is that it does not display the correlations of variables with site scores (for biplots, or not, or centroids for binary variables). Is this something that plans to be added in the future, or is there already a way to calculate these easily from the matrices? Anyway, I look forward to the future of this project.

**Comment by ebolyen** [comment]
Fixed in #298
