### ISSUE TITLE
what does QIIME import from PyCogent? these are priorities for clean-up and port to bipy, imo

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#39]

**Comment by mortonjt** [comment]
Is there still an interest to have `upgma`?

**Comment by ebolyen** [comment]
No, SciPy already implements it as [`scipy.cluster.hierarchy.average`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.average.html). Additionally QIIME's UPGMA is actually subtly incorrect, we explored this early on in the beginning of skbio: https://github.com/biocore/qiime/issues/1541.

**Comment by mortonjt** [comment]
Ahhh, I did not see [`TreeNode.from_linkage_matrix`](https://github.com/biocore/scikit-bio/blob/master/skbio/tree/_tree.py#L1930).  Thanks!!!
