### ISSUE TITLE
ASCII art displays incorrectly in scikits.appspot.com

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/scikit-bio#400]
https://scikits.appspot.com/scikit-bio

![screen shot 2014-05-17 at 3 22 16 pm](https://cloud.githubusercontent.com/assets/375307/3113562/6bbd6448-e6db-11e3-8273-485074576600.png)

**Comment by ebolyen** [comment]
We should probably replace the ascii in the readme with our actual logo, now that we have one. @johnchase Would you be up for doing this? The logo on the front of our homepage should work fine for this.

**Comment by ElDeveloper** [comment]
But `ASCII >> graphics`.

**Comment by ebolyen** [comment]
True, but `logo ⊆ professional packages`

**Comment by jairideout** [comment]
:+1: I think having the ASCII art in `skbio.__init__` makes sense, but we should use our logo on the web.

**Comment by ElDeveloper** [comment]
:+1: (but at heart I :-1: this change :P).

**Comment by johnchase** [comment]
So we are at a consensus that the logo is going to be the actual graphic and not the ASCII art? If so I will make that change.

**Comment by ElDeveloper** [comment]
Yes, you are right @johnchase!
