### ISSUE TITLE
error: command 'i686-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by raivivek** [biocore/scikit-bio#409]
Hi,

I tried to install scikit-bio from the latest branch but the build failed. The build log is shown in the gist.

https://gist.github.com/vivekiitkgp/a600adb5c008d2af6a3d

**Comment by MikeTrizna** [comment]
I ran into a lot of trouble with trying to install scikit-bio on my Windows 7 work computer recently. The fix finally came when I commented out the line in setup.py:
```python
if platform.machine() == 'i686':
```
I have 32-bit Python 2.7.6 installed and using mingw32's version of g++ to compile python libaries, but my computer reports platform.machine() to be "AMD64", so the -msse2 flag was skipped during install. You can see that I am running 32-bit Python using platform.architecture(), but I don't know how to identify that my version of g++ is 32-bit.

**Comment by jairideout** [comment]
Thanks for reporting this issue @MikeTrizna! I'll reopen this issue so someone can work on a fix.
