### ISSUE TITLE
test use of numpy array instead of str for storing BiologicalSequence._sequence

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#60]
Suggested by @wasade. I did some initial testing, and it shouldn't be hard to make this change. See discussion on #53, but in particular:

https://github.com/biocore/bipy/pull/53#discussion-diff-9160149
https://github.com/biocore/bipy/pull/53#discussion-diff-9171472

**Comment by jairideout** [comment]
Fixed in #920. Still more performance benchmarking and improvements to make (part of the upcoming sprint's goals) but `ndarray` is used internally in `Sequence` objects now.
