### ISSUE TITLE
update BiologicalSequence.k_words to return SequenceCollection

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#669]
@ebolyen suggested updating `BiologicalSequence.k_words` to return a `SequenceCollection` instead of yielding sequences. Once `SequenceCollection` is lazy, this will be even more powerful. 

`SequenceCollection` would then have `counts` and `frequencies` methods to provide the current functionality in `BiologicalSequence.k_word_counts` and `BiologicalSequence.k_word_frequencies` (those methods could be left in place for convenience/backwards-compatibility though).

**Comment by ebolyen** [comment]
SequenceCollection no longer exists #1220
