### ISSUE TITLE
make scikit-bio classes plottable

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#685]
`A user calls the plot method on an object to easily visualize their data.`

Add `plot` methods to the following scikit-bio classes (the type of plot will depend on the class):
- [x] `skbio.stats.distance.DissimilarityMatrix`: #684
- [ ] `skbio.tree.TreeNode`: #531
- [ ] `skbio.alignment.Alignment`
  - [ ] heatmap: #765 
  - [ ] sequence logo: #805 

Each `plot` method should return a matplotlib `Figure` object. Each class should also have `png` and `svg` properties and `_repr_png_` and `_repr_svg_` methods for IPython Notebook integration. See [`skbio.stats.ordination.OrdinationResults`](https://github.com/biocore/scikit-bio/blob/master/skbio/stats/ordination/_base.py#L30) for an example of a class that has plotting capabilities.

Will continue to add classes to this list. Related to (and partially addresses) #656.

Will assign to @Kleptobismol once he's a member of the biocore organization.

Dependencies:
- [ ] TreeNode Refactor (#809)
- [ ] Refactor Alignment (#823)

**Comment by mortonjt** [comment]
I've been experimenting with compositional biplots.  They are actually a quite powerful hypothesis driving tools and can give much information about correlations between OTUs and their relationships to their respective samples.

I've prototyped a basic version [here](https://github.com/mortonjt/ANCOM/blob/master/ancom/plot/biplot.py)

I got the original idea from [here](http://okomestudio.net/biboroku/?p=2292)

If you think it is a good idea, perhaps we can add this as an additional plotting method.

**Comment by gregcaporaso** [comment]
> I've been experimenting with compositional biplots

@mortonjt, these might be more appropriate to add to Emperor. This is really useful functionality, and the plotting function in scikit-bio is intended to be primarily for quick/basic visualization. What do you think?

cc @ElDeveloper @antgonza

**Comment by antgonza** [comment]
100% agree! This should be in Emperor. We have some open issues:
https://github.com/biocore/emperor/issues/275
https://github.com/biocore/emperor/issues/75, talking about similar
functionality. Also in the past we have talked about not only biplots
(environmental or OTU contributions) but triplots (both of those).

**Comment by Jorge-C** [comment]
It seems they're both somehow orthogonal. For example, the triangle at the top is an example of a ternary plot that @mortonjt mentioned as a Compositional Data analysis method:
![Ternary plot, from Distinct and diverse anaerobic bacterial communities in boreal lakes dominated by candidate division OD1. Sari Peura, Alexander Eiler, Stefan Bertilsson, Hannu Nykänen, Marja Tiirola and Roger I Jones](http://www.nature.com/ismej/journal/v6/n9/images/ismej201221f4.jpg)

==

Also, I think that having simple, static but actual triplots like this
![Triplot, from canodraw ](http://www.canodraw.com/triplot.png)
in skbio is *fundamental*, as our current ordination methods are not very useful: they can't be visualized (and a scatter plot is not enough) so people not only use R to do visualize them (and to be fair, it's possible to get gorgeous plots that way), they directly compute them there and thus don't even use skbio at all.

**Comment by antgonza** [comment]
I think these should live and be maintained in Emperor as you do not
want to support all these plotting functionalities in skbio. Note that
a user can simply generate the raw files in skbio and them use Emperor
to plot, which is also pip installable.

Here is a related discussion on this topic:
https://github.com/biocore/scikit-bio/pull/637

**Comment by mortonjt** [comment]
I think making 3D plots in Emperor is a great idea.  However, I'm not sure how well it will fit in the framework right now.

* The biplots I had in mind are completely different from the PCoA plots typically made in Emperor. 
* A number of steps need to be performed before creating these biplot namely a zero imputation, log transformation and a SVD.  This issues have been addressed in https://github.com/biocore/scikit-bio/issues/835
* Expanding ternary plots to tetrahedron plots in Emperor would be awesome.

Because a number of tools need to be developed before making these plots, I still agree with @Jorge-C .  At the very least, I think it would be a good idea to port these backend tools into skbio.

**Comment by Jorge-C** [comment]
Yes, they way I see it is as a symbiosis: Emperor is great for 3D, interactive exploratory analysis, it can make movies, you just need a browser, it's super responsive... and of course "the state of the art for analyzing N-dimensional data using principal coordinates analysis" (quoting home page). These would be static 2D plots that are different from the usual PCoA plots in Emperor, as @mortonjt mentioned.

**Comment by antgonza** [comment]
Why not make it 3D so they look more impressive? Additionally, this
will make the support of plotting/labeling/coloring/etc not part of
skbio. Seems like a lot of effort to support 2 plotting libraries.

BTW Emperor can work with other MDS methods not only PCoA and you
should be able to generate an Emperor plot really easy from the python
or ipython terminal once you have the objects.

**Comment by mortonjt** [comment]
Developing the biplot code won't be hard at all - I have it written up and with a little polishing, it is ready go!  

But I am definitely down to make 3D biplots in Emperor. My main concern is the backend tools required to generate these biplots.  I don't think it would be wise to include specialized compositional SVD methods and zero imputative methods into Emperor.

**Comment by ElDeveloper** [comment]
Emperor uses and depends on skbio, so if skbio can perform the
computations, Emperor can simply make use of it.

**Comment by rob-knight** [comment]
Yes the code and presentation layers should be separate.


On Feb 13, 2015, at 4:38 PM, mortonjt <notifications@github.com<mailto:notifications@github.com>> wrote:


Developing the biplot code won't be hard at all - I have it written up and with a little polishing, it is ready go!

But I am definitely down to make 3D biplots in Emperor. My main concern is the backend tools required to generate these biplots. I don't think it would be wise to include specialized compositional SVD methods and zero imputative methods into Emperor.

**Comment by antgonza** [comment]
Agree, it will be only the display.

**Comment by gregcaporaso** [comment]
@mortonjt, @Jorge-C we had some offline discussion about this and concluded that you should add the plotting functions in sckit-bio. It will be fantastic to also have these in Emperor (but not a pre-requisite to adding to scikit-bio). Thanks, and sorry for the slow reply on this.

**Comment by mortonjt** [comment]
Awesome!  I'll revive this issue once we have a functional contingency table added.  Constructing these biplots will require additional functionality (aka. zero imputation and clr transform)

**Comment by rob-knight** [comment]
Great — thanks! Will be very useful; as you’ve been discussing with Antonio, adding the functionality to emperor in 3d would also be awesome!


On Feb 19, 2015, at 11:07 AM, mortonjt <notifications@github.com<mailto:notifications@github.com>> wrote:


Awesome! I'll revive this issue once we have a functional contingency table added. Constructing these biplots will require additional functionality (aka. zero imputation and clr transform)

**Comment by mortonjt** [comment]
@gregcaporaso reopen if this hasn't been addressed

**Comment by sawezo** [comment]
Was the biplot code ever released?
