### ISSUE TITLE
io should support reading and writing gzip for all supported file formats

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#690]

**Comment by ebolyen** [comment]
Add URL support too!

**Comment by jrderuiter** [comment]
Any eta on this?

**Comment by ebolyen** [comment]
@jrderuiter Not a solid one at this time, but it is a very simple addition to make. This can be achieved very similarly to #903. (Waiting for #903 to be merged would be a good idea). I am sure one of use will get around to this soon, but if you are interested in contributing this change, we would be happy to help you get started!

**Comment by jrderuiter** [comment]
@ebolyen I think I have working version now (need to test it some more). I will wait on the #903 being merged first and then open a pull request if all is working.

**Comment by ebolyen** [comment]
That's really exciting @jrderuiter! Hopefully #903 will get merge very soon (just waiting on some doc updates).

**Comment by jairideout** [comment]
Fixed in #963.
