### ISSUE TITLE
port PD and unweighted unifrac python implementations from cookbook

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#730]
See [this recipe](http://nbviewer.ipython.org/github/biocore/scikit-bio-cookbook/blob/master/phylogentic-diversity-calculations.ipynb). Longer-term goal is that we should have C implementations as well, and calling these would give an ``EfficencyWarning``.

**Comment by jairideout** [comment]
Closing in favor of #822.
