### ISSUE TITLE
subsample isn't fast for very small tables

### ISSUE THREAD

**Issue by Jorge-C** [biocore/scikit-bio#758]
See QIIME issue https://github.com/biocore/qiime/issues/1710.

**Comment by wasade** [comment]
I don't believe this is still an issue. Subsample is presently cythonized following the pattern used in biom. The known bottlenecks are hard: the approach to jackknifing requires allocating sum(vec) bytes which can be large if the depth of vec is high, and second, calls to random number generators are slow and difficult to parallelize.
