### ISSUE TITLE
Required and recommended dependencies

### ISSUE THREAD

**Issue by dansondergaard** [biocore/scikit-bio#760]
Would it be possible to make scipy and matplotlib non-mandatory dependencies? There are a huge bunch of use cases where none of them are necessary (reading and writing various file formats, e.g. FASTA) and in those cases it seems wasteful to have to install/compile scipy and matplotlib in e.g. Docker images.

There could be required and recommended dependencies, and the packages using an unavailable recommended dependency could just raise an exception.

Thank you for building scikit-bio!
- Dan

**Comment by dansondergaard** [comment]
Unfortunately I don't have the time to look at this. Busy with teaching/work, so if anybody else wants it, it's up for grabs :)

**Comment by jvkersch** [comment]
Just wanted to chime in on this: we're currently using skbio on a headless box and getting matplotlib to run means installing a bunch of otherwise unneeded X libraries. I saw PR #886 and this would help our usecase along quite a bit --- is there anything I can do to help this get in?

**Comment by dansondergaard** [comment]
This is no longer relevant to me so I'll close the issue.
