### ISSUE TITLE
Determining number of tips descended from a TreeNode

### ISSUE THREAD

**Issue by dparks1134** [biocore/scikit-bio#763]
TreeNode has no function for reporting the number of tips (leaves) below it. This can be determined be iterating over all the tips with TreeNode.tips(), but this seems awkward for such a common operation.

**Comment by anderspitman** [comment]
Is this really that common? A quick search doesn't show this functionality available in NetworkX. There's a been a lot of talk lately about switching TreeNode to use NetworkX internally.

**Comment by dparks1134** [comment]
This functionality can be obtained with TreeNode.count(tips=True).

**Comment by anderspitman** [comment]
Ah cool, thanks. Good to know.
