### ISSUE TITLE
add option to FASTA reader to ignore blank/whitespace-only lines

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#781]
Would be useful to add an option to the FASTA reader to ignore blank/whitespace-only lines.

**Comment by jairideout** [comment]
This change should happen with the FASTQ parser too.

**Comment by ebolyen** [comment]
Some unit tests that definitely should exist for this functionality:

 * The case where an empty line occurs in the middle of a record should fail
 * The case where an empty line occurs instead of the sequence should fail
 * The case where an empty line occurs between records should succeed

**Comment by ebolyen** [comment]
@anderspitman Would you be up for tackling this issue? Should be relatively straight-forward and will introduce you to IO. I am happy to explain anything in regards to IO as well.

**Comment by Jorge-C** [comment]
Just curious, is there a standard for these files? Does it say anything
about blank lines?

**Comment by ElDeveloper** [comment]
I haven't checked in a while but can we also add that it should report
what was the last record it successfully parsed? Usually useful to
figure out what's wrong with your file.

**Comment by jairideout** [comment]
From the file format descriptions I could find for FASTA/Q, blank/whitespace-only lines aren't part of the format. However, we've had users with files that had a trailing blank line at the end of the file, or with records separated by newlines (maybe for readability?).

I think we should support ignoring these lines only if they appear *between* records. If they appear in the middle of a record it's hard to tell if a user incorrectly catted a file together, if there was an empty sequence (not allowed), etc.

I'm on the fence about whether this behavior should be the default or not. Thoughts?

**Comment by Jorge-C** [comment]
That's very reasonable.

I don't have any thoughts regarding whether it should be possible to error
or not on blank lines.

2015-03-06 13:30 GMT-07:00 Jai Ram Rideout <notifications@github.com>:

**Comment by anderspitman** [comment]
@ebolyen Somehow I didn't notice you tagged me until @jairideout suggested this issue today. Sorry about that. Happy to work on this.

**Comment by anderspitman** [comment]
@jairideout we want to implement this as an option and not default behavior, correct? The current documentation explicitly says blank spaces aren't valid.

@ebolyen Looking through the potential test cases you mention. I know in the interest of performance we don't currently validate records unless/until the user calls ``is_valid``, correct? In that case do we want to do whitespace validation every time the blank space feature is enabled, or roll whitespace validation into ``is_valid``? I'm assuming the latter.

**Comment by jairideout** [comment]
> we want to implement this as an option and not default behavior, correct?

@ebolyen and I think this should be the default (and only) behavior, no flag/option necessary.

> In that case do we want to do whitespace validation every time the blank space feature is enabled, or roll whitespace validation into is_valid?

I think this whitespace handling should be enabled at all times (it already is, so we shouldn't have too much of a performance hit). `BiologicalSequence.is_valid` checks whether the characters are within the IUPAC alphabet so we leave that check off since it could have a large performance impact.

**Comment by anderspitman** [comment]
Ah ok I didn't realize we were already doing some validation outside of ``is_valid``.

**Comment by Jorge-C** [comment]
I just came across a file, downloaded from NCBI, which had an empty line at the end. I haven't tested @anderspitman PR yet, hope it fixes that :)

**Comment by anderspitman** [comment]
@Jorge-C it should work. I'm happy to try it real quick if you want to link or send me the file.

**Comment by Jorge-C** [comment]
Thanks!! It's a small genome, can be downloaded [here](http://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?tool=portal&sendto=on&log$=seqview&db=nuccore&dopt=fasta&sort=&val=108885074&from=begin&to=end&maxplex=1). If the link expires, it can also be found [here](http://www.ncbi.nlm.nih.gov/nuccore/108885074?report=fasta&to=580076). Then click on "send" and choose destination "file".

**Comment by anderspitman** [comment]
Thanks! It always helps to test with real data early on. I an confirm that that sequence does not work on master, but does work after the changes in this PR, so that's a good sign.

**Comment by Jorge-C** [comment]
Sweet, thanks for checking!

**Comment by anderspitman** [comment]
@jairideout @ebolyen concerning FASTQ files. It appears we're using some of the same test files as the Open Bioinformatics Foundation. One of the files, `error_trunc_at_seq.fastq`, is considered invalid by OBF but would be valid after implementing the functionality in this issue. Should we diverge here or not allow blanks in FASTQ? I'm assuming diverge but want to make sure.

**Comment by anderspitman** [comment]
Sorry I meant `error_no_qual.fastq`, and I believe the file is still invalid but it shouldn't fail because of the blanks.

**Comment by anderspitman** [comment]
Wow, wrong again. That file is completely missing quality scores (who would have guessed). Ignore the last 3 comments.

**Comment by anderspitman** [comment]
Here's a more useful question: Should we give preference to blank line exceptions or invalid qual character exceptions with qual data?

**Comment by anderspitman** [comment]
@jairideout FYI I rediscovered what that last question was about. Consider the following FASTQ file:

```
@foo bar baz
AACCGG
+
MNO

@QR
@bar baz foo
TTGGCC
+
876543
```

In this case the error is somewhat ambiguous, due to the fact that '@' is a valid quality character. Is there a blank space embedded within the quality scores of the first sequence, or is the second sequence (id 'QR') missing it's data, in addition to the first sequence having truncated quality scores? You can get a reasonable answer by counting the quality scores. If the number of quality scores is correct but there's a blank line embedded, you know what's wrong. We're not going that far currently. I think it's reasonable to just assume a blank line error in this case, which is what I'm doing currently in #893.

**Comment by jairideout** [comment]
This is an interesting case, thanks for brining this up. I agree that a blank line error makes sense, since a blank line occurs before we've found the expected number of quality scores. Thus, we know that a blank line occurred within a record, which we aren't allowing. @ebolyen do you agree with this behavior?

**Comment by ebolyen** [comment]
@jairideout That makes sense to me.

**Comment by jairideout** [comment]
> I haven't checked in a while but can we also add that it should report
what was the last record it successfully parsed? Usually useful to
figure out what's wrong with your file.

@ElDeveloper can you please create a new issue for this feature? I agree this would be good to have but it didn't make it into #893 / #916.
