### ISSUE TITLE
TreeNode.tip_tip_distances doesn't work with GG 13_8 trees

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#791]
I'm not sure if this is an issue with the ``TreeNode`` or the tree itself, but I get this error with all of the different trees in this build of Greengenes. @wasade, do you know what's going on here? I confirmed that the md5 of the tree that I'm working with locally is the same as the md5 of the tree on ftp://greengenes.microbio.me.  

```python
In [1]: from skbio import TreeNode

In [2]: t = TreeNode.read('/Users/caporaso/data/gg_13_8_otus/trees/70_otus.tree')

In [3]: t.tip_tip_distances()
---------------------------------------------------------------------------
NoLengthError                             Traceback (most recent call last)
<ipython-input-3-0105b92aef7c> in <module>()
----> 1 t.tip_tip_distances()

/Users/caporaso/.virtualenvs/qiime/lib/python2.7/site-packages/skbio/tree/_tree.pyc in tip_tip_distances(self, endpoints)
   2740                 if child.length is None:
   2741                     raise NoLengthError("Node with name '%s' doesn't have a "
-> 2742                                         "length." % child.name)
   2743
   2744                 distances[child.__start:child.__stop] += child.length

NoLengthError: Node with name 'k__Bacteria' doesn't have a length.

In [4]: t = TreeNode.read('/Users/caporaso/data/gg_13_8_otus/trees/70_otus_unannotated.tree')

In [5]: t.tip_tip_distances()
---------------------------------------------------------------------------
NoLengthError                             Traceback (most recent call last)
<ipython-input-5-0105b92aef7c> in <module>()
----> 1 t.tip_tip_distances()

/Users/caporaso/.virtualenvs/qiime/lib/python2.7/site-packages/skbio/tree/_tree.pyc in tip_tip_distances(self, endpoints)
   2740                 if child.length is None:
   2741                     raise NoLengthError("Node with name '%s' doesn't have a "
-> 2742                                         "length." % child.name)
   2743
   2744                 distances[child.__start:child.__stop] += child.length

NoLengthError: Node with name 'None' doesn't have a length.
```

**Comment by MikeDeberg** [comment]
Hey guys,
I believe I understand @ebolyen's intended solution and will take a look at this.

**Comment by ebolyen** [comment]
Thanks @MikeDeberg! 
@gregcaporaso @jairideout, @MikeDeberg is a current student here at NAU and would like to get involved in skbio. 

@MikeDeberg I am happy to help you out in getting familiar with our codebase and processes.

**Comment by ebolyen** [comment]
@gregcaporaso Can you assign?

**Comment by MikeDeberg** [comment]
Thank you @ebolyen I will definitely take you up on that offer.

**Comment by gregcaporaso** [comment]
Great, welcome @MikeDeberg! I just invited you as a collaborator on the repository. Once you accept that you should be able to self-assign the issue.

**Comment by jairideout** [comment]
@gregcaporaso I don't think @MikeDeberg will be able to self-assign since collaborators have read-only permissions.

@MikeDeberg just let us know when you've accepted the invite and we'll assign to you.

**Comment by MikeDeberg** [comment]
Thank you @gregcaporaso,

I have accepted the invite, ready for assignment.

**Comment by jairideout** [comment]
Assigned to you, thanks @MikeDeberg!

**Comment by MikeDeberg** [comment]
Awesome, thanks @jairideout

**Comment by gregcaporaso** [comment]
Ok, thanks!

**Comment by MikeDeberg** [comment]
So, the idea was put into my head to use something more descriptive than just a user warning.

I figure the warning itself will provide the opportunity the explain the situation to the user but if I'm going to add a class to warnings it would be cool, if possible, to write something that could be used in other similar situations where substitutions have been used to enable something to operate successfully.  

@ebolyen suggested something about auto casting like autocastwarning, but since that doesn't exist in python I'd rather use something like assumptionwarning, substitutionwarning, representationwarning...

Any thoughts/suggestions would be greatly appreciated!

**Comment by MikeDeberg** [comment]
@jairideout : While implementing the numpy solution you suggested for this issue I noticed that numpy.testing is imported as nptest. I learned from an offline conversation with @ebolyen that it should be getting imported as npt as it is in every other case I could find.

Would you like me to refactor this in the _tree_test I am working in as part of this issue?

**Comment by Jorge-C** [comment]
That sounds great to me :+1:

**Comment by jairideout** [comment]
That'd be great if you don't mind making the changes, but not required for merge.
