### ISSUE TITLE
Incorporating in fast permutation tests

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#804]
Over the break, I've been developing fast permutation tests that can make use of SIMD instructions and multithreading through numpy matrix operations.

So far, I have developed 3 permutation tests: a mean test, a t-test and a pearson correlation test.

To get an idea for the timings, I've benchmarked the mean test to a naive implementation on a 60x60 OTU table with 1000 permutations.  Below are the timings

Naive time [s]: 1.91008838018
Numpy time [s]: 0.0174480279287

If you guys are down, I can start committing these algorithms into skbio.  In the near future, I plan on implementing ANOVA tests such as an F-test and a Krustal-Wallis test.

EDIT:  Adding a link to my code: https://github.com/mortonjt/ANCOM
The permutation tests can be found under ancom/stats/permutation.py
and the corresponding unittests can be found under ancom/test/test_permutation.py

**Comment by jairideout** [comment]
@mortonjt this sounds awesome! We currently are relying on scipy for all of the stats you mentioned (they aren't implemented in scikit-bio). It might be worth checking with them (on their issue tracker or mailing list) to see if they'd be interested in incorporating this into scipy. Does that sound good to you?

cc @gregcaporaso

**Comment by mortonjt** [comment]
Good call!  Just sent them a ping.

https://github.com/scipy/scipy/issues/4399

**Comment by jairideout** [comment]
Thanks!

**Comment by jairideout** [comment]
Closing as this functionality seems to fit better in scipy and/or statsmodels.
