### ISSUE TITLE
Tests failing with numpy 1.7 and matplotlib 1.3.1

### ISSUE THREAD

**Issue by anderspitman** [biocore/scikit-bio#806]
Travis should be running this same configuration, so I might be doing something wrong, but it appears to be broken. If I create a fresh conda environment with the following command:

``~/anaconda/bin/conda create -n skbio_env python=2.7 pip numpy=1.7 scipy matplotlib=1.3.1 pandas nose pep8 sphinx=1.2.2 ipython``

And then activate it:

``source ~/anaconda/bin/activate skbio_env``

Install skbio from scikit-bio directory:

``pip install -e .``

And then try to run some tests:

``nosetests skbio/sequence``

I get the following exception:

``ValueError: numpy.ufunc has the wrong size, try recompiling``

I believe it's failing because the version of scipy pulled in by conda is built against a newer version of numpy. What I don't get is why isn't Travis choking on this. Am I missing something here?

**Comment by Jorge-C** [comment]
Thank you very much for providing detailed instructions! I have tried these steps and can't reproduce it in linux with conda 3.7.4 and a fresh git clone. This error is typical from binary incompatibilities, and usually it's solved by using a newer numpy (at least whichever was used to compile scikit-bio) or recompiling scikit-bio for the older numpy version.

I don't know how that's happening for you, but (I guess) somehow the tests are picking up one scikit-bio's cython extensions that you had maybe compiled for a different, newer, numpy version. Can you please try clearing the scikit-bio/build folder?

**Comment by anderspitman** [comment]
Yep, that did it. Thanks @Jorge-C!

**Comment by anderspitman** [comment]
@Jorge-C: Also, I think the reason I'm getting this issue is that I'm working on a test script that runs the test suite against all of our Travis environments (see #800). Travis has the advantage of having a fresh isolated copy of skbio for each conda environment. I'm going to try and find a way to use the same skbio directory for different conda envs at the same time without hitting these issues. You have any suggestions?

**Comment by Jorge-C** [comment]
I see, I'll add a comment there!
