### ISSUE TITLE
rename I/O read/write methods to load/save?

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#812]
# Question
Should the current I/O `read` and `write` methods be renamed to `load` and `save`, respectively?

# Example (object-oriented)

```python
aln = Alignment.read('seqs.fasta')
...
aln.write('newseqs.fasta', format='fasta')
```

would become:

```python
aln = Alignment.load('seqs.fasta')
...
aln.save('newseqs.fasta', format='fasta')
```

# Example (procedural)

```python
aln = read('seqs.fasta', into=Alignment)
...
write(aln, format='fasta', into='newseqs.fasta')
```

would become:

```python
aln = load('seqs.fasta', into=Alignment)
...
save(aln, format='fasta', into='newseqs.fasta')
```

# Rationale

The current names might be confusing because they match the names used by Python for file I/O. @johnchase was reading some code that @shiffer1 wrote and was initially confused because he thought `write` was being called on a file handle instead of a scikit-bio object. Thus, the code looked backwards because a filepath was being passed to the `write` method instead of a string that should be written.

By renaming these methods to `load` and `save`, we'd be using names that are distinct from Python's I/O methods, which would hopefully minimize confusion. IMO, `load` and `save` are less CS-oriented and slightly higher-level descriptions than `read` and `write`. Since scikit-bio is targeted for users who may not have strong technical/programming backgrounds, these new names may be easier to understand and remember.

I don't have very strong feelings either way. @ebolyen brought up a good point that using the same names as Python for file I/O could be advantageous because we have already adopted other Pythonic names (e.g., file "sniffers") and this would be consistent with Python's standard library. Also, AstroPy uses `read` and `write` in their I/O framework.

cc: @gregcaporaso @ebolyen @johnchase @shiffer1 @ElDeveloper

**Comment by antgonza** [comment]
I think we should leave the Python names.

**Comment by ebolyen** [comment]
@antgonza I agree, but would you care to elaborate?

**Comment by antgonza** [comment]
I think changing the names will be a band aid to a different problem
as I believe the confusion could only be raised when a novice
programer looks at the code and skips the imports section. Also, if
you want to import different `open`s we can always use `import as`.
Finally, this will allow dev time to be focus on new functionality.

**Comment by josenavas** [comment]
I see the point of @antgonza, but IMOO if making this change now is not going to take more than 30min of developer time, I would suggest changing it, as load/save makes more sense.
However, if this code is used in a variety of places and it will require an entire day of developer work, then is not worth it.

**Comment by wasade** [comment]
I think load/save are misleading as they imply files, but we may actually
be reading or writing from a stream.

**Comment by ebolyen** [comment]
@antgonza I believe the issue was actually in regards to the method form of the IO operations. We also don't override `open` in any case. 

I definitely agree with your last point, but the overhead would mostly be documentation; most of the "real" code is generated on the fly and can be renamed in a line or two.

With regards to astropy, one thing I had not considered is that astropy does not have method forms of `read` and `write`, they are strictly procedural; so this confusion feels less likely to happen in their case. For that reason, any precedence set by astropy may not be a good reason to change/not change.

**Comment by antgonza** [comment]
Thanks for the clarification @ebolyen, I think that reinforces the
idea of my first point. However, I do not have strong feelings about
it. Perhaps, that's a better question: who has strong feelings about
the change and why?

**Comment by ebolyen** [comment]
@wasade actually has a really good point.
One thing we are planning, is at least basic url fetching.

Without prior knowledge, the following would be pretty ambiguous.
`SequenceCollection.save("http://example.com/file.fna")` <- Is this downloading or uploading the file?

I don't think we intend to implement file upload, because it is unlikely anyone would use it. However if `load` and `save` are the vocabulary, then standard UX analogies break down. (Right click *save* file as...)

`read` and `write` do not suffer this particular confusion.

**Comment by jairideout** [comment]
:+1: for the points raised by @wasade and @ebolyen.

I also thought of another reason to keep the names `read` and `write` (similar to @antgonza's first point above): even though scikit-bio is targeted to non-technical users, we may be leading people in the wrong direction by using terms that aren't standard in the field (i.e., within computer science and across programming languages). `save` and `load` might be more intuitive names to novice programmers, but it's probably worth using standard nomenclature, especially if these users will be using other tools/languages/etc.

**Comment by gregcaporaso** [comment]
I'm leaning toward keeping ``read`` and ``write`` based on this discussion. I think there several good arguments made for keeping those names.

**Comment by ElDeveloper** [comment]
:+1:, it seems like the best that can be done at the moment. After
searching in scikit-learn, numpy and pandas, it seems that they they use
load/save instead of read/write (not that this should be a definitive
factor), but I thought it would be useful to mention this.

**Comment by johnchase** [comment]
I think this is in part a limitation of python where the object type is not explicit.
Take the following code for example:
`distance_matrix.write(output)`

The `write` method could be the standard python library or it could be the scikit-bio implementation. There is nothing to suggest that `distance_matrix` in this example is anything other than a string as that is what the standard python usage would be. I think can cause confusion even among non-novice programmers and while it's not to hard to figure out what is going on it is still not explicit what is happening (dang python!). I think it's worth avoiding any confusion if possible, and even if it is only novice programmers that are confused by this shouldn't we assume that novice programmers will be writing/reviewing code using scikit-bio?

As @ElDeveloper mentioned other common libraries avoid this by not using `read` and `write`. 

With all of that said I'm not convinced that `read` and `write` aren't the best, just wanted to add something to think about.

**Comment by jairideout** [comment]
With the new I/O registry in #963, many sources make the most sense with `read` and `write`.
