### ISSUE TITLE
pep8 has been updated

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#818]
The carnage is terrible. We need to change a lot of imports to remain compliant now.

**Comment by Jorge-C** [comment]
As someone pointed out in the [pep8 issue](https://github.com/jcrocholl/pep8/issues/264#issuecomment-73584055) this wouldn't let us do things like having [optional dependencies](https://github.com/biocore/scikit-bio/issues/760), so maybe we should think about disabling some messages.

**Comment by ebolyen** [comment]
I think we would handle optional dependencies inside the function which requires them. Bypassing the pep8 issue altogether.

**Comment by Jorge-C** [comment]
Yes, I haven't tested it but we'd have imports inside functions (so not at the top) and the style checker would then complain.

**Comment by ebolyen** [comment]
importing inside of a function is completely fine by pep8 and `pep8/flake8`

**Comment by Jorge-C** [comment]
Thanks @ebolyen! Good to know :)
