### ISSUE TITLE
add phylogenetic diversity metrics

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#822]
`The user measures alpha- and beta-diversity using phylogenetically-aware metrics.`

- [x] Faith's Phylogenetic Diversity (PD) (#820)
- [x] weighted/unweighted UniFrac (#46)

Depends on:

- [ ] add `ContingencyTable` (#821)
- [ ] refactor `TreeNode` (#809)

**Comment by gregcaporaso** [comment]
See #730 re: PD and UniFrac implementations in IAB.
