### ISSUE TITLE
What to do about skbio.spatial?

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#830]
`skbio.spatial` currently only has a single function `procrustes`. Scipy has a partial implementation of this (the general case), so should we adapt it and move our `procrustes` into ordination as that is how it is used in scikit-bio?

**Comment by gregcaporaso** [comment]
related to scipy/scipy#3786

If we could eventually drop ours and use SciPy's, that'd be ideal.

**Comment by ElDeveloper** [comment]
It would be nice if we can figure out how to use that function from our procrustes implementation. When I was trying to do that, I encountered the following problem:

https://github.com/scipy/scipy/issues/3994

Which prevented me (at that time) from moving the code out of skbio and into scipy.

**Comment by jairideout** [comment]
> If we could eventually drop ours and use SciPy's, that'd be ideal.

:+1: 

@ElDeveloper are you interested in taking the lead on this issue, since you've already started working on it? If so, I'll assign to you.

**Comment by ElDeveloper** [comment]
I am! However, I couldn't find a good way to use their function without
special-casing for our needs (which in general seems like a bad
practice), but that's where I got stuck at. I'll take another round at
this piece of code this Friday or if not earlier and report back.

**Comment by jairideout** [comment]
Awesome, thanks @ElDeveloper!

**Comment by ElDeveloper** [comment]
PR in https://github.com/scipy/scipy/pull/4540

**Comment by jairideout** [comment]
Thanks! Let's leave this issue open so that we can deprecate scikit-bio's `spatial` subpackage once `procrustes` is in a scipy release.

**Comment by ElDeveloper** [comment]
Sounds good.

**Comment by jairideout** [comment]
Noticed that scipy/scipy#4540 was merged, thanks for working on this @ElDeveloper!

**Comment by ElDeveloper** [comment]
Not a problem, the code review helped improve the code a lot (mainly by making better use of the numpy API).

**Comment by ElDeveloper** [comment]
https://github.com/scipy/scipy/releases/tag/v0.16.0 woot! :beers:

**Comment by jairideout** [comment]
:shipit:
