### ISSUE TITLE
Ensure objects are immutable

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#834]
Immutable objects will prevent side-effects that could lead to incorrect results if our users are unaware of that property of the object.

Even if it may be slightly less efficient in some cases, it is better than incorrect results being published as a result of our library.

**Comment by jairideout** [comment]
We decided not to force immutability across the codebase as this isn't how Python libraries typically work and it is impossible to enforce in certain situations (for example, now that we support truly arbitrary metadata on sequence objects). Decisions on immutability will be made on a per-object basis going forward.

**Comment by ebolyen** [comment]
:+1:

**Comment by Jorge-C** [comment]
Great! :+1:
