### ISSUE TITLE
Adding in Compositional Data analysis methods

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#835]
Composition Data analysis is an alternative technique to analyzing compositional data (aka data involving percentages and proportions).

Most of the OTU data that we are dealing with are inherently compositional, and applying some of these techniques would really ease analysis/interpretation of this sort of data.

As far as I can tell, these techniques have not been implemented anywhere in the Python world.
I've started drafting some of these methods [here](https://github.com/mortonjt/ANCOM/blob/master/ancom/linalg/composition.py).

Also, a bunch of nice visualization tools can be used within this framework, such as [compositional biplots](http://en.wikipedia.org/wiki/Biplot) and [ternary plots](http://en.wikipedia.org/wiki/Ternary_plot)

I realize that scikit-bio is undergoing some infrastructure changes.  Perhaps once the [Contingency Table](https://github.com/biocore/scikit-bio/issues/821) has been added, I can start porting over some of these methods.

**Comment by Jorge-C** [comment]
What are the differences between compositional biplots and plain biplots (ie plotting samples as dots and continuous variables as arrows?

The ordination methods used to have (very barebones) 2D biplots and triplots (when plotting samples and sites as dots, plus variables as arrows) through matplotlib, though they ended up [removed](https://github.com/biocore/scikit-bio/commit/03e11a33b02ad2dd219634a8576314dabfeb0664) and we just added a simple scatter plot later.

I agree that recovering (but mainly improving) bi/triplots would be fantastic, and ternary plots look cool.

:+1:

**Comment by mortonjt** [comment]
Technically they are exactly the same.

The main difference is that the biplots that I'm proposing have a particular log transformation (called centre log transformation) applied to the OTU percent abundance data.   A standard SVD can be applied to this data to obtain PC coordinates, however, a [more correct SVD](http://www.sis2014.it/proceedings/allpapers/2863.pdf) for compositional data for potentially more accurate results.

**Comment by Jorge-C** [comment]
I see, thanks! So they'd be useful for contingency table that have relative abundances, and you'd take the element wise logarithm of the table, and then center it. Is there a standard way to deal with null abundances?

**Comment by mortonjt** [comment]
Exactly!

So zeros are still a problem with this area - there are a couple of common ways about it.
1) [Multiplicative replacement](http://www.leg.ufpr.br/lib/exe/fetch.php/pessoais:abtmartins:dealingwithzerosandmissingvalues.pdf).
This is a very common approach.  Not only it is simple, but it doesn't seriously distort the non-zero data.
2) [EM](http://www.sciencedirect.com/science/article/pii/S0098300407002208)
This approach has shown to have less bias - but its a bit more computationally expensive.

I already have the first one coded up.  It may not be a bad idea to also include the second approach.

**Comment by Jorge-C** [comment]
Thanks for the references, I agree it would be great to have these in skbio!

A correct implementation of EM could be sped up using cython later on, so that's not a big issue. Let me know if I can be of any help! I implemented our ordination methods, though I haven't used them that much, and most had not been implemented in Python or under permissive licenses, so we can end up with a very nice and comprehensive set of tools to analyze this kind of data.

**Comment by mortonjt** [comment]
:+1:

**Comment by gregcaporaso** [comment]
@mortonjt, note that I just followed up on the plotting issue on #685.

**Comment by mortonjt** [comment]
Perhaps this isn't dependent on the Contingency Table.

If so, I'll be submitting a PR for this really soon.  I'll probably add a new file called ```skbio.stats.composition```

It'll contain the following functionality

* ```closure(mat)```
* ```zero_replacement(mat)```
* ```perturb(x, y)```
* ```perturb_inv(x, y)```
* ```power(x, y)```
* ```clr(mat)```
* ```centre(mat)```

These are all of the functions required to create a biplot.

@Jorge-C , @ElDeveloper @antgonza . Would you be willing to review this PR?  Do you think i should split it up?

**Comment by ElDeveloper** [comment]
Yes, I'll have a look!

**Comment by mortonjt** [comment]
Thanks!

**Comment by jairideout** [comment]
@mortonjt can this be closed now that #860 is merged?

**Comment by mortonjt** [comment]
I'd like to make 1 more PR with the following functionality

`clr_inv` - inverse clr transform
`ilr` - isometric log ratio transform
`ilr_inv` - inverse isometric log ratio transform
`inner` - Aitchison inner product (tests for orthogonality and is required in ilr)

This PR will be significantly smaller.  But once that's merged, then yes, I think this issue can be closed.

**Comment by jairideout** [comment]
Sounds good, thanks for the details!

**Comment by jsevo** [comment]
Hey,

How are you getting on with this? I actually implemented all these functions myself last week and am happy to look over you prototype / discuss. The prototype is not accessible to me at the moment though.

**Comment by mortonjt** [comment]
Hi @jsevo .  Glad that you are interested!

All of the core methods have been implemented as of #860 and #892 - the functions can be found [here](https://github.com/biocore/scikit-bio/blob/master/skbio/stats/composition.py).

Let me know if you have any trouble using these functions.  Also if you have code for visualizing compositional biplots or ternary plots, I'll be happy to review it.

**Comment by jairideout** [comment]
@mortonjt can this issue be closed now that #892 is merged?

**Comment by mortonjt** [comment]
:+1: on closing it

**Comment by jsevo** [comment]
:+1: on closing it
