### ISSUE TITLE
Filtering high entropy positions (very minor doc improvement)

### ISSUE THREAD

**Issue by JTFouquier** [biocore/scikit-bio#840]
It would probably be better to have varying positional entropies for teaching purposes in the documentation on this page: 
http://scikit-bio.org/docs/latest/generated/skbio.alignment.Alignment.position_entropies.html?highlight=entropy

from skbio.alignment import Alignment
from skbio.sequence import DNA
sequences = [DNA('AC--', id="seq1"),
                      DNA('AT-C', id="seq2"),
                      DNA('TT-C', id="seq3")]
a1 = Alignment(sequences)
print(a1.position_entropies())
[**0.63651416829481278**, **0.63651416829481278**, nan, nan]

**Comment by gregcaporaso** [comment]
@JTFouquier, I agree - would you want to submit a pull request to scikit-bio with that change? It'd be a great first contribution, and we could help if you have any questions about how to do it.

**Comment by JTFouquier** [comment]
@gregcaporaso, sounds good.  I'm going over some of the things I learned in AZ with Scott and the other students in my lab (hopefully today) so I'll use this as a Git teaching opportunity.  Thanks!

**Comment by gregcaporaso** [comment]
Great!

On Mon, Feb 16, 2015 at 8:34 AM, Jennifer Fouquier <notifications@github.com

**Comment by JTFouquier** [comment]
So apparently I'm doing something wrong.  I forked sci-kit bio, and tried to do "git clone git clone git@github.com:biocore/scikit-bio.git" but I get this error inside of a virtual environment that has been initialized with git...  
![screen shot 2015-02-17 at 5 15 10 pm](https://cloud.githubusercontent.com/assets/7920357/6240861/5eda9b9c-b6c9-11e4-8100-eeab61647b54.png)

I tried the github help for the "permission denied public key" but then it talks about doing SSH key stuff and those steps are failing... but I don't really understand why my other repository communicates with git, but now this one won't.  Help appreciated!  Thanks!

**Comment by Jorge-C** [comment]
@JTFouquier I' suggest using https cloning to avoid ssh issues, but note that you're cloning biocore's repo, not your fork:
```bash
$ git clone https://github.com/biocore/scikit-bio.git
```
---

I see now that are instructions in the README might be misleading, try [these steps instead](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md#submitting-code-to-scikit-bio)

**Comment by JTFouquier** [comment]
Thanks @Jorge-C!!  Yes, that makes sense.  I was reading the installation of the development version of skbio and got things confused with that an the "contributing" documentation.
