### ISSUE TITLE
Installation of development version

### ISSUE THREAD

**Issue by Jorge-C** [biocore/scikit-bio#850]
Our README instructions to install the development version might mislead a new developer to clone biocore's repo instead of forking and modifying that, plus they use ssh instead of https cloning, which is another roadblock for a would-be contributor. We just need to point readers to CONTRIBUTING.md, which has the right steps.

**Comment by jairideout** [comment]
:+1: thanks for catching this!

**Comment by jairideout** [comment]
Will address as part of #867.
