### ISSUE TITLE
Checklist.py should verify the copyright headers on each file.

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#855]
The current standard for scikit-bio's copyright headers is defined [here](http://scikit-bio.org/docs/latest/development/new_module.html). What checklist should be able to validate:

If there is a module level docstring:
 1. The docstring appears at the top of the file. Variant isn't important (can be `r"""....` or plain `"""....` and any style of quotation).
 2. This docstring is immediately followed by a new line.
 3. After this new line, our copyright header appears in full.
 4. Finally another new line.

If there is **no** module level docstring:
 1. The copyright header appears at the top of the file in full.
 2. Followed by a new line.

I would suggest using the [tokenize](https://docs.python.org/3/library/tokenize.html) module in the standard library to accomplish this as it can identify comments while the AST module has already stripped them.

**Comment by vivekiitkgp** [comment]
@ebolyen I would like to give a shot to this issue. Could you please assign?

**Comment by ebolyen** [comment]
@gregcaporaso, @vivekiitkgp needs to be added as a contributor to be assigned issues. 

In the mean-time, @vivekiitkgp is handling this issue.

Thanks!

**Comment by gregcaporaso** [comment]
I've sent @vivekiitkgp an invitation to join the team.

**Comment by vivekiitkgp** [comment]
@ebolyen Can you please review the PR?
