### ISSUE TITLE
Tests fail when run twice in a row

### ISSUE THREAD

**Issue by anderspitman** [biocore/scikit-bio#857]
When running tests via ``numpy.testing.Tester``, if you run them twice in a row the second time fails:

```python
import skbio
skbio.test()
...
Ran 1123 tests in 40.921s

OK
skbio.test()
...
Ran 1123 tests in 41.168s

FAILED (failures=3)
```

The errors seem to indicate that expected warnings aren't happening:
``AssertionError: No warning raised when calling PCoA``

This makes sense, because I've noticed certain warnings only occur the first time you use the procedure after importing it.

**Comment by josenavas** [comment]
We had this issue in qiita. The warnings are raised only the first time that they're hit in a python session. They're then cached and they're not raised again. You can apply a filter to python so it always raises the warning by doing:

```python
import warnings
warnings.simplefilter('always', UserWarning)
```

**Comment by ElDeveloper** [comment]
Yeah, that would work but I would say that in the case of scikit-bio we
want the warnings to only show up once. Hoping not tu clutter the stderr
of applications using the library, for example QIIME.

**Comment by anderspitman** [comment]
We might be able to reset the warnings cache manually when the tests are run. I'll look into that as part of my work on #808.

**Comment by anderspitman** [comment]
#808 ended up getting somewhat cluttered. I'll work on this separately.

**Comment by jairideout** [comment]
Closing, see discussion in #871 for details.
