### ISSUE TITLE
Add 'metadata' attribute to BiologicalSequence

### ISSUE THREAD

**Issue by josenavas** [biocore/scikit-bio#870]
In some cases it is useful to attach some metadata/precomputed values to the BiologicalSequence so we can access those values later. I think a dict will suffice.

**Comment by ebolyen** [comment]
:+1: We are heading in this same direction. We will also need this for stockhom formats. Likely related to #827 in some way.

**Comment by ebolyen** [comment]
Just some additional thoughts:
We would like to support ranged metadata, though we aren't quite sure what that API would look like. (It is a shame that the python slice syntax must be used in getitem, else we could imagine something like: `DNA('...', introns=[0:3, 5:10]`)

**Comment by jairideout** [comment]
Fixed in #938
