### ISSUE TITLE
coverage comments

### ISSUE THREAD

**Issue by Jorge-C** [biocore/scikit-bio#873]
Should we disable coveralls comments in PRs? I think they add excessive email noise, with information that hardly ever changes.

**Comment by ElDeveloper** [comment]
It's a good way to know that builds are ready though. I :-1: removing
the @coveralls comments.

**Comment by ebolyen** [comment]
I don't have strong feelings on the matter. Since coveralls puts the information in the build status it doesn't really matter too much. And I would hope no one merges PR's which are yellow (a.k.a. being tested).

**Comment by jairideout** [comment]
:+1: for disabling coverage emails now that we have that info in the build status. I think the developer submitting the PR should post a comment letting reviewers know that it's time for another review (that's the only time these coverage emails have been useful to me at least).

**Comment by ElDeveloper** [comment]
@ebolyen What I mean is that having a comment posted to the PR is a
good way for me to get a notification on my email that the build is
done.

**Comment by ebolyen** [comment]
@ElDeveloper That makes more sense. But I agree with @jairideout that we can't know for sure when the PR is ready for re-review.

**Comment by Jorge-C** [comment]
To summarize, there's a slight preference for disabling them: :+1: :-1: +:zero: :+1: so I'll do that soon. Main arguments: we still need a message from the developer saying code is ready for re-review, the information is still available at the build status. Thank you guys!
