### ISSUE TITLE
Method that does subset of SequenceCollection would be nice, similar to Alignment.subalignment()

### ISSUE THREAD

**Issue by JTFouquier** [biocore/scikit-bio#874]
When writing fasta seqs it would be nice to have method that quickly does "seqs_to_keep" (subset) just like in the Alignment class.  Feature suggestion.  

seqs_to_keep : list, optional 

http://scikit-bio.org/docs/0.2.3/generated/skbio.alignment.Alignment.subalignment.html?highlight=subalignment

**Comment by ebolyen** [comment]
Is this in regards to `SequenceCollection`? Or are you interested in a kwarg which accomplishes this in the writer itself?

**Comment by JTFouquier** [comment]
From what I see, it would make sense to have a subset in the `SequenceCollection`

to get these sequences:    seq_list = ["C1", "C2"] 

from a `SequenceCollection` object I do this:

def get_seq_from_list():
    seqs = SequenceCollection.read("otu_seqs.fasta", format="fasta")
    for i in seq_list:
        seq_in_list = seqs.get_seq(i)
        yield seq_in_list

skbio.write(get_seq_from_list(), into="practice_mini_out.fasta", format="fasta")


in the `Alignment`  class I can do this in one line, but I do not have an alignment:
otu_seqs = all_tips_seqs.subalignment(seq_list)

**Comment by ebolyen** [comment]
That makes sense. Also just as a tip for your example code above, you can use a generator rather than a sequence collection by using `skbio.read` your code will look basically identical, but it will be very memory efficient.

**Comment by JTFouquier** [comment]
Yeah, these files should be small, but you're right, I'll use a generator.  Thanks!

**Comment by JTFouquier** [comment]
:+1: !!

**Comment by ebolyen** [comment]
`SequenceCollection` has been removed (#1220) in favor of Python list/generator-comprehensions.
