### ISSUE TITLE
None of the doctests in skbio/io/fasta.py are run

### ISSUE THREAD

**Issue by anderspitman** [biocore/scikit-bio#876]
Not actually sure if those comments are considered doctests, so maybe this is expected behavior, but just wanted to be sure. It would be ideal for that example code to be executed.

**Comment by ebolyen** [comment]
That code *should* be executed as a doctest. It is actually pretty bizarre that they aren't being run. The module doesn't even start with an underscore...

**Comment by anderspitman** [comment]
Agreed. I'll figure out what's going on.

**Comment by anderspitman** [comment]
Ok well I'm not able to reproduce my results from yesterday. I can confirm that the doctests are working using both the old testing method ``nosetests --with-doctest -I DO_NOT_IGNORE_ANYTHING skbio/io`` and the new one ``python -c "import skbio; skbio.io.test()"``. I must have been doing something weird yesterday. Pretty sure we can close this as a false alarm.
