### ISSUE TITLE
Rename current working branch to 0.3.0-dev

### ISSUE THREAD

**Issue by antgonza** [biocore/scikit-bio#878]
Testing with https://github.com/biocore/scikit-bio/commit/23b5930a75211849c3c7b3c82f020a638ed51eb2 and https://github.com/biocore/qiime/commit/294422b3f378d4caeb056935cf93bd157ba87d14, gives the following error:
```
Traceback (most recent call last):
  File "/Users/antoniog/svn_programs/qiime/scripts/multiple_rarefactions_even_depth.py", line 17, in <module>
    from qiime.rarefaction import RarefactionMaker
  File "/Users/antoniog/svn_programs/qiime/qiime/rarefaction.py", line 22, in <module>
    from skbio.stats import subsample
ImportError: cannot import name subsample
```
Not sure the full impact of changes.

**Comment by ElDeveloper** [comment]
Oddly enough testing with 0.2.3 seems to work just fine :\

**Comment by Jorge-C** [comment]
Weird, subsample was renamed back in November: https://github.com/biocore/scikit-bio/commit/bc4c15baec3dbcbf84ab90940566bc128a85f32c

**Comment by ebolyen** [comment]
QIIME depends on API version 0.2.x this was made clear in our [roadmap](https://github.com/biocore/scikit-bio/wiki/beta-release-roadmap#02x) (Also note the range in QIIME's [setup.py](https://github.com/biocore/qiime/blob/master/setup.py#L439) (this was intentional)). There is no intention of being backwards compatible with API version 0.2.x, testing QIIME against the latest master isn't meaningful. If we release a 0.2.4 version, we would guarantee compatibility with 0.2.3 as they are in the same API version (0.2.x) and QIIME's tests should not fail.

**Comment by antgonza** [comment]
I'm confused, in the roadmap it says that qiime will work with
scikit-bio >= 0.2.3, < 0.3.0. The current branch is 0.2.3-dev so not
sure why is it fine to be broken, do you mind clarification?

**Comment by ebolyen** [comment]
That will get bumped to 0.3.0 on release. We aren't actively developing the 0.2.x branch.

**Comment by antgonza** [comment]
That's not clear anywhere, is it? Perhaps calling this branch
0.3.0-dev vs. 0.2.3-dev will be clearer, right?

**Comment by ebolyen** [comment]
As with every release (in all of our projects), we make no prior assumptions about what the final released version will be. Because there are backwards incompatible changes, our next release will by *definition* be 0.3.x.

**Comment by antgonza** [comment]
I think this is a bit different cause these are consider mayor
changes, right? If a dev within the group gets confused due to the
naming "flexibility", what can we expect about external ones?

**Comment by ebolyen** [comment]
The only correct solution to this problem would require a development cycle we simply cannot support with our team size. If we had a branch for 0.2.4, and 0.3.0 then we could deal with not knowing the version ahead of time, because all possible versions would have a branch. This would mean when we release we have the following branches:

* 1.0.0
    * 1.0.1
    * 1.1.0
* 2.0.0

While this would be nice, we would have to merge each pull request into ALL of the correct branches. We simply don't have the manpower to do this accurately. 

Instead, like all other projects in biocore since pycogent we simply leave the final version up to the release.

With any luck, maybe we will have the organizational structure in place to avoid this in the future. But as it stands, it's really only a handful of people actually developing this package. And we simply don't have the capacity to worry about this (or develop parallel API versions at the same time), though it may be worth revisiting at Beta. If you feel very strongly about this, feel free to create a new issue regarding our deployment cycle.

**Comment by antgonza** [comment]
Agree that it sucks but I think it has to be done. Imagine we find a
skbio bug and we have to do a quick 2.3.1 release ...

**Comment by ebolyen** [comment]
In that case, we would branch off of the last release, and fix the bug...

**Comment by antgonza** [comment]
OK, if it's that easy why not name the current branch 0.3.0-dev and
avoid this kind of discussion?

**Comment by ebolyen** [comment]
Because we didn't invent a new deployment cycle for this package. We just adopted QIIME's.

**Comment by antgonza** [comment]
Not sure that's an excuse for closing the issue vs. leaving it open so
somebody fixes it. Remember we are trying to stop reproducing past
mistakes.

**Comment by ebolyen** [comment]
I have already asked you to create a **NEW** issue if you feel strongly about this.

**Comment by ebolyen** [comment]
@antgonza This is not a new issue. Nor does it address the core of the complaint, which is the development process. Simply changing the version string does not represent a consensus for the change in the development process. Which should be a discussion, between more than just the two of us. 

Once again, I plead that you create a new issue, where we can discuss the version strategy on it's own merit. You may of course reference this issue as past discussion, but please create a new issue to open the floor for alternative opinions.

**Comment by antgonza** [comment]
What's the difference between opening a new issue vs. continue discussion here?

**Comment by ebolyen** [comment]
Quoted from above:
>   Once again, I plead that you create a new issue, where we can discuss the version strategy on it's own 
>   merit. You may of course reference this issue as past discussion, but please create a new issue to open 
>   the floor for alternative opinions.

**Comment by antgonza** [comment]
Sorry but I do not see the benefit or why this issue prevents other
people to participate ...

**Comment by gregcaporaso** [comment]
The solution to the issue that you raise for now is that you should not be importing from a development version of scikit-bio in packages that depend on its API. I have clarified this in the [roadmap document](https://github.com/biocore/scikit-bio/wiki/beta-release-roadmap). 

We are not violating the promise made in that document that *release versions numbered >= 0.2.0, < 0.3.0 are backward compatible*, as the release version that will use the current changes in master is 0.3.0. By nature of development versions being less reliable than release versions, we can't promise that development versions will be perfectly backward compatible. 

pip will never install a development version (unless you're explicitly pointing at a specific skbio file or URL, which you'd never do for Qiita/QIIME/etc), so this is not an issue that would ever come up for users, and it's the issue that virtualenv solves for developers

@antgonza, your solution of renaming this 0.3.0-dev won't work as it has the potential to be ambiguous. I've created [a new wiki page](https://github.com/biocore/scikit-bio/wiki/how-and-why-scikit-bio-development-versions-get-their-version-names) describing how we define our development versions so it's clear why we name our versions this way, why your proposed solution leads to ambiguity, and the issue with the current naming scheme that you raise here. 

Given that there are currently no practical issues with how we name development versions in scikit-bio, and that we have a lot to get done before beta, we're not going to revisit how we name development versions in scikit-bio right now, though we may want to in the future. (At that time, we'd likely want to revisit for the other biocore packages that use the current naming scheme, which is at least QIIME, Emperor, and SitePainter).

**Comment by rob-knight** [comment]
This sounds reasonable; thanks, Greg.

Rob


On Mar 22, 2015, at 3:02 PM, Greg Caporaso <notifications@github.com<mailto:notifications@github.com>> wrote:


The solution to the issue that you raise for now is that you should not be importing from a development version of scikit-bio in packages that depend on its API. I have clarified this in the roadmap document<https://github.com/biocore/scikit-bio/wiki/beta-release-roadmap>.

We are not violating the promise made in that document that release versions numbered >= 0.2.0, < 0.3.0 are backward compatible, as the release version that will use the current changes in master is 0.3.0. By nature of development versions being less reliable than release versions, we can't promise that development versions will be perfectly backward compatible.

pip will never install a development version (unless you're explicitly pointing at a specific skbio file or URL, which you'd never do for Qiita/QIIME/etc), so this is not an issue that would ever come up for users, and it's the issue that virtualenv solves for developers

@antgonza<https://github.com/antgonza>, your solution of renaming this 0.3.0-dev won't work as it has the potential to be ambiguous. I've created a new wiki page<https://github.com/biocore/scikit-bio/wiki/how-and-why-scikit-bio-development-versions-get-their-version-names> describing how we define our development versions so it's clear why we name our versions this way, why your proposed solution leads to ambiguity, and the issue with the current naming scheme that you raise here.

Given that there are currently no practical issues with how we name development versions in scikit-bio, and that we have a lot to get done before beta, we're not going to revisit how we name development versions in scikit-bio right now, though we may want to in the future. (At that time, we'd likely want to revisit for the other biocore packages that use the current naming scheme, which is at least QIIME, Emperor, and SitePainter).
