### ISSUE TITLE
Make Power Code faster

### ISSUE THREAD

**Issue by JWDebelius** [biocore/scikit-bio#880]
I'd like to improve the run time on the power calculation. Depending on the computer and the test, the run time can be quite long. Running permutations on the American Gut dataset can take upwards of an hour.

This typically involves 10 runs x 5 - 10 points/run x 500 iterations / point  = 25,000 tests - 50,000 tests. When I profiled about 85% of the time was spent on running tests. I'm sure with better profiling, the method could be sped-up more.

There are a couple of steps I have in mind to improve the code, although I'm open to suggestions.

- [ ] Switch the way `subsample_paired_power` draws samples so a new sample is drawn for each round, removing a bias.
- [ ] Optimize the code so to limit the number of points and runs needed, or try to optimize the apparent signal-to-noise so an appropriate number of points are drawn.
- [ ] Parallelize the code-base on permutations. I tried using `multiprocessing.Pool`, but this had several draw backs.

**Comment by mortonjt** [comment]
Awesome!

This may be a good place for my fast permutation test.

**Comment by josenavas** [comment]
How do we want to handle parallelization on scikit-bio? I've seen [joblib](https://pythonhosted.org/joblib/) which is being used, e.g., by scikit-learn. I did not play with it but probably is something that we want to give a shot? What others think?

**Comment by ebolyen** [comment]
Joblib looks like it would make a lot of sense in the context of scikit-learn where the focus is on the algorithms (not the structures) and creating a lightweight pipeline DSL. I'm not sure how well that will work with our current understanding of scikit-bio.
 
I'm not sure how we want to deal with it. It seems a little beyond our scope, unless we could provide some relatively transparent way to support different parallelization schemes. Maybe we can define a superclass that is injected? Then users can extend that superclass with their own parallel drivers.

Alternatively, we can ignore this for now and see if anything interesting comes up in the near future.

**Comment by wasade** [comment]
@JWDebelius, can you post the profile results (just top 10 functions) sorted by cumulative time and by total time please?

**Comment by JWDebelius** [comment]
@wasade, I used line profiler, so it may not be the most accurate representation of actual time. I didn't profile the test, but it's defined as

```
def test_alpha(x):
    vals = [map_.loc[i, 'PD_whole_tree_mean'].values for i in x]
    return scipy.stats.kruskal(*vals)[1]
```

Here are my results:
```
Sorted by total time
--------------------------------------------------------------------------------------------------------------------------------------------
Line #	 Hits	  Time	    Per Hit	 % Time(fun)  %Time(tot)	Line Contents
--------------------------------------------------------------------------------------------------------------------------------------------
 111	 35000	52967010	1513.3		97.3	 	79.5		p_values[:, idx] = test(subs)
 166	  5751	 6315867	1098.2		86.0		 9.5		exp_group = meta.loc[matched_ids].groupby(cat).groups
 104	 35000	 1199975	  34.3	 	 2.2		 1.8		pos = np.random.choice(np.arange(0, samp_lens[0]), counts[0], replace=False)
 149	    71	  231885	3266.0		 3.2		 0.3		ctrl_group = meta.loc[cat_groups[ctrl_name]].groupby(list(control_cats)).groups
 148	    71	  183810	2588.9		 2.5		 0.3		ctrl_match_groups = meta.groupby(control_cats).groups
 106	105000	  171183	   1.6		 0.3		 0.3		subs = [sample[pos] for sample in samples]
 177	  5751	  164111	  28.5		 2.2		 0.2		exp_ids = [np.random.choice(ctrl_ids, num_draw, replace=False)]
 104	 35000	  161506	   4.6		 0.3		 0.2		pos = np.random.choice(np.arange(0, samp_lens[0]), counts[0],
 183	  4544	   80243	  17.7		 1.1		 0.1		ids[idx] = np.hstack((ids[idx], exp_ids[idx]))
 175	  5751	   72201	  12.6		 1.0		 0.1		num_draw = np.array(num_ids).min()
--------------------------------------------------------------------------------------------------------------------------------------------

Sorted by Hit time
--------------------------------------------------------------------------------------------------------------------------------------------
Line #	 Hits	  Time	    Per Hit	% Time(fun)	%Time(tot)	Line Contents
--------------------------------------------------------------------------------------------------------------------------------------------
  27	    1	    3689	3689.0		0.0		   0.0		p_return = test(sub_ids)
 149 	   71	  231885	3266.0		3.2		   0.3		ctrl_group = meta.loc[cat_groups[ctrl_name]].groupby(list(control_cats)).groups
 148	   71	  183810	2588.9		2.5		   0.3		ctrl_match_groups = meta.groupby(control_cats).groups
 111	35000	52967010	1513.3	   97.3	      79.5		p_values[:, idx] = test(subs)
 166	 5751	 6315867	1098.2	   86.0		   9.5		exp_group = meta.loc[matched_ids].groupby(cat).groups
 134	   71	   17174	 241.9		0.2		   0.0		cat_groups = meta.groupby(cat).groups
  61	   70	    3491	  49.9	    0.0		   0.0		power[id1, id2, :] = _calculate_power(ps, alpha_pwr)
 104	35000	 1199975	  34.3		2.2		   1.8		pos = np.random.choice(np.arange(0, samp_lens[0]), counts[0], replace=False)
 177	 5751	  164111	  28.5		2.2		   0.2		exp_ids = [np.random.choice(ctrl_ids, num_draw, replace=False)]
 124	   70	    1627	  23.2	   57.5		   0.0		w = (p_values < float(alpha)).sum(1)/float(p_values.shape[1])
--------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by wasade** [comment]
Can you please use the cProfile? This is too specific while masking
interaction with operators making it hard to interpret. It would be useful
to make sure the test method is included as well. You can use cProfile in
IPython by just doing %prun or %%prun.

**Comment by JWDebelius** [comment]
Here's cProfile, cumulative:
```
       35953849 function calls (35595389 primitive calls) in 48.241 seconds

   Ordered by: cumulative time
   List reduced from 329 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   48.241   48.241 <string>:4(<module>)
        1    0.001    0.001   48.241   48.241 power.py:328(subsample_paired_power)
       10    0.002    0.000   47.321    4.732 power.py:916(_calculate_power_curve)
       70    0.342    0.005   47.317    0.676 power.py:829(_compare_distributions)
    35000    0.578    0.000   45.766    0.001 <ipython-input-4-640c322d58e3>:1(test_alpha)
140820/70820    0.154    0.000   39.841    0.001 indexing.py:1198(__getitem__)
    70000    0.054    0.000   39.138    0.001 indexing.py:697(_getitem_tuple)
    70000    0.734    0.000   39.084    0.001 indexing.py:798(_getitem_lowerdim)
   140820    0.586    0.000   37.419    0.000 indexing.py:1311(_getitem_axis)
    70820    0.837    0.000   33.350    0.000 indexing.py:930(_getitem_iterable)
```
And, here's total time:
```
      35953849 function calls (35595389 primitive calls) in 43.813 seconds

   Ordered by: internal time
   List reduced from 329 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    70710    2.593    0.000    3.341    0.000 index.py:1578(isin)
  7235790    2.051    0.000    2.641    0.000 {isinstance}
212450/212370    2.034    0.000    7.489    0.000 index.py:125(__new__)
   991230    1.836    0.000    1.836    0.000 {numpy.core.multiarray.array}
   283140    1.504    0.000    3.326    0.000 common.py:2279(_asarray_tuplesafe)
   212400    1.471    0.000    1.471    0.000 {pandas.lib.infer_dtype}
   216160    1.273    0.000    1.273    0.000 {method 'reduce' of 'numpy.ufunc' objects}
   140820    1.179    0.000    9.711    0.000 indexing.py:1240(_has_valid_type)
2046180/1976180    0.886    0.000    0.917    0.000 {getattr}
    70820    0.765    0.000   30.319    0.000 indexing.py:930(_getitem_iterable)
```

**Comment by wasade** [comment]
Thanks! Is it possible to use a simpler test? The test method itself is consuming the bulk of the runtime which might mask where the performance bottlenecks are of the actual framework. I suspect this is likely due to:

```python
vals = [map_.loc[i, 'PD_whole_tree_mean'].values for i in x]
```

...or is that real world? My guess is that there is quite a bit of random access, which I believe is supported given that the majority of the runtime appears to be associated with indexing in pandas. It is also possible that this is not the most efficient way to index into `map_`.

**Comment by JWDebelius** [comment]
That is real world for `subsample_paired_power`. I ran this on a variable from the American Gut data the same way I typically run it for American Gut. One of the challenges of the test is that it can be really variable in the run length. It takes way longer when I run a permanova-based test.

I can run a test data set I've been playing, but that uses `subsample_power` instead of `subsample_paired_power`.

**Comment by JWDebelius** [comment]
When I run
```
>>> import numpy as np
>>> import scipy

>>> sample1 = np.random.randn(50)*1.5
>>> sample2 = np.random.randn(50)*1.5 + 2

>>> def test(x):
...     return scipy.stats.ttest_ind(x[0], x[1])[1]

>>> test([sample1, sample2])
2.5651809734110741e-09
```
And then, profile the code, the test is still expensive:

```
        4353065 function calls in 9.478 seconds

   Ordered by: cumulative time
   List reduced from 72 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    9.478    9.478 <string>:4(<module>)
        1    0.000    0.000    9.478    9.478 power.py:152(subsample_power)
       10    0.001    0.000    9.478    0.948 power.py:916(_calculate_power_curve)
       60    0.254    0.004    9.474    0.158 power.py:829(_compare_distributions)
    30000    0.041    0.000    7.556    0.000 <ipython-input-12-1563e693a5e4>:2(test)
    30000    0.397    0.000    7.515    0.000 stats.py:3271(ttest_ind)
    30000    0.183    0.000    3.745    0.000 stats.py:3262(_ttest_finish)
    30000    0.841    0.000    3.562    0.000 _distn_infrastructure.py:1701(sf)
    60000    0.089    0.000    2.363    0.000 fromnumeric.py:2830(var)
    60000    1.186    0.000    2.274    0.000 _methods.py:77(_var)
```
And sorted by time
```        4353065 function calls in 9.319 seconds

   Ordered by: internal time
   List reduced from 72 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   270121    1.317    0.000    1.317    0.000 {method 'reduce' of 'numpy.ufunc' objects}
    60000    1.168    0.000    2.240    0.000 _methods.py:77(_var)
    60000    0.979    0.000    1.503    0.000 {method 'choice' of 'mtrand.RandomState' objects}
    30000    0.823    0.000    3.498    0.000 _distn_infrastructure.py:1701(sf)
   660091    0.662    0.000    0.662    0.000 {numpy.core.multiarray.array}
    30000    0.393    0.000    7.388    0.000 stats.py:3271(ttest_ind)
    30000    0.383    0.000    1.418    0.000 _distn_infrastructure.py:549(argsreduce)
    60000    0.249    0.000    0.808    0.000 _methods.py:53(_mean)
       60    0.249    0.004    9.315    0.155 power.py:829(_compare_distributions)
   270000    0.197    0.000    0.473    0.000 numeric.py:464(asanyarray)
```

**Comment by wasade** [comment]
So this is much faster likely as it avoids the indexing in pandas.

The bulk of the expense now is within numpy and scipy. There aren't many
targets to optimize. It may make sense to explore some level of parallelism
here but that is a larger can of worms as if that route is taken it needs
to be done in a fashion that is consistent with how skbio in general wants
to handle parallelism.

**Comment by jairideout** [comment]
@JWDebelius can this be closed now that #911 is merged?

**Comment by JWDebelius** [comment]
Yep.  #911 drastically increased the speed. (I didn't do formally profiling, but I went from running the AG samples overnight to under 2 hours). 
I still think this is a good candidate for parallelization, that's a larger discussion.

**Comment by mortonjt** [comment]
Awesome!

Keep in mind,  you can't parallelize the power code unless you pass in a
numpy RandomState object.

**Comment by jairideout** [comment]
Awesome, thanks @JWDebelius!
