### ISSUE TITLE
[0.2.3] TreeNode.extend seems to mangle the results

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#889]
@JTFouquier was working with the `TreeNode` object and was unable to make extend produce the expected results.

Here we create two subtrees and `append` them to a specific node on a scaffold.
http://hastebin.com/ewihulekib.py

When we change this to `extend` on the children, we would expect the root to be substituted by the scaffold node.
http://hastebin.com/qevonatuha.py
However, certain children are skipped in the extend resulting in two mangled trees.

This also occurs when using [`from_newick`](https://github.com/biocore/scikit-bio/blob/0.2.3/skbio/tree/_tree.py#L1945) instead of the new IO:
http://hastebin.com/ibuhicayaq.py

I believe this will require a `0.2.4` release.

**Comment by wasade** [comment]
Can you expand on the `from_newick` difference? I'm not seeing it in the
code above. The (incorrect) tree produced from extend seems to be the same
if its `from_newick` or `read`?

I think I see what's going on. The call to `TreeNode._adopt` is issuing a
`node.parent.remove`. This looks like it will modify the list that is being
iterated over in the `TreeNode.extend` call.

**Comment by ebolyen** [comment]
@wasade There isn't a difference, I was just trying to control for the new IO, by using the old IO.

The mutation of the mini_trees isn't really a problem, so much as the incomplete capture of their children. Notice when we compare the `append` to the `extend` we lose children.

**Comment by wasade** [comment]
Yes, which I believe is due to the modification of the iterable in the
`extend` call

**Comment by ebolyen** [comment]
@wasade Sorry I misunderstood your original comment. That definitely seems like the problem. 

Does it seem reasonable to tree to extend on the children of a different tree? That was the first thing that occurred to me to do.
