### ISSUE TITLE
Adding capability to convert multifurcating trees to bifurcating trees

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#896]
I know that there are some algorithms that can only work with bifurcating trees. 

Right now, I'm working on a function to convert a multifurcating tree to a bifurcating tree.
Once this is done, mind if I could submit a PR for it?

**Comment by mortonjt** [comment]
The bifurcating tree code is ready to push for a PR!

**Comment by jairideout** [comment]
Thanks @mortonjt! @wasade or @ebolyen can you please let @mortonjt know how to proceed with this feature addition?

**Comment by jairideout** [comment]
Fixed in #904.
