### ISSUE TITLE
Add BLAST parser

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/scikit-bio#899]
Are there any plans in getting a BLAST parser added to the project?

**Comment by RNAer** [comment]
+1. it would be useful. and there are other pieces of software such as
diamond, with output format compliant to the same format.

**Comment by ebolyen** [comment]
That would be awesome, is there anyone interested in contributing the necessary logic to IO?

**Comment by antgonza** [comment]
I think it will be great to add not only the "classic" format (what
qiime uses) but also the new version and sortmerna blast output, which
I think is the same than the newest blast output.

**Comment by rob-knight** [comment]
You probably want to start with the one from pycogent which has a fair amount of development behind it…

On Apr 21, 2015, at 9:45 AM, Evan Bolyen <notifications@github.com<mailto:notifications@github.com>> wrote:


That would be awesome, is there anyone interested in contributing the necessary logic to IO?

**Comment by ebolyen** [comment]
@antgonza :+1: this falls into the idea of versioned formats for IO, (we don't have this yet, but we have always expected a need for it).

**Comment by gregcaporaso** [comment]
:+1: for starting with cogent parser, and for supporting BLAST and BLAST+ output formats (I don't know off-hand what the differences are).

**Comment by gregcaporaso** [comment]
It would also be awesome to support reading a BLAST (e.g. bl9) file into a BIOM table, where you parameterize similarity thresholds, etc. This would allow us to very easily compare read mapping approaches that support bl9, which is a lot of them (diamond, blat, vsearch, usearch, blast, ...). We have some basic support for this in QIIME now that could easily be adapted. 

I might be able to work on this, so will assign to myself for now since I'm pretty familiar with what already exists.

**Comment by ElDeveloper** [comment]
That's awesome!

**Comment by anderspitman** [comment]
I'd be happy to help if necessary. This would be a fairly straight forward transition from my work on #781.

**Comment by gregcaporaso** [comment]
Ok, let's chat about it asap and figure out a plan for who will do what.

**Comment by anderspitman** [comment]
Sounds good.

**Comment by gregcaporaso** [comment]
@anderspitman and I are going to discuss this shortly.

Some of my initial thoughts: Initial support should be for the blast "tabular" (i.e., ``-m8``) format. This is the format that is generated by the different mappers that I mentioned above, and is also generated by BLAST+ with ``-outfmt 6``, so seems like a logical place to start. If this parser ignores lines starting with ``#``, it also supports the ``-m 9`` and ``-outfmt 7`` formats in BLAST and BLAST+ respectively. 

The natural object for this result would be a DataFrame, but memory will be an issue (which is what we did in cogent with the ``MinimalBla[s]t*`` parsers) for large queries (e.g., I've generated these using blat for metagenome sequences, and the output file is massive), so we probably want both options (the base functionality can be an iterator, and then we can have a wrapper that converts to a DataFrame). 

One unfortunate issue with the BLAST+ customizable ``-outfmt 6`` is the missing header information, [discussed here](http://blastedbio.blogspot.com/2014/11/column-headers-in-blast-tabular-and-csv.html). We could handle that in the parser by defaulting to the standard column headers:

``
Query id, Subject id, % identity, alignment length, mismatches, gap openings, q. start, q. end, s. start, s. end, e-value, bit score
``

and allowing the user to override those in the case where they customized their BLAST+ output format.

**Comment by genomematt** [comment]
It is also worth doing a check of the type pattern with -outfmt 6 to see if it is consistent with the assumed headers

**Comment by gregcaporaso** [comment]
@genomematt, this would just be to parse the results though, so wouldn't assume that BLAST+ was installed. Would that require BLAST+ be installed?

**Comment by wasade** [comment]
@gregcaporaso, the BIOM table idea sounds really awesome. Good call

On Tue, Apr 21, 2015 at 4:27 PM, Matthew Wakefield <notifications@github.com

**Comment by gregcaporaso** [comment]
@genomematt, I think I understand now - we can check the types without calling BLAST+.

**Comment by wasade** [comment]
Thinking slightly further, there is a general case here with respect to
biom. What you want is, given a tabular file, a way to indicate what is the
column ID, row ID, and what to pack into the filled in value. Once this
method is in place, which is fairly light, extending it to blast or other
apps that dump tabular would be easy. The open question is about the rest
of the data that are in the tabular file as it isn't query or subject
metadata, so perhaps something like:

def tab_to_biom(tab_fp, row_idx, col_idx, val_idx, sep='\t'):
     # ghetto
     other_details = {}
     rcv = []
     for line in tab_fp:
        fields = line.strip().split(sep)
        rcv.append((fields[row_idx], fields[col_idx], fields[val_ids]))
        other_details[(fields[row_idx], fields[col_idx])] = fields

    return Table(rcv), other_details

...

**Comment by gregcaporaso** [comment]
Re: parsing into a DataFrame, I have a quick-and-dirty example [here](http://nbviewer.ipython.org/github/gregcaporaso/qdr-issue14/blob/master/analyses.ipynb) that I just remember. That might be useful as a reference. 

@wasade, remember that by default with the BLAST tabular output we can have multiple hits per query (so that's why I mentioned filtering by e-value threshold, etc). What you're describing though would be really simple if the BIOM table itself were a DataFrame as you could load the tab-separated text file you mention, then use ``groupby(...).sum()``, and I think that'd give you that data.

**Comment by wasade** [comment]
Do you mean the query hitting the subject multiple times, or the query
hitting multiple subjects? Former is annoying, latter is taken care of
free. With the `groupby(...).sum()`, what would the entires in the biom
table be, number of times the query hit the subject?

**Comment by gregcaporaso** [comment]
Both are common with BLAST. 

With ``groupby(...).sum()``, it'd depend on what you have in the ``DataFrame``. In the case of BLAST, I'd see filtering that between parsing the BLAST result and building a BIOM table to contain only the hits that you want to consider. I think is getting a little off-topic here though, I'll bring this idea up on the biom tracker instead later and link back to here (need to run now).

**Comment by wasade** [comment]
Sounds good, thanks!

**Comment by gregcaporaso** [comment]
@anderspitman, @ebolyen, and @jairideout and I just a brief call to discuss this. We're going to start with support for the tabular formats for BLAST and BLAST+, as I mention above. 

@anderspitman, [here](https://github.com/pycogent/pycogent/blob/master/tests/test_parse/test_blast.py#L157) is the test data in PyCogent that I mentioned, though it's a little sparse. I'll email you a few more examples.

**Comment by anderspitman** [comment]
@gregcaporaso great, thanks!

**Comment by ElDeveloper** [comment]
Just FYI here's @wasade's implementation that's currently in use in Platypus-Conquistador.

https://github.com/biocore/Platypus-Conquistador/blob/master/platypus/parse.py#L31

**Comment by wasade** [comment]
This really is just minimal though and I think we want a richer object on
top like what was in cogent

**Comment by jairideout** [comment]
Closing in favor of #1110.
