### ISSUE TITLE
io should support reading from URLs

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#900]
This will most likely involve updating [``open_files``](https://github.com/biocore/scikit-bio/blob/master/skbio/io/util.py#L92) to pull files from URLs with ``requests`` to temporary files (as generated by the python ``tempfile`` module). 

Note that ``open_file`` is deprecated, so don't need to do any work there.

**Comment by wasade** [comment]
I don't think all IO methods would need to go via an intermediary. For instance, couldn't `parse_fasta` just read directly from a socket?

**Comment by ebolyen** [comment]
@wasade we would be reading from the socket object (more or less). What this is meant to address is allowing "smart" handling of URLs where you could say: `Alignment.read("http://example.com/something.fasta")` and IO would recognize it is a URL, and open a file handle (we are going to use ``requests``). This is similar to how you can pass a filepath instead of a fileobject.

**Comment by wasade** [comment]
Yup. Just was wondering the need for using `tempfile` (in all cases)

**Comment by ebolyen** [comment]
@wasade Oh I understand your comment now. Sorry, the tempfile thing wasn't made super clear in the original post. The tempfile would be in support of basic caching, that way if a format isn't given, each sniffer (as IO tests the file) isn't downloading a fresh copy each time.

**Comment by wasade** [comment]
Ah, okay. The concern I have is if it is always creating a temp file and
storing all of the retrieved data, then sourcing from some large remote
file will bloat /tmp. This is not usually a problem, but it is a problem in
shared environments. For instance, the pando compute nodes are 64-threads
but only like 90GB of /tmp, and typically running jobs from many users at
once. We've had /tmp issues in these envs previously.

**Comment by genomematt** [comment]
What about using a http Range request to get just the start of the file for format sniffing.  You need to do two server requests but the first is much more lightweight (at least on servers that support range queries).
Failure is relatively graceful if costly as you get the whole file back.

**Comment by gregcaporaso** [comment]
@wasade, note that you can customize where temp files get written with the ``tempfile`` module based on one of a few environment variables (described [here](https://docs.python.org/2/library/tempfile.html#tempfile.tempdir)).

**Comment by wasade** [comment]
Ya, but that doesn't mean programs like QIIME are setting it
