### ISSUE TITLE
travis-ci improvements

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#906]
The travis build could be improved by:

- [x] ~~building docs in a separate job~~
- [x] ~~testing coverage (without doctests) in a separate job to prevent doctests from inflating coverage~~

**Comment by anderspitman** [comment]
Probably also useful:
- [ ] Many of the pip packages are also available in conda now.

- [ ] We should use a `requirements.txt` [file for conda](https://groups.google.com/a/continuum.io/forum/#!topic/conda/PiM9sjWyXFU)

**Comment by anderspitman** [comment]
I've also noticed that travis seems to start 3 of our builds at the same time, but wait a while for the 4th. Might want to try and collapse it down to 3 builds.
