### ISSUE TITLE
create skbio.sequence.stats and initially populate with sequence distance metrics

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#913]
This will be where we store sequence-specific statistics. Two initial functions that we'll include here will be ``hamming`` and ``kmer_distance``. 

- [x] ``hamming`` will be a wrapper around ``scipy.spatial.distance.hamming``, which takes two ``skbio.Sequence`` objects, confirms that they are the same length as raises an informative error if not, converts them into input to ``scipy.spatial.distance.hamming`` (i.e., by accessing the ``sequence`` attribute), and returns the result. This will let us remove the metric-specific check for sequence length in ``skbio.Sequence.distance``. 

- [ ] ``kmer_distance`` will take two ``skbio.Sequence`` objects, ``k`` (the kmer length), and probably a flag indicating whether the metric should be qualitative (presence/absence of kmers only) or quantitative (compares abundances of kmers), and return the fraction of unique kmers between the pair of sequences. [This implementation](https://github.com/gregcaporaso/An-Introduction-To-Applied-Bioinformatics/blob/master/iab/algorithms/__init__.py#L769) can be ported or used as a starting point.

``skbio.Sequence`` should then be updated to support these functions, and all metric-specific error checking should be removed from that method.

**Comment by ebolyen** [comment]
:+1:

**Comment by jairideout** [comment]
@Kleptobismol are you interested in working on this?

**Comment by Kleptobismol** [comment]
Yes.

**Comment by Kleptobismol** [comment]
@gregcaporaso the analysis that ``kmer_distance`` performs appears to be qualitative--finding only how many unique kmers exist. Should this be the default functionality as opposed to quantitative? Also, I have no problem writing tests for this ported code, but I cant seem to find any tests in your code. Are there any? Thanks!
