### ISSUE TITLE
remove custom numpydoc distro and `.. shownumpydoc` hack

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/scikit-bio#919]
`.. shownumpydoc` is currently used to show the numpy doc for the dunder (i.e., ``__<whatever>__``) methods, but these tend to clutter the API web docs (see *Methods* [here](http://scikit-bio.org/docs/0.2.3/generated/skbio.sequence.BiologicalSequence.html#skbio.sequence.BiologicalSequence), and prevent us from using the latest and greatest ``numpydoc`` (e.g., the new ``Yields`` section). We should drop the `.. shownumpydoc` and the customized numpydoc distro. 

Once this change goes in, we should update to the latest ``numpydoc``.

**Comment by ebolyen** [comment]
Reminder: we will need our own extension soon to monkey-patch a certain decorator for our docs. (Currently in the numpydoc __init__ file)

**Comment by ElDeveloper** [comment]
Can this be contributed to upstream?

**Comment by gregcaporaso** [comment]
> Can this be contributed to upstream? 

I was about ask the same thing.
