### ISSUE TITLE
Stable, experimental and deprecated functionality

### ISSUE THREAD

**Issue by wasade** [biocore/scikit-bio#923]
A user should know:

- Whether functionality is stable, experimental or deprecated
- If the functionality is deprecated, the user should have an expectation about when it will be removed, and why
- If the functionality is experimental, the user should know when the functionality was added

A developer can specify the status of functionality. Experimental functionality is to be experimental for <= 2 releases. If > 2 releases, the release manager must explicitly mark the functionality as overdue for the given release. 

All experimental code is to be placed under `skbio.experimental`. Any import from from `skbio.experimental` will raise a warning.

A developer can learn about how to mark methods through `CONTRIBUTING.md`

A state diagram for functionality:
 
![hackpad com_2fyrtr6iinw_p 327785_1431380076978_slide1](https://cloud.githubusercontent.com/assets/474290/7576014/0449259e-f7f7-11e4-8056-811c92f9c6af.jpg)

**Comment by gregcaporaso** [comment]
This was addressed in #945.
