### ISSUE TITLE
skbio.stats.gradient unit test failure

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#930]
With the latest version of the `natsort` package, the following `skbio.stats.gradient` unit test fails:

```
======================================================================
FAIL: test_make_groups_natural_sorting (skbio.stats.tests.test_gradient.GradientANOVATests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "skbio/stats/tests/test_gradient.py", line 740, in test_make_groups_natural_sorting
    self.assertEqual(ga._groups, exp_groups)
AssertionError: defaultdict(<type 'dict'>, {'Col2': {'-42.0': ['a1'], '5': ['a10', 'a-10'], '1.0': ['a2'], '2e-5': ['a11.0']}, 'Col1': {'foo': ['a2', 'a11.0', 'a-10'], 'bar': ['a1', 'a10']}}) != {'Col2': {'-42.0': ['a1'], '5': ['a-10', 'a10'], '1.0': ['a2'], '2e-5': ['a11.0']}, 'Col1': {'foo': ['a-10', 'a2', 'a11.0'], 'bar': ['a1', 'a10']}}
```

@josenavas is this a legitimate failure or does the test just need to be modified to be less strict?

**Comment by josenavas** [comment]
@jairideout I'm unsure on what to say. It all comes down on how natural sorting is defined. It looks like in this latest version, `natsort` changed the definition of natural sorting.

Before, the correct sorting was: `['a-10', 'a10']`, but now is sorting those strings like this: `['a10', 'a-10']`. Those strings represent sample names and they sorting is used to state the sorting in the gradient.

If we agree with `natsort` definition of natural sorting, then we should simply change the test. However, if we think that the previous definition is correct, we will need to implement our own natural sorting...

IMOO, I would use natsort, as I'm sure they have good reasons to have changed that, probably useful to take a look to their changelog?

@antgonza do you have any thoughts on this?

**Comment by antgonza** [comment]
Agree on following natsort definition.

**Comment by ebolyen** [comment]
@josenavas since the difference is purely cosmetic, I will update the tests and bump the minimum version.

**Comment by josenavas** [comment]
@ebolyen note that the difference is not purely cosmetic. It actually defines the order in which the samples should be analyzed. That's why I was rising the concern about the "correct" natural sorting.

In that case, it should be ok, but if natsort keeps changing their definition of "natural sorting" it is possible that the analysis won't be reproducible. At this point it is ok, as AFAIK, this code has not been used anywhere (it is some analysis that @antgonza and I where doing, but it is right now on the backlog). This is used for time series analysis.

**Comment by ebolyen** [comment]
@josenavas They say this:

> The default sorting algorithm for natsort has changed in version 4.0.0 from signed floats (with exponents) to unsigned integers. The motivation for this change is that it will cause natsort to return results that pass the "least astonishment" test for the most common use case, which is sorting version numbers. If you relied on the default behavior to be signed floats, add alg=ns.F | ns.S to your natsort calls or switch to the new realsorted function which behaves identically to the older natsorted with default values. For 99% of users this change will not effect their code... it is only expected that this will effect users using natsort for science and engineering. This will also affect the default behavior of the natsort shell script.

Out of curiosity, why does the sample id have any bearing on the order of analysis? Doesn't that imply I can manipulate the results by changing ids? (Or perhaps I completely misunderstand where this id comes from)

**Comment by josenavas** [comment]
The default behavior if the user doesn't provide a column for sorting their values it's using the sample ids. Anyway, if the user provides a column to sort the samples, we cannot make sure that we are using a numeric column, which will lead to the same behavior.

Given that they point out that this will change the results on science and engineering, I think we should start using their new `realsorted` function, which will output the same results.

**Comment by jairideout** [comment]
> I think we should start using their new realsorted function, which will output the same results.

:+1:, and update setup.py to rely on natsort >= 4.0.0. Is anyone available to work on a PR with this fix?

> At this point it is ok, as AFAIK, this code has not been used anywhere (it is some analysis that @antgonza and I where doing, but it is right now on the backlog). This is used for time series analysis.

This code is used in QIIME's compare_trajectories.py script. @gregcaporaso and I have updated QIIME's setup.py to specify natsort < 4.0.0 to retain the current sorting behavior.
