### ISSUE TITLE
Underscores in newick tip names get removed

### ISSUE THREAD

**Issue by wwood** [biocore/scikit-bio#934]
Hey, I'm using skbio to clean up some newick files since it is more flexible than some, but ran into this:
```
import io
import skbio
skbio.tree.TreeNode.read(io.StringIO(u"((a_2,b)c,(d,e)f)root;")).to_newick(escape_name=False)
#=> '((a 2,b)c,(d,e)f)root;'
```
I wasn't expecting skbio to remove the `_` after the `a`, i.e. I was expecting
```
#=> '((a_2,b)c,(d,e)f)root;'
```

This is with 0.2.3, I attempted to install from master branch but was unable to - apologies if this is a duplicate.

Thanks,
ben

**Comment by ebolyen** [comment]
Hey @wwood, `to_newick` is deprecated, we recommend using `write` or `str` instead. So your command should look like this:

```
In [1]: import io

In [2]: import skbio

In [3]: str(skbio.tree.TreeNode.read(io.StringIO(u"((a_2,b)c,(d,e)f)root;")))
Out[3]: '((a_2,b)c,(d,e)f)root;\n'
```

`write` is called internally by `str`

**Comment by josenavas** [comment]
Hey @wwood,

accordingly to the newick format, the "_" characters are interpreted as spaces, so that is another thing to take into account.

**Comment by ebolyen** [comment]
@josenavas The problem is that the `_` characters are being replaced with spaces when encoded, which is exactly the opposite of what one would want to have happen.

The new `reader` and `writer` do not have this issue.

**Comment by wwood** [comment]
Hi, thanks for the quick response. Somehow I'd noticed `from_newick` was deprecated, but missed that `to_newick` was too. 

However, my larger problem is not solved, because I specifically do not want single quotes around the names as FastTree doesn't recognise the quotes as far as I can tell. (hence `escape_names=False`). Is there some way to do this with `str` or otherwise? e.g. replicate
```
t = skbio.tree.TreeNode.read(io.StringIO(u"(('a_2','b')'c',('d','e')'f')root;"))

In [11]: t.to_newick(escape_name=False)
Out[11]: '((a_2,b)c,(d,e)f)root;'
```
whereas with str
```
In [10]: str(t)
Out[10]: "(('a_2',b)c,(d,e)f)root;\n"
```

**Comment by ebolyen** [comment]
@wwood I see what is happening. Your name starts out as `'a_2'` because it is already escaped (with the quotes) it will treated as a literal string resulting in a node which has `a_2` as its name. When that is written again, `a_2` will be escaped as the node's name has an `_` (it isn't converting with a simple replace it because it isn't a space). According to what little standards seem to exist, this behaviour is the most correct, and loses the least amount of information.

To solve your problem specifically, you can just iterate over each node and replace it's name like so:
```
In [1]: import io; import skbio

In [2]: t = skbio.tree.TreeNode.read(io.StringIO(u"(('a_2','b')'c',('d','e')'f')root;"))

In [3]: for n in t.traverse():
    n.name = n.name.replace('_', ' ')

In [4]: str(t)           
Out[4]: '((a_2,b)c,(d,e)f)root;\n'
```

**Comment by ebolyen** [comment]
Essentially it will only quote something if one of the characters in the name is in `set(",:_;()[]")`. So if you have any of those you might want to replace them as well. Otherwise it will always choose the simplest escaping possible.

**Comment by wwood** [comment]
OK, makes sense - I agree that is the most correct behaviour.
