### ISSUE TITLE
Request: Add more flexibility to `assign_ids`

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#936]
Right now, the only way to use `assign_ids` within `TreeNode` objects is to assign the ids according to a postorder topology.

It would be awesome if the user can pass in an arbitrary ordering (i.e. levelorder) and can call this function as follows

```
t = TreeNode.read(tree_file)
t.assign_ids( t.levelorder() )
```

**Comment by wasade** [comment]
Can you describe a use case please? One issue with allowing a user to define the ordering is that the order information then needs to be stored on the tree in order to know how to interpret the IDs.

**Comment by mortonjt** [comment]
Right now, I'm writing up an algorithm that constructs a DP matrix from a tree (traversing the tree bottom up).  Having the nodes ID'ed in according to a level order fashion would make it significantly easier to index the DP matrix.

**Comment by wasade** [comment]
Oh, nice! What about just doing the decoration yourself?

for dp_id, node in enumerate(self.levelorder()):
   node.dp_id = dp_id

I'm still concerned about the ambiguity that can arise if
TreeNode.assign_ids can support different orderings.

**Comment by mortonjt** [comment]
Yup.  That's exactly what I'm doing right now.  I was just curious to see if there was any interest to have this capability integrated, since it may not be straightforward to ID the nodes without the modifying the skbio source code.

But after giving it a little more thought, this might not is a problem.  The below works fine without modifying the skbio source code.
```
t = TreeNode.read(tree_file)
for dp_id, node in enumerate(t.levelorder()):
   node.id = dp_id
```
Thanks!  Consider this closed.
