### ISSUE TITLE
define scikit-bio version in a single place

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#939]
Currently, scikit-bio's version is stored in `skbio.__version__` and `setup.py`. It'd be nice to only store this info once.

**Comment by ElDeveloper** [comment]
@wasade did the following (which is based on Flask's setup.py) for moi:
https://github.com/biocore/mustached-octo-ironman/blob/master/setup.py#L15-21

**Comment by jairideout** [comment]
Awesome, thanks!

**Comment by wasade** [comment]
Flask is so awesome...
