### ISSUE TITLE
BUG: skbio.diversity.alpha.lladser_pe

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#940]
Looks like this function can return uncovered probabilities greater than 1.

**Comment by mortonjt** [comment]
In addition, I see that there is a np.random.shuffle method embedded within this method.  
It will probably be a good idea to include a numpy RandomState parameter

**Comment by jairideout** [comment]
Some discussion started on the mailing list, including a code sample that reproduces the bug (thanks @mortonjt):

```python
from __future__ import division
from skbio.diversity.alpha import lladser_pe
from skbio.stats.composition import closure
import numpy as np

np.random.seed(0)
pvals = closure(np.random.geometric(1/10000, size=10000))
samp_table = np.array([np.random.multinomial(n=1000, pvals=pvals)
                       for i in range(1000)])
table = np.apply_along_axis(lladser_pe,  1, samp_table)
print (table > 1).sum()
```

@jensreeder is going to look into this.

**Comment by Jorge-C** [comment]
:+1: on the RandomState parameter.

**Comment by jensreeder** [comment]
Regarding the RandomState, I noticed that all the other functions in skbio that rely on some sort of randomness (e.g. np.random.sample, np.random.choice) also don't allow a RandomState param.

I think this is something that should either be handled consistently across skbio or not at all.
For testing you can always  set numpy.random.seed() before calling this function. As long as you have no concurrent threads, this does the trick.

**Comment by jairideout** [comment]
@jensreeder I agree.

Adding a random state parameter isn't necessary for this bug fix. @mortonjt can you please create a separate issue for this feature request so that discussion related to it will happen there?

**Comment by jensreeder** [comment]
I discussed with Manuel, the mathematician behind this method,  and we do not consider this to be a bug. The point estimator is unbiased, which means that the expected value of the estimator (the mean of multiple independent predictions) is the true value. Practically this means for p close to 1, predicted values will scatter around 1, with some larger than 1.
The distributions generated in the code above are actually pretty flat. The majority of species are seen exactly once, with a few seen twice, three or four times. This is a strong indicator that the list of already seen species has a very low probability and the uncovered probability is close to 1, thus causing the estimator to predict values larger than 1 sometimes.

If we were to artificially limit the point estimates to 1, we would turn the predictor into a biased estimator and the math behind it will not hold up anymore.

Thus, I propose to leave the method as is.

**Comment by mortonjt** [comment]
I just talked to Manuel.  Looks like it is a "problem" with the theory ...

That being said, at the very least, we need to update the documentation.  We can't have people using this thinking that it'll always return real probabilities.

**Comment by ebolyen** [comment]
Thanks for looking into this @jensreeder and @mortonjt! Would either of you be up to sending in a PR with the doc updates?

**Comment by jairideout** [comment]
Thanks for tracking this down @jensreeder @mortonjt! Thanks for the doc update @mortonjt
