### ISSUE TITLE
random distance matrices aren't always symmetric

### ISSUE THREAD

**Issue by Jorge-C** [biocore/scikit-bio#943]
[This line](https://github.com/biocore/scikit-bio/blob/master/skbio/stats/distance/_base.py#L772) does not create symmetric matrices (since it's modifying it in place, it depends on how numpy will traverse the memory to make the updates).

Fortunately, this is caught by the `DistanceMatrix` constructor.

**Comment by mortonjt** [comment]
Hmm.  Nice catch!  Sounds like it can just be fixed with
```
data = data + data.T
```
Want to submit a PR for it?

**Comment by Jorge-C** [comment]
I don't mind, this could be the most gentle introduction to contributing to skbio. The code fix is trivial as you pointed out and so they could focus on git, running the test suite locally, adding a test case that shows the failure, etc. If keeping a few of these tiny issues open can be useful in the short term I'll leave it as is, otherwise I'll fix it!

**Comment by jairideout** [comment]
Let's keep this open for a few more days in case someone new to scikit-bio development wants a quick fix to work on. Thanks for reporting this @Jorge-C!

**Comment by johnchase** [comment]
@jairideout  I can work on this if you want to assign it to me, or I can leave it. If anyone else wants to work on this, the code has been modified so the link in the initial post doesn't point to the correct line. The line that needs to be modified is: 
```python 
    data += data.T
```
Which should be fairly apparent from @mortonjt's comment

**Comment by jairideout** [comment]
Assigned to you, thanks @johnchase!

**Comment by antgonza** [comment]
If a distance matrix is not symmetric, is it still a distance matrix? In other words, should this be allowed?

**Comment by jairideout** [comment]
No, it is explicitly disallowed (this check happens in the `DistanceMatrix` constructor). This is just a bug in `randdm`, which is a utility function for creating random distance matrices.

**Comment by antgonza** [comment]
Got it, thanks.
