### ISSUE TITLE
Freeze Minimum Dependencies 

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#955]
When we release beta, we should freeze the minimum dependency for every package at whatever is the latest at that time. We can then keep these up to date moving forward as package APIs change.

**Comment by ebolyen** [comment]
![](http://api.ning.com/files/It3-odgnrfRu7Z9VNG6pP1qhlsWV2cuEEFSKpW9XCtPFlf2-2A0VuRmU-YZW-p0GrPpVKYRGyc3BAaj0GqNqh2GD0wNednF-/back2future.png)

**Comment by ElDeveloper** [comment]
[.](https://github.com/ElDeveloper/ITTDMMAWHTTTF)

**Comment by gregcaporaso** [comment]
:+1:
