### ISSUE TITLE
TreeNode#prune not removing nodes

### ISSUE THREAD

**Issue by wwood** [biocore/scikit-bio#970]
Hi,

I'm having some trouble understanding this behaviour, and am wondering it is a bug. Basically, `prune` does not appear to remove nodes when I expected it to:

```
In [31]: t2 = skbio.TreeNode.read(StringIO.StringIO("((a,b),(c,d))root;"))

In [25]: print t2.ascii_art()
                    /-a
          /--------|
         |          \-b
-root----|
         |          /-c
          \--------|
                    \-d

In [32]: t2.find('a').parent.remove(t2.find('a'))
Out[32]: True

In [33]: t2.find('b').parent.remove(t2.find('b'))
Out[33]: True

In [34]: print t2.ascii_art()
          /-
-root----|
         |          /-c
          \--------|
                    \-d

In [35]: t2.prune()

In [36]: print t2.ascii_art()
          /-
-root----|
         |          /-c
          \--------|
                    \-d
```

i.e. I expected there not to be the branch at the top. `remove_deleted` acts in the same way

```
In [37]: t2 = skbio.TreeNode.read(StringIO.StringIO("((a,b),(c,d))root;"))

In [38]: t2.remove_deleted(lambda x: x.name in ('a','b'))

In [39]: print t2.ascii_art()
          /-
-root----|
         |          /-c
          \--------|
                    \-d

In [40]: t2.prune()

In [41]: print t2.ascii_art()
          /-
-root----|
         |          /-c
          \--------|
                    \-d
```

I am able to workaround by using `remove` and then `prune` for each node:

```
In [6]: t2 = skbio.TreeNode.read(StringIO.StringIO("((a,b),(c,d))root;"))

In [7]: t2.find('a').parent.remove(t2.find('b'))
Out[7]: True

In [8]: t2.prune()

In [9]: t2.find('a').parent.remove(t2.find('a'))
Out[9]: True

In [10]: t2.prune()

In [11]: print(t2.ascii_art())
                    /-c
-root---- /--------|
                    \-d
```

Thanks,
ben

**Comment by wasade** [comment]
Prune collapses single descendent nodes, in your first example, there
doesn't exist a single descendent node as the root has two children: one
internal node with two tips, and a tip. Perhaps the documentation should be
more explicit here?

**Comment by wwood** [comment]
Hmm, so how does one clean up the tree after a call to `remove_deleted` when multiple nodes are removed? Also I wondered if it might be easier to implement the pruning as you are removing, so global tree searches are not necessary.

This is all hypothetical for me though, as the "workaround" (which I guess is actually what I am supposed to be doing) works fine for my particular situation. So close away if you think appropriate.

Thanks. ben

**Comment by wasade** [comment]
I guess I don't understand how `prune` isn't doing the cleanup, or what cleanup you're looking for? Do you want to remove all resulting tips which were originally internal nodes? In which case, you may be better off using `subtree` and fetching just the tips you care about.

Note, the tree in your work around may not be what you want as it is has a single descendent from the root (`((c,d));`) and can be collapsed back to `(c,d);`. I'm a bit surprised that `prune` didn't catch that, however, it may be that `prune` needs to be applied multiple times.

**Comment by wwood** [comment]
Oh I see. `subtree` I thought was a subtree in the sense of a TreeNode and its children, which I guess is a almost superfluous in skbio where a tree is a treenode. Actually the comment "Make a copy of the subtree" would imply my original understanding was correct. Cannot test this, at least in 0.2.3:
```
In [3]: t2 = skbio.TreeNode.read(StringIO.StringIO("((a,b),(c,d))root;"))

In [4]: t2.subtree(['c','d'])
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-4-b95660384ddf> in <module>()
----> 1 t2.subtree(['c','d'])

/usr/local/lib/python2.7/dist-packages/skbio/tree/_tree.pyc in subtree(self, tip_list)
    654     def subtree(self, tip_list=None):
    655         r"""Make a copy of the subtree"""
--> 656         raise NotImplementedError()
    657 
    658     def subset(self):
```
What I'm after is a function that removes a list of tips (or takes a lambda function) and removes them from the tree. Also it cleans the tree such that there are no nodes of degree 1, and no new tips are created. Maybe it could be like this:
```
def prune_tips(tip_list):
    for tip in tip_list:
        # remove tip from tip's parent
        # if parent now has degree 1, remove parent and make sibling a direct child of grandparent
```
(though need to deal with e.g. removing tips directly connected to the root).

I think this definition is the same as that implemented in ete - http://pythonhosted.org/ete2/reference/reference_tree.html#ete2.TreeNode.prune

**Comment by wasade** [comment]
Have you tried `TreeNode.shear`?

**Comment by wwood** [comment]
No, hadn't seen that, seems perfect, perhaps it makes sense to add that as a "see also"? Thanks.

**Comment by wasade** [comment]
Docs were previously updated w.r.t. the see also
