### ISSUE TITLE
support for file formats of annotations

### ISSUE THREAD

**Issue by RNAer** [biocore/scikit-bio#986]
Formats list:
- [ ] gbk (http://www.ncbi.nlm.nih.gov/genbank/samplerecord/).
- [ ] gff version 3 (http://www.sequenceontology.org/gff3.shtml)

These 2 are widely used in sequence/genomic annotation. I think we should support them. I can implement if people think it is good to do that.

**Comment by ebolyen** [comment]
:+1: genbank is definitely on our list! With the new IO in, it wouldn't be a bad time to start working on expanding the list of formats we support. Ideally we can grow that list indefinitely.

**Comment by jairideout** [comment]
:+1: Thanks for working on this @RNAer!

**Comment by RNAer** [comment]
cool. for discussion, what class do you think a genbank entry read into? a new, child class of `Sequence` class?

**Comment by RNAer** [comment]
or a class with a `Sequence` instance as a member. This is inheritance vs. composition (http://stackoverflow.com/questions/49002/prefer-composition-over-inheritance).

**Comment by ebolyen** [comment]
We would want support for all 4 sequence types (DNA, RNA, Protein, and Sequence) we do not want to create objects specific to a format (StockholmAlignment was recently removed for example, we want to use Alignment for that). Fortunately skbio supports arbitrary metadata (global and positional) for sequence types.

**Comment by RNAer** [comment]
No class of formats makes sense. The positional metadata is a great
feature, but not ideal in this case. suppose you have 1000 genes in a
microbial genome (in real case, it is much more because you will have many
more sub-gene annotations). If I understand correctly, every single
annotation of genes, ncRNAs, etc., will be an array of genome length if
stored as positional metadata. we don't want to have tons of arrays of
genome length to blow up the memory, right? I think we need a coordinate
relevant metadata in Sequence object. This is an analogy to sparse matrix
representation.

By the way, does the io for Stockholm format exist after StockholmAlignment
is removed?

**Comment by rob-knight** [comment]
Quick note:

There are two separate use cases for sequence annotations:

1. You have a short sequence, several annotations that cover large chunks of the sequence. It makes sense to use a mask approach as described below, and use bitwise operations to combine features.

2. You have a long sequence, very large numbers of annotations that cover small chunks of the sequence (consider gene annotations on a 100 MB mammalian chromosome). You want to store the start and end of each feature, and add logic to combine features based on coordinates.

We usually cover case 1. Gavin usually covers case 2. This is why there are two completely separate feature annotation systems in pycogent — each method can handle cases that the other simply can’t. So be careful if planning to choose only one method for representation.

**Comment by ebolyen** [comment]
@RNAer, Sockholm's IO was also removed (this is temporary), much of that implementation was buggy due to a fault in the unit-tests (`__eq__` was inherited, so none of the metadata worked) that wasn't caught. 

You are also correct that annotations would result in 1000s of arrays. It is certainly inefficient, in fact one of our earlier iterations would have exposed an API that supported both slices and masks, however the Pandas API was deemed too valuable to not use. After all what is the point of having metadata if you can't query it?

I think for now we should just move forward with the many arrays to see how that feels (it also looks like Pandas may support [sparse](http://pandas.pydata.org/pandas-docs/stable/sparse.html) DataFrames). If it turns out Pandas won't be able to handle the sparseness of that kind of data (without an API break in skbio) then we may be able to experiment with third metadata category, though I would prefer to avoid it.

**Comment by ebolyen** [comment]
Thanks for the context @rob-knight!

**Comment by ebolyen** [comment]
Just played with pandas a bit. We can create sparse boolean vectors and attach them to arbitrary dataframes. I think we can keep the API AND have memory efficiency too!

**Comment by RNAer** [comment]
:+1: will look into that.

**Comment by RNAer** [comment]
Related to this topic. There is a parent-child relationship between features, such as an exon belongs to a gene (Note that this can't be inferred merely from coordinates because genes can overlap). would it make sense to have that in `Sequence`? I am thinking tree-like struct similar `TreeNode`.

**Comment by ebolyen** [comment]
@RNAer empty sequences are fine. As for parent-child relations, I don't think we need to explicitly model what you are describing.  Boolean vectors are really easy to operate on and an `|` expression should make the above possible. 
```
exon_gene_mask = seq.positional_metadata['exon'] | seq.positional_metadata['some_gene']
sliced = seq[exon_gene_mask]
```

**Comment by ebolyen** [comment]
Sorry it's early, I used exactly the wrong operator above, it's been corrected to `&`

**Comment by RNAer** [comment]
maybe I didn't explain clearly. The fact of a genetic feature located inside another does not neccessarily means it belongs to the other feature. Many annotations are overlapping. Like this:
````
gene A: ......======-----=========.........
gene B: ...............=================...
````
`=` is exon and `-` is intron.

**Comment by ebolyen** [comment]
Right sorry, rereading your last comment and I see what you were saying now. In this situation I think we would really just denormalize, so have "gene_b_exons" and "gene_a_exons" . @gregcaporaso thoughts?

**Comment by RNAer** [comment]
just wanted to check back on this thread. it is ok to ignore parent-child relationship for the time being and add that later if necessary?

**Comment by ebolyen** [comment]
I would say so, perhaps prefix anything for now and we can evaluate how that works out.

**Comment by RNAer** [comment]
:+1:  I'll start implementing the backbone and issue pull request to get quick feedback from you guys.

**Comment by ebolyen** [comment]
That would be awesome, thanks for working on this @RNAer!

**Comment by RNAer** [comment]
@gregcaporaso @ebolyen , after a second thought, I still strongly think that positional metadata is a bad idea. Take the following feature table from a genbank record as an example:
1) it will lose the info that the 5' end of the CDS is incomplete (as indicated by `<`)

2) I have to separate a feature into metadata (condon_start, product, protein_id, etc.) and positional metadata (location of the CDS). a feature is a logical unit. separate it into 2 parts is not a good idea, IMHO.

````
     CDS             <1..206
                     /codon_start=3
                     /product="TCP1-beta"
                     /protein_id="AAA98665.1"
                     /db_xref="GI:1293614"
                     /translation="SSIYNGISTSGLDLNNGTIADMRQLGIVESYKLKRAVVSSASEA
                     AEVLLRVDNIIRARPRTANRQHM"
````

I suggest adding a sequence feature class that encapsulate all the info of a feature into a single entity and attach the objects of that class to `Sequence` object. Any thoughts?

**Comment by RNAer** [comment]
and by the way, EMBL format use the same feature table in its record. So with feature class, we can easily write parser for EMBL file as well. a stone killing two birds?

**Comment by ebolyen** [comment]
@RNAer Thanks, I'll check out your PR shortly. Talked about this briefly with @gregcaporaso and we think we can probably represent this by having a list of features in our `metadata` and part of each feature can link out to their respective column on `positional_metadata`. I don't know if it's best to just put a reference to the series, or the column name, but regardless this will allow slicing and other operations on the sequence to propagate the positions correctly. As for partial coding sequences, a boolean in the feature for 3' and 5' should be enough.

Our big goal is to allow people to manipulate metadata arbitrarily via `pandas`. Creating a new object doesn't really help and will limit the kinds of questions that could be asked of the entire sequence or require a lot of custom code to ask those questions. (We also received VERY positive feedback on our decision to use pandas for positional metadata at SciPy.) 

There may yet be room for a feature class, but I think we should keep it very simple for now and just use a list of dicts in `metadata`. 

So your example might end up looking something like:

```
seq.metadata['features'] = [
    { ... },
    {
        "type: "CDS",
        "position": "COLUMN_NAME" or SparseSeries(),
        "5_partial": True,
        "3_partial": False,
        "codon_start": 3,
        "product": "TCP1-beta",
        "protein_id": "AAA98665.1",
        "db_xref": "GI:1293614",
        "translation": Protein("SSIYNGISTSGLDLNNGTIADMRQLGIVESYKLKRAVVSSASEAAEVLLRVDNIIRARPRTANRQHM")
    },
    { ... }

]
```
If there is an obvious ID for these features, a dict would be better than a list.

In this way the feature isn't so horribly split, but you can still look at all of the positions on their own via `pandas`. Of course it would be awesome if pandas supported metadata on `Series`, but that won't be happening for a while (or ever) from the looks of it. Perhaps `xray` would be worth a glance in the far future.

**Comment by gregcaporaso** [comment]
I agree with this, and we can always revisit later if the existing infrastructure isn't working for what we want.

**Comment by RNAer** [comment]
right on. what do you think to represent features on rev complementary strand with `positional_metadata`?

````
     gene            complement(join(97999..98793,69611..69724))
                     /gene="rps12"
                     /locus_tag="ArthCp001"
                     /trans_splicing
                     /db_xref="GeneID:1466250"
````

**Comment by ebolyen** [comment]
@RNAer I think that would be consistent with the partial starts/ends.
