### ISSUE TITLE
check argv to detect if install in setup.py

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#997]
this would avoid installing numpy even when `--help` is called on setup

**Comment by jairideout** [comment]
See qiime-default-reference for [an example](https://github.com/biocore/qiime-default-reference/blob/master/setup.py#L14) of how to do this.

**Comment by corburn** [comment]
I wonder if something like the following is what you had in mind:

``` Python
# numpy is not required with help or information display options
if any(arg.startswith('--') and arg not in ['--verbose', '--quiet', '--dry-run', '--no-user-cfg', '--command-packages'] for arg in sys.argv):
    setup_requires = []
else:
    setup_requires = ['numpy >= 1.9.2']
```

**Comment by jairideout** [comment]
That makes sense, thanks for the code! Are you interested in issuing a pull request?

**Comment by jairideout** [comment]
Closing in favor of #1296.
